/* POPS.ELF Decompiled - compiler.c */
/* Auto-generated by POPS Decompiler */
/* 69 functions */

#include "pops_types.h"
#include "functions.h"

/* Forward declarations */
u32 Compiler_Init(void);
u32 Compiler_FindCacheSlot(u32 a0);
u32 Compiler_FindOrAllocateSlot(void);
u32 Compiler_InitializeCacheSlots(void);
u32 Compiler_ClearCacheSlots(void);
u32 Compiler_EmitLoadStoreOp(u32 a0, u32 a1);
u32 Compiler_BuildBlockLinkage(u32 a0);
u32 Compiler_AllocateBlockSlot(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_CompileInstructionBlock(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_HandleBlockCompilation(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_ProcessMultipleBlocks(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_InitCacheBuffer(u32 a0);
u32 Compiler_EmitPrologue(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitEpilogue(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitRegisterLoad(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitRegisterStore(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitAddressCalculation(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitMemoryReference(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitArithmetic(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitLogicalOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitComparison(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitSpecialOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitLoadOpcode(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitStoreOpcode(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EmitImmediateOp(u32 a0, u32 a1);
u32 Compiler_EmitCoprocessorOp(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_LW(u32 a0, u32 a1);
u32 Compiler_Emit_SW(u32 a0, u32 a1);
u32 Compiler_Emit_LH(u32 a0, u32 a1, u32 a2);
u32 Compiler_CalculateBufferSize(u32 a0, u32 a1);
u32 Compiler_Emit_SH(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_LB(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EncodeLoadStoreAddressing(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_EncodeRegisterOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_SB(u32 a0, u32 a1);
u32 Compiler_Emit_ADD(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_ADDI(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_SUB(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_SUBI(u32 a0, u32 a1);
u32 Compiler_Emit_LUI(u32 a0, u32 a1);
u32 Compiler_Emit_JAL(void);
u32 Compiler_Emit_ImmediateArith(u32 a0, u32 a1);
u32 Compiler_Emit_IndirectJump(u32 a0, u32 a1);
u32 Compiler_EncodeNegateOp(u32 a0, u32 a1);
u32 Compiler_Emit_BiImmediate(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_LoadIndexed(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_SimpleArithmetic(u32 a0, u32 a1);
u32 Compiler_Emit_BranchLinkage(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_CoprocessorMove(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_MemoryLoadALU(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_MemoryStoreALU(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_GTEOperation(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_MultiplyDivide(u32 a0);
u32 Compiler_Emit_ShiftOp(u32 a0);
u32 Compiler_Emit_RotateOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_SystemCall(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Compiler_Emit_Exception(u32 a0);
u32 Compiler_Emit_InterruptCheck(u32 a0, u32 a1, u32 a2);
u32 Compiler_Emit_FloatLoad(u32 a0, u32 a1);
u32 Compiler_Emit_NoOp(void);
u32 Compiler_InitializeLookupTables(void);
u32 Compiler_InitializeGTEConstants(u32 a0);
u32 Compiler_MemoryCopy(u32 a0, u32 a1, u32 a2);
u32 Compiler_MemoryClear(u32 a0, u32 a1);
u32 Compiler_SetCacheFlushFlag(u32 a0);
u32 Compiler_RequestCacheFlush(u32 a0, u32 a1);
u32 Compiler_GetCacheStatus(void);
u32 Compiler_ClearCacheFlushFlag(u32 a0, u32 a1);
u32 Compiler_ResetCacheState(void);

/* ======================================== */

/* Function at 0x00204E70 - 0x00204FB8 */
u32 Compiler_Init(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3;
    ret = R3000_AllocTranslationBuffers();
    a0 = 8;
    a1 = 0x48;
    if (ret == 0) goto loc_204ED8;
    ret = EEKernel_SyscallWrapper(a0, a1);
    a1 = 0x48;
    v1 = ret;
    a0 = v1;
    g_jit_cache = v1;
    if (v1 == 0) goto loc_204ED8;
    ret = Compiler_MemoryClear(a0, a1);
    a0 = 0x00503B20;
    a1 = 0;
    a2 = 0x3060;
    ret = Libc_Memset(a0, a1, a2);
    a0 = g_jit_cache;
    return Compiler_InitializeGTEConstants(a0);
loc_204ED8:
    return ret;
}

/* Function at 0x00204FB8 - 0x00204FF8 */
u32 Compiler_FindCacheSlot(u32 a0)
{
    u32 ret, v1, a1;
    ret = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    a1 = 0;
    v1 = ret + -0x5600;
    do {
        ret = *(u32*)(v1 + 4);
        a1 = a1 + 1;
        if (ret == a0) {
            return *(u32*)(v1);
        }
        ret = ((signed)a1 < 0xa) ? 1 : 0;
        v1 = v1 + 0x10;
    } while (ret != 0);
    return 0;
}

/* Function at 0x00204FF8 - 0x00205038 */
u32 Compiler_FindOrAllocateSlot(void)
{
    u32 ret, v1, a0, a1, a2, a3;
    a1 = 0;
    ret = PSX_JIT_SLOTS;  /* 0x0024AA00 - JIT_CacheSlot array (10 slots) */
    a3 = 0;
    a2 = ret + 4;
    do {
        ret = *(u32*)(a2);
        a2 = a2 + 0x10;
        a3 = a3 + 1;
        v1 = a1 + 1;
        a0 = ((unsigned)a3 < 0xa) ? 1 : 0;
        if (ret == 0) a1 = v1;
    } while (a0 != 0);
    return a1;
}

/* Function at 0x00205038 - 0x00205078 */
u32 Compiler_InitializeCacheSlots(void)
{
    u32 ret, v1, a0;
    a0 = 1;
    ret = PSX_JIT_SLOTS;  /* 0x0024AA00 - JIT_CacheSlot array (10 slots) */
    v1 = 9;
    ret = ret + 0xc;
    do {
        v1 = v1 + -1;
        *(u32*)(ret + -8) = 0;
        *(u32*)(ret) = a0;
        ret = ret + 0x10;
    } while ((signed)v1 >= 0);
    return ret;
}

/* Function at 0x00205078 - 0x002050B8 */
u32 Compiler_ClearCacheSlots(void)
{
    u32 ret, v1, a0;
    a0 = 9;
    v1 = PSX_JIT_SLOTS + 4;  /* 0x0024AA00 - JIT_CacheSlot array (10 slots) */
loc_205088:
    ret = *(u32*)(v1);
    *(u32*)(v1) = 0;
    if (ret != 0) goto loc_205094;
loc_205094:
    a0 = a0 + -1;
    v1 = v1 + 0x10;
    if ((signed)a0 >= 0) goto loc_205088;
    return ret;
}

/* Function at 0x002050B8 - 0x00205110 */
u32 Compiler_EmitLoadStoreOp(u32 a0, u32 a1)
{
    u32 ret, v1, a2, a3, t0, t1;
    a0 = a0 << 4;
    a2 = PSX_JIT_SLOTS;  /* 0x0024AA00 - JIT_CacheSlot array (10 slots) */
    t1 = 0xAC000000;
    ret = a2 + a0;
    a3 = a0 + a2;
    v1 = *(u32*)(ret + 4);
    t0 = 0x03800000;
    ret = *(u32*)(a3);
    a2 = a2 + a0;
    v1 = v1 << 2;
    a0 = 1;
    v1 = v1 + 0x10;
    ret = ret << 0x10;
    v1 = v1 & 0xffff;
    ret = ret | t0;
    v1 = v1 | ret;
    ret = a1 + 4;
    *(u32*)(a1) = v1;
    *(u32*)(a2 + 0xc) = a0;
    return ret;
}

/* Function at 0x00205110 - 0x002051E0 */
u32 Compiler_BuildBlockLinkage(u32 a0)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a1, a2, a3, s0, i;
    s0 = PSX_JIT_SLOTS + 0xc;  /* 0x0024AA00 - JIT_CacheSlot array (10 slots) */
    i = 0;
loc_205130:
    ret = *(u32*)(s0 + -8);
    i = i + 1;
    if (ret == 0) goto loc_20515C;
    ret = *(u32*)(s0);
    i = i + 1;
    if (ret != 0) goto loc_20515C;
    a1 = a0;
    a0 = i;
    a0 = Compiler_EmitLoadStoreOp(a0, a1);
    i = i + 1;
loc_20515C:
    s0 = s0 + 0x10;
    if ((signed)i < 0xa) goto loc_205130;
    a1 = 0x00250000 + -0x560c;  /* JIT_CODE_CACHE: JIT compiled code cache */
    *(u32*)(a0) = *(u32*)(a1);
    a0 = a0 + 4;
    *(u32*)(a0) = 0xAF820004;
    a0 = a0 + 4;
    *(u32*)(a1) = 0;
    a1 = 0x00250000 + -0x5608;  /* JIT_CODE_CACHE: JIT compiled code cache */
    *(u32*)(a0) = *(u32*)(a1);
    a0 = a0 + 4;
    *(u32*)(a0) = 0xAF820008;
    a0 = a0 + 4;
    *(u32*)(a1) = 0;
    return a0;
}

/* Function at 0x002051E0 - 0x002052B8 */
u32 Compiler_AllocateBlockSlot(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0, t1, t2, t3, t4;
    t4 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    ret = t4 + -0x5600;
    s0 = 0xa;
    s1 = a2;
    t3 = a0;
    t2 = a1;
    t0 = ret + 0xc;
    t1 = 0;
    a2 = 0;
    v1 = *(u32*)(t0 + -8);
loc_205218:
    if (v1 == 0) {
        *(u32*)(s1) = a2;
    } else {
        ret = 0;
        if (v1 == t3) goto loc_20523C;
        ret = 4;
        if (v1 != t2) goto loc_20523C;
        ret = 0;
        loc_20523C:
        a1 = *(u32*)(t0);
        a0 = ret + 1;
        ret = ret + 2;
        if (a1 == 0) ret = a0;
        v1 = ((unsigned)t1 < (unsigned)ret) ? 1 : 0;
        t0 = t0 + 0x10;
        if (v1 != 0) {
            t1 = ret;
            s0 = a2;
        }
        a2 = a2 + 1;
        v1 = *(u32*)(t0 + -8);
        if ((signed)a2 < 0xa) goto loc_205218;
        ret = t4 + -0x5600;
        v1 = s0 << 4;
        ret = ret + v1;
        a0 = *(u32*)(ret + 0xc);  /* GTE data: vz1 */
        *(u32*)(s1) = s0;
        if (a0 == 0) {
            a1 = a3;
            a0 = s0;
            a3 = Compiler_EmitLoadStoreOp(a0, a1);
            *(u32*)(s1) = s0;
            }
        }
    return a3;
}

/* Function at 0x002052B8 - 0x00205408 */
u32 Compiler_CompileInstructionBlock(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, t0, t1, t2, t3, t4;
    ret = t2;
    s0 = a0;
    s3 = s0 << 2;
    v1 = *(u32*)(v1 + -0x6c40);
    a0 = a1;
    s1 = a3;
    s2 = t1;
    s5 = t0;
    a1 = a2;
    *(u32*)(s1) = v1;
    if ((signed)v1 < 0) {
        s4 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        *(u32*)(__sp) = 0;
        t3 = s4 + -0x5600;
        t1 = 0;
        t0 = 0;
        t4 = t3 + 4;
        a2 = t3 + 0xc;
            do {
                a3 = t0 << 4;
                ret = a3 + t4;
                v1 = *(u32*)(ret);
                t1 = t0 + 1;
                if (v1 == s0) {
                v1 = t1 << 4;
                if (s2 != 0) {
                    ret = a3 + a2;
                    *(u32*)(ret) = 0;
                }
                ret = t2;
                v1 = v1 + t3;
                a0 = *(u32*)(v1);
                *(u32*)(s1) = a0;
                } else {
                t0 = t1;
                ret = ((signed)t0 < 0xa) ? 1 : 0;
                *(u32*)(__sp) = t1;
                }
            } while (ret != 0);
            a3 = t2;
            a2 = __sp;
            ret = Compiler_AllocateBlockSlot(a0, a1, a2, a3);
            v1 = s4 + -0x5600;
            t2 = ret;
            ret = *(u32*)(__sp);
            a3 = ((unsigned)s2 < 1) ? 1 : 0;
            ret = ret << 4;
            a0 = ret + v1;
            a2 = v1 + ret;
            a1 = *(u32*)(a0);
            v1 = a2;
            *(u32*)(s1) = a1;
            *(u32*)(v1 + 4) = s0;
            *(u32*)(a2 + 0xc) = a3;
            if (s5 != 0) {
                v1 = *(u32*)(s1);
                ret = ret & 0xffff;
                a1 = 0x8C000000;
                v1 = v1 << 0x10;
                a0 = 0x03800000;
                ret = ret | a1;
                v1 = v1 | a0;
                ret = ret | v1;
                *(u32*)(t2) = ret;
                t2 = t2 + 4;
            }
            ret = t2;
        }
    }
    return ret;

/* Function at 0x00205408 - 0x00205590 */
u32 Compiler_HandleBlockCompilation(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, t0, t1, t2;
    s1 = a0;
    ret = s1 << 2;
    v1 = *(u32*)(v1 + -0x6c40);
    s2 = a2;
    s0 = t0;
    s3 = a1;
    s4 = a3;
    *(u32*)(s2) = v1;
    if ((signed)v1 >= 0) goto loc_205508;
    a1 = Compiler_FindCacheSlot(a0);
    *(u32*)(s2) = a1;
    if (a1 != 0) {
        a2 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = 0;
        a0 = a2 + -0x5600;
        ret = *(u32*)(a0);
            do {
                a0 = a0 + 0x10;
                if (ret != a1) {
                v1 = v1 + 1;
                }
                ret = *(u32*)(a0);
            } while (ret != 0);
            v1 = -1;
        }
        ret = a2 + -0x5600;
        v1 = v1 << 4;
        ret = ret + v1;
        *(u32*)(ret + 0xc) = 0;
        goto loc_205508;
    }
    t2 = s0;
    if (s1 != s3) {
        a0 = s1;
        a1 = 0;
        a2 = 0;
        a3 = s2;
        t0 = 0;
        t1 = 1;
        s0 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
        goto loc_205508;
    }
    a0 = s1;
    a1 = s1;
    a2 = 0;
    a3 = s2;
    t0 = 1;
    t1 = 1;
    s0 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
loc_205508:
    if (s1 == s3) {
        *(u32*)(s4) = *(u32*)(s2);
        goto loc_20556C;
    }
    v1 = s3 << 2;
    ret = ret + -0x6c40;
    v1 = v1 + ret;
    a0 = *(u32*)(v1);
    *(u32*)(s4) = a0;
    if ((signed)a0 >= 0) goto loc_20556C;
    a0 = s3;
    ret = Compiler_FindCacheSlot(a0);
    *(u32*)(s4) = ret;
    if (ret != 0) goto loc_20556C;
    t2 = s0;
    a0 = s3;
    a1 = s1;
    a3 = s4;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    s0 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
loc_20556C:
    return s0;

/* Function at 0x00205590 - 0x002057A8 */
u32 Compiler_ProcessMultipleBlocks(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, s6, s7, t0, t1, t2;
    s2 = a0;
    ret = s2 << 2;
    v1 = *(u32*)(v1 + -0x6c40);
    s5 = a3;
    s0 = a2;
    s1 = a1;
    s3 = t2;
    s4 = t0;
    s6 = t1;
    s7 = 0x00500000;
    *(u32*)(s5) = v1;
    if ((signed)v1 >= 0) goto loc_20569C;
    a1 = Compiler_FindCacheSlot(a0);
    *(u32*)(s5) = a1;
    if (a1 != 0) {
        a2 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = 0;
        a0 = a2 + -0x5600;
        ret = *(u32*)(a0);
            do {
                a0 = a0 + 0x10;
                if (ret != a1) {
                v1 = v1 + 1;
                }
                ret = *(u32*)(a0);
            } while (ret != 0);
            v1 = -1;
        }
        ret = a2 + -0x5600;
        v1 = v1 << 4;
        ret = ret + v1;
        *(u32*)(ret + 0xc) = 0;
        goto loc_20569C;
    }
    ret = s2 ^ s1;
    v1 = s2 ^ s0;
    a1 = 0;
    a2 = 0;
    if (ret != 0) a1 = s1;
    if (v1 != 0) a2 = s0;
    t0 = 0;
    if (s2 != s1) {
        t2 = s3;
            t0 = 1;
            t2 = s3;
        }
    a0 = s2;
    a3 = s5;
    t1 = 1;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    s3 = ret;
loc_20569C:
    ret = s7 + -0x6c40;
    if (s1 == s2) {
        ret = *(u32*)(s5);
        *(u32*)(s4) = ret;
    } else {
        v1 = v1 + ret;
        a0 = *(u32*)(v1);
        *(u32*)(s4) = a0;
        if ((signed)a0 >= 0) goto loc_205700;
        a0 = s1;
        ret = Compiler_FindCacheSlot(a0);
        *(u32*)(s4) = ret;
        if (ret != 0) goto loc_205700;
        ret = s1 ^ s0;
        a2 = 0;
        t2 = s3;
        if (ret != 0) a2 = s0;
        a0 = s1;
        a1 = s2;
        a3 = s4;
        t0 = 1;
        t1 = 0;
        s3 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    }
loc_205700:
    if (s0 == s2) {
        ret = *(u32*)(s5);
        *(u32*)(s6) = ret;
        goto loc_205778;
    }
    ret = s7 + -0x6c40;
    if (s0 == s1) {
        ret = *(u32*)(s4);
        *(u32*)(s6) = ret;
        goto loc_205778;
    }
    v1 = v1 + ret;
    a0 = *(u32*)(v1);
    *(u32*)(s6) = a0;
    if ((signed)a0 >= 0) goto loc_205778;
    a0 = s0;
    ret = Compiler_FindCacheSlot(a0);
    *(u32*)(s6) = ret;
    if (ret != 0) goto loc_205778;
    t2 = s3;
    a0 = s0;
    a1 = s2;
    a2 = s1;
    a3 = s6;
    t0 = 1;
    t1 = 0;
    s3 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
loc_205778:
    return s3;

/* Function at 0x002057A8 - 0x002057D0 */
u32 Compiler_InitCacheBuffer(u32 a0)
{
    /* Stack frame: 16 bytes */
    u32 ret, a1, a2, a3, s0;
    s0 = a0;
    ret = Compiler_InitializeCacheSlots();
    return s0;
}

/* Function at 0x002057D0 - 0x00205840 */
u32 Compiler_EmitPrologue(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1;
    s0 = a0;
    s1 = a3;
    a0 = a1;
    a1 = a2;
    a3 = __sp + 4;
    a2 = __sp;
    ret = Compiler_HandleBlockCompilation(a0, a1, a2, a3);
    a0 = *(u32*)(__sp + 4);
    s1 = s1 & 0xffff;
    v1 = *(u32*)(__sp);
    s0 = s0 << 0x1a;
    a0 = a0 << 0x15;
    s0 = s0 | s1;
    v1 = v1 << 0x10;
    a1 = ret;
    v1 = v1 | a0;
    s0 = s0 | v1;
    *(u32*)(a1) = s0;
    return a1 + 4;
}

/* Function at 0x00205840 - 0x002058B8 */
u32 Compiler_EmitEpilogue(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, t0, t1, t2;
    t2 = t0;
    s0 = a0;
    t0 = __sp + 4;
    t1 = __sp + 8;
    a0 = a1;
    a1 = a2;
    a2 = a3;
    a3 = __sp;
    ret = Compiler_ProcessMultipleBlocks(a0, a1, a2, a3);
    a1 = *(u32*)(__sp + 4);
    t2 = ret;
    a0 = *(u32*)(__sp + 8);
    ret = -0x41;
    v1 = *(u32*)(__sp);
    s0 = s0 & ret;
    a1 = a1 << 0x15;
    a0 = a0 << 0x10;
    v1 = v1 << 0xb;
    a0 = a0 | a1;
    s0 = s0 | v1;
    s0 = s0 | a0;
    ret = t2 + 4;
    *(u32*)(t2) = s0;
    return ret;
}

/* Function at 0x002058B8 - 0x00205970 */
u32 Compiler_EmitRegisterLoad(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, t0, t1, t2;
    t2 = a3;
    s2 = a1;
    s0 = a0;
    s1 = a2;
    a3 = __sp;
    a0 = s2;
    a1 = 0;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a3 = __sp + 4;
    t2 = ret;
    a0 = s1;
    a1 = s2;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a2 = 1;
    a0 = *(u32*)(__sp);
    t2 = ret;
    v1 = *(u32*)(__sp + 4);
    ret = -0x41;
    a0 = a0 << 0x15;
    s0 = s0 & ret;
    v1 = v1 | a0;
    s0 = s0 | v1;
    *(u32*)(t2) = s0;
    a3 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    a1 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    ret = t2 + 4;
    *(u32*)(a1 + -0x5608) = a2;
    *(u32*)(a3 + -0x560c) = a2;
    return ret;
}

/* Function at 0x00205970 - 0x00205AF8 */
u32 Compiler_EmitRegisterStore(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, t0, t1, t2;
    s0 = a0;
    a0 = a2;
    if (a1 != 0) {
        t2 = a3;
        a3 = __sp;
        a1 = 0;
        a2 = 0;
        t0 = 1;
        t1 = 0;
        ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
        a3 = ret;
        if (s0 != 0) {
            ret = *(u32*)(__sp);
            a1 = 0x03800000;
            v1 = 0xAC000008;
            ret = ret | a1;
            a0 = 0x0024A9F8;
        } else {
            ret = *(u32*)(__sp);
            a1 = 0x03800000;
            v1 = 0xAC000004;
            ret = ret | a1;
            a0 = 0x0024A9F4;
        }
        ret = ret | v1;
        *(u32*)(a3) = ret;
        ret = *(u32*)(a0);
        a3 = a3 + 4;
        if (ret == 0) goto loc_205AE0;
        *(u32*)(a0) = 0;
        goto loc_205AE0;
    }
    t2 = a3;
    a3 = __sp;
    a2 = 0;
    t0 = 0;
    t1 = 1;
    a3 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    if (s0 != 0) {
        a1 = 0x00250000 + -0x5608;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = *(u32*)(a1);
        ret = *(u32*)(__sp);
        if (v1 != 0) {
            a0 = 0x03800000;
            v1 = 0xAC000008;
            ret = ret | 0x12;
            goto loc_205A98;
        }
        v1 = 0x8C000008;
    } else {
        a1 = 0x00250000 + -0x560c;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = *(u32*)(a1);
        ret = *(u32*)(__sp);
        if (v1 != 0) {
            a0 = 0x03800000;
            v1 = 0xAC000004;
            ret = ret | 0x10;
            loc_205A98:
            *(u32*)(a3) = ret;
            a3 = a3 + 4;
            *(u32*)(a3) = ret | v1;
            a3 = a3 + 4;
            *(u32*)(a1) = 0;
        } else {
            a0 = 0x03800000;
            v1 = 0x8C000004;
            }
            *(u32*)(a3) = ret | v1;
            a3 = a3 + 4;
        }
loc_205AE0:
    return a3;
}

/* Function at 0x00205AF8 - 0x00205B70 */
u32 Compiler_EmitAddressCalculation(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1;
    s0 = a0;
    s1 = a3 & 0xffff;
    a0 = a1;
    a1 = a2;
    a3 = __sp + 4;
    a2 = __sp;
    ret = Compiler_HandleBlockCompilation(a0, a1, a2, a3);
    a1 = ret;
    ret = -0x41;
    a0 = *(u32*)(__sp);
    s1 = s1 & 0xff;
    v1 = *(u32*)(__sp + 4);
    s0 = s0 & ret;
    s1 = s1 << 6;
    a0 = a0 << 0xb;
    s0 = s0 | s1;
    s0 = s0 | a0;
    v1 = v1 << 0x10;
    s0 = s0 | v1;
    *(u32*)(a1) = s0;
    return a1 + 4;
}

/* Function at 0x00205B70 - 0x00205BE8 */
u32 Compiler_EmitMemoryReference(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, t0, t1, t2;
    t2 = t0;
    s0 = a0;
    t0 = __sp + 4;
    t1 = __sp + 8;
    a0 = a1;
    a1 = a3;
    a3 = __sp;
    ret = Compiler_ProcessMultipleBlocks(a0, a1, a2, a3);
    a1 = *(u32*)(__sp + 4);
    t2 = ret;
    a0 = *(u32*)(__sp + 8);
    ret = -0x41;
    v1 = *(u32*)(__sp);
    s0 = s0 & ret;
    a1 = a1 << 0x15;
    a0 = a0 << 0x10;
    v1 = v1 << 0xb;
    a0 = a0 | a1;
    s0 = s0 | v1;
    s0 = s0 | a0;
    ret = t2 + 4;
    *(u32*)(t2) = s0;
    return ret;
}

/* Function at 0x00205BE8 - 0x00205D78 */
u32 Compiler_EmitArithmetic(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, s6, t0, t1, t2, t3, t4;
    ret = a3 << 0x10;
    s2 = a0;
    t4 = t0;
    t0 = 1;
    s4 = a2;
    s6 = s2 & 3;
    v1 = (signed)s2 >> 3;
    t1 = 2;
    s0 = a1;
    s1 = v1 & 1;
    s3 = 0;
    s5 = (signed)ret >> 0x10;
    a3 = __sp;
    a1 = 0;
    a2 = 0;
    a0 = s4;
    t2 = t4;
    if (s6 != t1) {
            s3 = 1;
        }
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = s0;
    t4 = ret;
    ret = s0 & 0x80;
    t1 = s1 ^ 1;
    t2 = t4;
    t0 = s3;
    a1 = s4;
    a2 = 0;
    a3 = __sp + 4;
    v1 = s0 & 0x7f;
    if (ret != 0) {
        *(u32*)(__sp + 4) = v1;
        goto loc_205CAC;
    }
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    t4 = ret;
loc_205CAC:
    a3 = 0x00500000;
    ret = s5 & 0xffff;
    v1 = *(u32*)(a3 + 0x2710);
    a0 = s2 << 0x1a;
    a0 = a0 | ret;
    t0 = 0x3C000000;
    ret = *(u16*)(v1 + 0x2d2);
    t1 = 5 << 16;
    ret = ret | t0;
    a1 = 0x00202024;
    ret = ret | t1;
    a2 = 0x00A42021;
    *(u32*)(t4) = ret;
    t4 = t4 + 4;
    t2 = 0x00800000;
    t3 = 2;
    *(u32*)(t4) = ret | a1;
    t4 = t4 + 4;
    *(u32*)(t4) = a2;
    t4 = t4 + 4;
    ret = ret | t2;
    a0 = a0 | ret;
    *(u32*)(t4) = a0;
    t4 = t4 + 4;
    if (s6 != t3) {
        if (s4 != 0x1d) {
            *(u32*)(t4) = 0;
            t4 = t4 + 4;
            *(u32*)(t4) = 0;
            t4 = t4 + 4;
            }
        }
    return t4;
}

/* Function at 0x00205D78 - 0x00206198 */
u32 Compiler_EmitLogicalOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, t0, t1, t2;
    s5 = a2;
    ret = 0x1FFFFFFF;
    v1 = 4;
    s0 = t0;
    s2 = a3 & ret;
    s3 = a0;
    s4 = a1;
    if (s5 == v1) {
        ret = 0xE07FF000;
        v1 = 0x1FFE0130;
        ret = s2 + ret;
        s5 = s3 & 3;
        s1 = (unsigned)ret >> 4;
        if (s2 == v1) goto loc_205DF8;
        ret = 0x1F000004;
        if (s2 == 0x1F000000) goto loc_205DF8;
        if (s2 != 0x1F000084) goto loc_205DFC;
        loc_205DF8:
        s1 = 0;
        loc_205DFC:
        a0 = s0;
        ret = Compiler_BuildBlockLinkage(a0);
        s0 = ret;
        ret = Compiler_ClearCacheSlots();
        if ((s1 << 2) != 0) {
            a0 = s4;
            t2 = s0;
            a1 = 0;
            a2 = 0;
            a3 = __sp;
            t0 = 1;
            s1 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
            s1 = s1 + ret;
            s1 = *(u32*)(s1 + -0x5f80);
            t1 = 0;
            ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
            a0 = s5 + 1;
            s0 = ret;
            if (a0 == 0) {
                *(u32*)(s0) = 0x302d;
                s0 = s0 + 4;
            } else {
                ret = a0;
                a1 = a0 & 0xffff;
                if (a0 == ret) {
                    v1 = 6 << 16;
                    ret = a0 | ret;
                    a0 = s0 + 4;
                    *(u32*)(s0) = ret | v1;
                } else {
                    a0 = s0 + 4;
                    *(u32*)(s0) = 0x3C060000;
                    if (a1 != 0) {
                        *(u32*)(a0) = ret | 0x00C60000;
                        a0 = s0 + 8;
                        }
                    }
                s0 = a0;
            }
            a0 = 0x3C000000;
            v1 = v1 | a0;
            ret = 4 << 16;
            a1 = (unsigned)s1 >> 0x10;
            v1 = v1 | ret;
            a1 = a1 | a0;
            a0 = 7 << 16;
            t0 = 0x34000000;
            a2 = s2 & 0xffff;
            *(u32*)(s0) = v1;
            s0 = s0 + 4;
            a1 = a1 | a0;
            a0 = s1 & 0xffff;
            v1 = 0x00840000;
            a2 = a2 | t0;
            ret = 0x00207C18;
            a3 = 0x0FFFFFFF;
            *(u32*)(s0) = a1;
            s0 = s0 + 4;
            a2 = a2 | v1;
            v1 = 0x00E70000;
            a0 = a0 | t0;
            ret = ret & a3;
            *(u32*)(s0) = a2;
            s0 = s0 + 4;
            a0 = a0 | v1;
            v1 = 0x0C000000;
            ret = (unsigned)ret >> 2;
            *(u32*)(s0) = a0;
            ret = ret | v1;
            s0 = s0 + 4;
            *(u32*)(s0) = ret;
            s0 = s0 + 4;
            ret = ret | 0x282d;
            goto loc_206164;
        }
        a0 = s4;
        s1 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        s1 = s1 + ret;
        s1 = *(u32*)(s1 + -0x6780);
        t2 = s0;
        a1 = 0;
        a2 = 0;
        a3 = __sp;
        t0 = 0;
        t1 = 1;
        ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
        t1 = 0x3C000000;
        v1 = (unsigned)s2 >> 0x10;
        s0 = ret;
        v1 = v1 | t1;
        a0 = (unsigned)s1 >> 0x10;
        ret = 4 << 16;
        t0 = 0x34000000;
        v1 = v1 | ret;
        ret = 0x00200000;
        a1 = 6 << 16;
        a0 = a0 | t1;
        a3 = s2 & 0xffff;
        *(u32*)(s0) = v1;
        s0 = s0 + 4;
        a0 = a0 | a1;
        a1 = s1 & 0xffff;
        v1 = 0x00840000;
        a3 = a3 | t0;
        ret = 0x00207C58;
        a2 = 0x0FFFFFFF;
        *(u32*)(s0) = a0;
        s0 = s0 + 4;
        a3 = a3 | v1;
        v1 = 0x00C60000;
        ret = ret & a2;
        a1 = a1 | t0;
        *(u32*)(s0) = a3;
        s0 = s0 + 4;
        a1 = a1 | v1;
        v1 = 0x0C000000;
        ret = (unsigned)ret >> 2;
        *(u32*)(s0) = a1;
        ret = ret | v1;
        a0 = s5 + 1;
        s0 = s0 + 4;
        *(u32*)(s0) = ret;
        s0 = s0 + 4;
        if (a0 == 0) {
            *(u32*)(s0) = 0x282d;
            s0 = s0 + 4;
        } else {
            ret = 5 << 16;
            if (a0 == ret) {
                v1 = 5 << 16;
                ret = a0 | ret;
                a0 = s0 + 4;
                ret = ret | v1;
                *(u32*)(s0) = ret;
            } else {
                v1 = a0 & 0xffff;
                ret = t1 | ret;
                a0 = s0 + 4;
                *(u32*)(s0) = ret;
                if (v1 != 0) {
                    *(u32*)(a0) = ret | 0x00A50000;
                    a0 = s0 + 8;
                    }
                }
            s0 = a0;
        }
        v1 = *(u32*)(__sp);
        *(u32*)(s0) = v1 | 0x0040002D;
    } else {
        s1 = s3 & 8;
        t0 = 0;
        if (s1 == 0) {
            v1 = s3 & 3;
            ret = 2;
                t0 = 1;
                ret = 0x00500000;
            }
        a0 = s4;
        v1 = *(u32*)(ret + 0x2710);
        t2 = s0;
        a1 = 0;
        a2 = 0;
        ret = *(u32*)(v1 + 0x2d0);  /* PSX: ram_base */
        a3 = __sp;
        t1 = ((unsigned)s1 < 1) ? 1 : 0;
        s2 = s2 | ret;
        ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
        s0 = ret;
        ret = s2 << 0x10;
        v1 = (unsigned)s2 >> 0x10;
        ret = ret + v1;
        v1 = s3 << 0x1a;
        a0 = 0x3C000000;
        ret = ret & 0xffff;
        a1 = 2 << 16;
        ret = ret | a1;
        a1 = 2;
        *(u32*)(s0) = ret;
        s0 = s0 + 4;
        a2 = s2 & 0xffff;
        a0 = 0x00400000;
        ret = *(u32*)(__sp);
        v1 = v1 | a2;
        ret = ret | a0;
        *(u32*)(s0) = v1 | ret;
        s0 = s0 + 4;
        if (s5 != a1) goto loc_20616C;
        ret = 4;
        a0 = 0x24000000;
        if (s1 != 0) ret = 0;
        ret = ret | 0x037B0000;
        loc_206164:
        *(u32*)(s0) = ret;
    }
    s0 = s0 + 4;
loc_20616C:
    return s0;
}

/* Function at 0x00206198 - 0x00206388 */
u32 Compiler_EmitComparison(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 128 bytes */
    u32 local_20;
    u32 ret, v1, s0, s1, i, s3, s4, s5, s6, s7, t0, t1, t2;
    s4 = a0;
    s0 = s4 + 1;
    s1 = a3;
    s5 = a1;
    s7 = a2;
    ret = Compiler_FindOrAllocateSlot();
    t2 = s1;
    if ((unsigned)ret < (unsigned)s0) {
        a0 = s1;
        ret = Compiler_BuildBlockLinkage(a0);
        s1 = ret;
        ret = Compiler_ClearCacheSlots();
        t2 = s1;
    }
    a0 = s5;
    a1 = 0;
    a2 = 0;
    a3 = __sp + 0x20;
    t0 = 1;
    t1 = 0;
    i = 0;
    s1 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    if (s4 != 0) {
        s6 = 2;
        s3 = __sp;
        s0 = s7;
        do {
            ret = *(u32*)(s0);
            t0 = 0;
            v1 = ret & 3;
            ret = ret & 1;
            if (v1 != s6) {
                a0 = *(u32*)(s0 + 4);
                    t0 = 1;
                    a0 = *(u32*)(s0 + 4);
                }
            s0 = s0 + 0xc;
            t2 = s1;
            a3 = s3;
            t1 = ret ^ 1;
            a1 = s5;
            a2 = 0;
            i = i + 1;
            ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
            s1 = ret;
            ret = ((unsigned)i < (unsigned)s4) ? 1 : 0;
            s3 = s3 + 4;
        } while (ret != 0);
    }
    ret = 0x00500000;
    a3 = 0x3C000000;
    a1 = *(u32*)(ret + 0x2710);
    a2 = 5 << 16;
    ret = *(u16*)(a1 + 0x2d2);
    v1 = 0x00202024;
    a0 = 0x00A42021;
    i = 0;
    ret = ret | a2;
    *(u32*)(s1) = ret;
    s1 = s1 + 4;
    *(u32*)(s1) = ret | v1;
    s1 = s1 + 4;
    *(u32*)(s1) = a0;
    s1 = s1 + 4;
    if (s4 != 0) {
        a2 = s7;
        t1 = 0x00800000;
        t0 = 2;
        a3 = 0x1d;
        a1 = __sp;
        ret = *(u32*)(a2);
        do {
            v1 = *(u32*)(a1);
            a1 = a1 + 4;
            a0 = *(u16*)(a2 + 8);
            ret = ret << 0x1a;
            v1 = v1 << 0x10;
            ret = ret | a0;
            v1 = v1 | t1;
            ret = ret | v1;
            *(u32*)(s1) = ret;
            s1 = s1 + 4;
            ret = ret & 3;
            a2 = a2 + 0xc;
            if (ret != t0) {
                i = i + 1;
                if (s5 != a3) {
                    *(u32*)(s1) = 0;
                    s1 = s1 + 4;
                    *(u32*)(s1) = 0;
                    s1 = s1 + 4;
                    }
                    i = i + 1;
                }
        } while ((*(u32*)(a2)) != 0);
    }
    return s1;
}

/* Function at 0x00206388 - 0x00206498 */
u32 Compiler_EmitSpecialOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, t0, t1, t2;
    v1 = a0;
    ret = 1;
    s1 = a2;
    s2 = a3;
    t2 = t0;
    t0 = 1;
    a0 = a1;
    a1 = 0;
    a2 = 0;
    a3 = __sp;
    s0 = 0x23;
    if (v1 != ret) {
        ret = 2;
        if (v1 == 0) goto loc_2063EC;
        s0 = 0x25;
        if (v1 == ret) goto loc_2063EC;
        goto loc_2063EC;
    }
    s0 = 0x21;
loc_2063EC:
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = 0x3C000000;
    t2 = ret;
    v1 = *(u32*)(0x00500000 + 0x2710);
    a1 = 5 << 16;
    a2 = s0 << 0x1a;
    ret = *(u16*)(v1 + 0x2d2);
    v1 = s1 & 0xffff;
    t0 = 0x00201024;
    ret = ret | a0;
    a0 = s2 & 0xffff;
    ret = ret | a1;
    a1 = 0xAC000000;
    *(u32*)(t2) = ret;
    t2 = t2 + 4;
    a2 = a2 | v1;
    v1 = 0x00420000;
    ret = *(u32*)(__sp);
    a3 = 0x00A21021;
    a2 = a2 | v1;
    v1 = 0x03820000;
    ret = ret << 0x10;
    a0 = a0 | a1;
    *(u32*)(t2) = ret | t0;
    t2 = t2 + 4;
    *(u32*)(t2) = a3;
    t2 = t2 + 4;
    *(u32*)(t2) = a2;
    t2 = t2 + 4;
    a0 = a0 | v1;
    ret = t2 + 4;
    *(u32*)(t2) = a0;
    return ret;
}

/* Function at 0x00206498 - 0x00206608 */
u32 Compiler_EmitLoadOpcode(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, t0, t1, t2, t3, t4;
    t2 = a3;
    s0 = a0;
    s1 = a2;
    a0 = a1;
    a1 = 0;
    a3 = __sp;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    t2 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = *(u32*)(0x00500000 + 0x2710);
    a1 = 0x3C000000;
    a2 = 5 << 16;
    ret = *(u16*)(a0 + 0x2d2);
    v1 = 0x00201024;
    a0 = 0x00A21021;
    ret = ret | a1;
    a3 = 0;
    ret = ret | a2;
    *(u32*)(t2) = ret;
    t2 = t2 + 4;
    *(u32*)(t2) = ret | v1;
    t2 = t2 + 4;
    *(u32*)(t2) = a0;
    t2 = t2 + 4;
    if (s0 == 0) goto loc_2065A4;
    t4 = 1;
    t3 = 2;
    t1 = 0x00400000;
    a2 = 3 << 16;
    a1 = s1;
    t0 = 1 << 16;
loc_206548:
    v1 = *(u32*)(a1);
    ret = 0x23;
    if (v1 != t4) {
        a0 = *(u16*)(a1 + 8);
        if (v1 == 0) goto loc_206578;
        ret = 0x25;
        if (v1 != t3) {
            a0 = *(u16*)(a1 + 8);
            goto loc_206578;
            }
            ret = 0x21;
        }
    a0 = *(u16*)(a1 + 8);
loc_206578:
    a1 = a1 + 0xc;
    ret = ret << 0x1a;
    v1 = a2 | t1;
    ret = ret | a0;
    a3 = a3 + 1;
    ret = ret | v1;
    a0 = ((unsigned)a3 < (unsigned)s0) ? 1 : 0;
    *(u32*)(t2) = ret;
    t2 = t2 + 4;
    a2 = a2 + t0;
    if (a0 != 0) goto loc_206548;
loc_2065A4:
    a3 = 0;
    if (s0 != 0) {
        a2 = s1 + 4;
        t3 = 0xAC000000;
        t1 = 0x03800000;
        a1 = 3 << 16;
        t0 = 1 << 16;
        do {
            ret = *(u16*)(a2);
            a2 = a2 + 0xc;
            a0 = a1 | t1;
            a1 = a1 + t0;
            ret = ret | t3;
            a3 = a3 + 1;
            ret = ret | a0;
            v1 = ((unsigned)a3 < (unsigned)s0) ? 1 : 0;
            *(u32*)(t2) = ret;
            t2 = t2 + 4;
        } while (v1 != 0);
    }
    return t2;
}

/* Function at 0x00206608 - 0x00206740 */
u32 Compiler_EmitStoreOpcode(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, t0, t1, t2, t3;
    t2 = a3;
    s0 = a0;
    s1 = a2;
    a0 = a1;
    a1 = 0;
    a3 = __sp;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    t2 = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = *(u32*)(0x00500000 + 0x2710);
    a1 = 0x3C000000;
    a2 = 5 << 16;
    ret = *(u16*)(a0 + 0x2d2);
    v1 = 0x00201024;
    a0 = 0x00A21021;
    ret = ret | a1;
    a3 = 0;
    ret = ret | a2;
    *(u32*)(t2) = ret;
    t2 = t2 + 4;
    *(u32*)(t2) = ret | v1;
    t2 = t2 + 4;
    *(u32*)(t2) = a0;
    t2 = t2 + 4;
    if (s0 != 0) {
        t3 = 0x8C000000;
        t1 = 0x03800000;
        a2 = 3 << 16;
        a1 = s1 + 4;
        t0 = 1 << 16;
        do {
            ret = *(u16*)(a1);
            a1 = a1 + 0xc;
            a0 = a2 | t1;
            a2 = a2 + t0;
            ret = ret | t3;
            a3 = a3 + 1;
            ret = ret | a0;
            v1 = ((unsigned)a3 < (unsigned)s0) ? 1 : 0;
            *(u32*)(t2) = ret;
            t2 = t2 + 4;
        } while (v1 != 0);
    }
    a3 = 0;
    if (s0 != 0) {
        a2 = s1 + 8;
        t3 = 0xAC000000;
        t1 = 0x00400000;
        a1 = 3 << 16;
        t0 = 1 << 16;
        do {
            ret = *(u16*)(a2);
            a2 = a2 + 0xc;
            a0 = a1 | t1;
            a1 = a1 + t0;
            ret = ret | t3;
            a3 = a3 + 1;
            ret = ret | a0;
            v1 = ((unsigned)a3 < (unsigned)s0) ? 1 : 0;
            *(u32*)(t2) = ret;
            t2 = t2 + 4;
        } while (v1 != 0);
    }
    return t2;
}

/* Function at 0x00206740 - 0x00206770 */
u32 Compiler_EmitImmediateOp(u32 a0, u32 a1)
{
    u32 ret, v1, a2;
    a2 = 0x0C000000;
    v1 = 0x0FFFFFFF;
    ret = a1;
    a0 = a0 & v1;
    a0 = (unsigned)a0 >> 2;
    a0 = a0 | a2;
    *(u32*)(ret) = a0;
    ret = ret + 4;
    *(u32*)(ret) = 0;
    return ret + 4;
}

/* Function at 0x00206770 - 0x002067B0 */
u32 Compiler_EmitCoprocessorOp(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, a3, s0, s1;
    s1 = a0;
    a0 = a2;
    ret = Compiler_BuildBlockLinkage(a0);
    s0 = ret;
    ret = Compiler_ClearCacheSlots();
    a0 = s1;
    a1 = s0;
    return Compiler_EmitImmediateOp(a0, a1);
}

/* Function at 0x002067B0 - 0x00206CA8 */
u32 Compiler_Emit_LW(u32 a0, u32 a1)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a2, a3, s0, s1, t2, t3;
    s0 = a0;
    a0 = a1;
    ret = Compiler_BuildBlockLinkage(a0);
    s1 = ret;
    ret = Compiler_ClearCacheSlots();
    ret = ret + -1;
    v1 = ((unsigned)ret < 0x3f) ? 1 : 0;
    a0 = 0;
    if (v1 == 0) Compiler_Emit_LW(a0, a1); return;
    ret = ret << 2;
    v1 = *(u32*)(v1 + -0x6bc0);
    goto *v1; /* computed jump */
    a0 = 0x00210000 + -0x7738;
    Compiler_Emit_LW(a0, a1); return;
        a1 = a1 & 0xffff;
        *(u32*)(s1) = ret;
        a0 = s1 + 4;
        if (a1 != 0) {
            *(u32*)(a0) = ret | 0x00A50000;
            a0 = s1 + 8;
        }
        s1 = a0;
    a0 = 0x00210000 + -0x6438;
    goto loc_206C5C;
        a1 = s1 + 4;
        *(u32*)(s1) = ret;
        if (a0 != 0) {
            *(u32*)(a1) = ret | 0x00A50000;
            a1 = s1 + 8;
        }
        s1 = a1;
    a0 = 0x00210000 + -0x7480;
    goto loc_206C5C;
        a1 = s1 + 4;
        *(u32*)(s1) = ret;
        if (a0 != 0) {
            *(u32*)(a1) = ret | 0x00A50000;
            a1 = s1 + 8;
        }
        s1 = a1;
    a0 = 0x00210000 + -0x7478;
    goto loc_206C5C;
        a1 = a1 & 0xffff;
        *(u32*)(s1) = ret;
        a0 = s1 + 4;
        if (a1 != 0) {
            *(u32*)(a0) = ret | 0x00A50000;
            a0 = s1 + 8;
        }
        s1 = a0;
    a0 = 0x00210000 + -0x6518;
    goto loc_206C5C;
    if (a3 != 0) {
        ret = ret | 0x03860000;
    } else {
        ret = 0x302d;
    }
    *(u32*)(s1) = ret;
    s1 = s1 + 4;
    ret = 1;
    a3 = 0x264;
    if (t2 == ret) goto loc_206BF0;
    a3 = 0x244;
    if (t2 == 0) goto loc_206BF0;
    ret = 2;
    a3 = 0x284;
    if (t2 == ret) goto loc_206BF0;
    a3 = 0;
loc_206BF0:
    if (a3 != 0) {
        ret = ret | 0x03870000;
    } else {
        ret = 0x382d;
    }
    *(u32*)(s1) = ret;
    s1 = s1 + 4;
    if (t3 == 0) {
        if (a2 == 0) {
            a0 = 0x00210000 + -0x6390;
            goto loc_206C5C;
        }
        a0 = ret + -0x6380;
    } else {
        if (a2 == 0) {
            a0 = 0x00210000 + -0x6370;
            goto loc_206C5C;
        }
        a0 = ret + -0x6360;
        goto loc_206C5C;
    }
loc_206C5C:
    a1 = 0x0C000000;
    ret = a0 & ret;
    a0 = 0;
    ret = (unsigned)ret >> 2;
    v1 = 0x278401B0;
    *(u32*)(s1) = ret | a1;
    s1 = s1 + 4;
    *(u32*)(s1) = v1;
    a1 = s1 + 4;
    return Compiler_Emit_LUI(a0, a1);
}

/* Function at 0x00206CA8 - 0x00206CE0 */
u32 Compiler_Emit_SW(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, a2, a3, s0;
    s0 = a1;
    if (a0 == 0) {
        a0 = s0;
        ret = Compiler_BuildBlockLinkage(a0);
        s0 = ret;
        ret = Compiler_ClearCacheSlots();
    }
    return s0;
}

/* Function at 0x00206CE0 - 0x00206DB8 */
u32 Compiler_Emit_LH(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a3, s0, t0, t1, t2;
    t2 = a2;
    s0 = a0;
    a2 = 0;
    a3 = __sp;
    a0 = a1;
    a1 = 0;
    t0 = 0;
    t1 = 1;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    t2 = ret;
    ret = (signed)ret >> 0x10;
    a0 = *(u32*)(__sp);
    if (s0 == 0) {
        ret = ret | 0x2d;
        *(u32*)(t2) = ret;
        t2 = t2 + 4;
    } else {
        if (s0 == ret) {
            ret = s0 & 0xffff;
            v1 = 0x24000000;
            a0 = a0 << 0x10;
            ret = ret | a0;
            a1 = t2 + 4;
            *(u32*)(t2) = ret;
        } else {
            ret = (unsigned)s0 >> 0x10;
            a3 = a0 << 0x10;
            ret = ret | a3;
            a2 = s0 & 0xffff;
            a1 = t2 + 4;
            *(u32*)(t2) = ret;
            if (a2 != 0) {
                v1 = a0 << 0x15;
                ret = a2 | ret;
                v1 = a3 | v1;
                *(u32*)(a1) = ret | v1;
                a1 = t2 + 8;
                }
            }
        t2 = a1;
    }
    return t2;
}

/* Function at 0x00206DB8 - 0x00206DD8 */
u32 Compiler_CalculateBufferSize(u32 a0, u32 a1)
{
    u32 ret, v1;
    ret = (signed)ret >> 2;
    v1 = (signed)v1 >> 0x10;
    return ((unsigned)ret < 1) ? 1 : 0;
}

/* Function at 0x00206DD8 - 0x00206E98 */
u32 Compiler_Emit_SH(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a3, s0, s1, s2;
    s0 = a2;
    s1 = a0;
    s2 = a1;
    ret = Compiler_ClearCacheSlots();
    ret = 0x0FFFFFFF;
    v1 = 0x08000000;
    ret = s1 & ret;
    a1 = 0xFFFC0001;
    ret = (unsigned)ret >> 2;
    a0 = s1 - s0;
    a2 = ret | v1;
    if (s2 != 0) {
        *(u32*)(s2) = s0;
    }
    v1 = 0;
    if (s1 != 0) {
        v1 = a0 + -4;
    }
    if (v1 != 0) {
        *(u32*)(s0) = a2;
        if ((signed)v1 < (signed)a1) goto loc_206E74;
        ret = 0x0003FFFF;
        *(u32*)(s0) = a2;
        if ((signed)ret < (signed)v1) goto loc_206E74;
        ret = (signed)v1 >> 2;
        *(u32*)(s0) = ret | 0x10000000;
    } else {
        *(u32*)(s0) = a2;
    }
loc_206E74:
    s0 = s0 + 4;
    ret = s0 + 4;
    *(u32*)(s0) = 0;
    return ret;
}

/* Function at 0x00206E98 - 0x00206F80 */
u32 Compiler_Emit_LB(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, s3;
    s0 = a2;
    s1 = a3;
    s2 = a0;
    s3 = a1;
    ret = Compiler_ClearCacheSlots();
    s0 = -s0;
    v1 = 0x24000000;
    s0 = s0 & 0xffff;
    ret = 0x0FFFFFFF;
    s0 = s0 | v1;
    ret = s2 & ret;
    v1 = 0x037B0000;
    ret = (unsigned)ret >> 2;
    s0 = s0 | v1;
    a1 = ret | 0x08000000;
    ret = s2 - s1;
    a0 = 0xFFFC0001;
    if (s3 != 0) {
        *(u32*)(s3) = s1;
    }
    v1 = 0;
    if (s2 != 0) {
        v1 = ret + -4;
    }
    if (v1 != 0) {
        *(u32*)(s1) = a1;
        if ((signed)v1 < (signed)a0) goto loc_206F54;
        ret = 0x0003FFFF;
        *(u32*)(s1) = a1;
        if ((signed)ret < (signed)v1) goto loc_206F54;
        ret = (signed)v1 >> 2;
        *(u32*)(s1) = ret | 0x10000000;
    } else {
        *(u32*)(s1) = a1;
    }
loc_206F54:
    s1 = s1 + 4;
    *(u32*)(s1) = s0;
    return s1 + 4;
}

/* Function at 0x00206F80 - 0x00206FD0 */
u32 Compiler_EncodeLoadStoreAddressing(u32 a0, u32 a1, u32 a2, u32 a3)
{
    u32 ret, v1;
    ret = a1 - a3;
    *(u32*)(a0) = a3;
    v1 = 0;
    if (a1 != 0) {
        v1 = ret + -4;
    }
    a0 = 7;
    ret = 6;
    v1 = (signed)v1 >> 2;
    if (a2 == 0) ret = a0;
    v1 = v1 & 0xffff;
    ret = ret << 0x1a;
    a1 = 0x03600000;
    *(u32*)(a3) = ret | a1;
    a3 = a3 + 4;
    *(u32*)(a3) = 0;
    return a3 + 4;
}

/* Function at 0x00206FD0 - 0x00207018 */
u32 Compiler_EncodeRegisterOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    u32 ret, v1, t0;
    *(u32*)(a0) = a3;
    a0 = 0;
    ret = a3 + 4;
    v1 = a1 - a3;
    t0 = a2;
    if (a1 != 0) {
        a0 = v1 + -4;
    }
    a1 = 7;
    v1 = 6;
    a0 = (signed)a0 >> 2;
    if (t0 == 0) v1 = a1;
    a0 = a0 & 0xffff;
    v1 = v1 << 0x1a;
    a2 = 0x03600000;
    *(u32*)(a3) = v1 | a2;
    return ret;
}

/* Function at 0x00207018 - 0x00207218 */
u32 Compiler_Emit_SB(u32 a0, u32 a1)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, a2, a3, s0, s1, s2;
    s1 = a0;
    a0 = a1;
    s2 = 0x00210000;
    ret = Compiler_BuildBlockLinkage(a0);
    s0 = ret;
    ret = Compiler_ClearCacheSlots();
    a0 = s0;
    a1 = s2 + -0x7da8;
    ret = Compiler_CalculateBufferSize(a0, a1);
    ret = s1 << 0x10;
    if (ret != 0) {
        ret = (signed)ret >> 0x10;
        if (s1 == 0) {
            *(u32*)(s0) = 0x102d;
            s0 = s0 + 4;
        } else {
            if (s1 == 0x3C000000) {
                ret = ret | 0x24000000;
                a0 = 2 << 16;
                ret = ret | a0;
                a1 = s0 + 4;
                *(u32*)(s0) = ret;
            } else {
                v1 = (unsigned)s1 >> 0x10;
                a0 = 2 << 16;
                v1 = v1 | a0;
                a0 = s1 & 0xffff;
                *(u32*)(s0) = v1;
                a1 = s0 + 4;
                if (a0 != 0) {
                    *(u32*)(a1) = ret | 0x00420000;
                    a1 = s0 + 8;
                    }
                }
            s0 = a1;
        }
        a3 = s0;
        a0 = __sp;
        a1 = s2 + -0x7da8;
        a2 = 1;
        s0 = Compiler_EncodeRegisterOp(a0, a1, a2, a3);
        *(u32*)(s0) = 0xAF820000;
        a1 = s0 + 4;
        a0 = 0x002082C8;
        ret = Compiler_EmitImmediateOp(a0, a1);
        s0 = ret;
        goto loc_2071FC;
    }
    ret = (signed)ret >> 0x10;
    if (s1 == ret) {
        a3 = s0;
        a1 = s0 + 0x10;
        a0 = __sp;
        a2 = 1;
        ret = Compiler_EncodeRegisterOp(a0, a1, a2, a3);
        s0 = ret;
        if (s1 == 0) {
            ret = 0x102d;
        } else {
            ret = ret | 0x24000000;
            a0 = 2 << 16;
            ret = ret | a0;
            } else {
            ret = (unsigned)s1 >> 0x10;
            v1 = 2 << 16;
            ret = ret | v1;
            a2 = 1;
            *(u32*)(s0) = ret;
            s0 = s0 + 4;
            a0 = __sp;
            a3 = s0;
            a1 = s0 + 0x10;
            ret = Compiler_EncodeRegisterOp(a0, a1, a2, a3);
            a0 = 0x34000000;
            s0 = ret;
            ret = ret | 0x00420000;
            }
        }
    *(u32*)(s0) = ret;
    s0 = s0 + 4;
    a1 = 0x0FFFFFFF;
    ret = ret & a1;
    v1 = 0x0C000000;
    a0 = s2 + -0x7da8;
    ret = ret | v1;
    v1 = 0xAF820000;
    a0 = a0 & a1;
    *(u32*)(s0) = ret;
    a0 = (unsigned)a0 >> 2;
    s0 = s0 + 4;
    ret = 0x08000000;
    *(u32*)(s0) = v1;
    a0 = a0 | ret;
    s0 = s0 + 4;
    *(u32*)(s0) = a0;
    s0 = s0 + 4;
    *(u32*)(s0) = v1;
    s0 = s0 + 4;
loc_2071FC:
    return s0;
}

/* Function at 0x00207218 - 0x00207378 */
u32 Compiler_Emit_ADD(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, t0, t1, t2;
    s0 = a2;
    s1 = a0;
    s2 = t0;
    a0 = a1;
    a2 = t2;
    if (a3 != 0) {
        v1 = 1;
        ret = a2;
        *(u32*)(t1) = v1;
        goto loc_20735C;
    }
    *(u32*)(t1) = 0;
    t1 = 0;
    a3 = __sp;
    a1 = 0;
    a2 = 0;
    t0 = 1;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = s0;
    a2 = 0;
    a1 = 0;
    t2 = ret;
    a3 = __sp + 4;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = s1 + -0x201;
    a2 = ret;
    if ((a0 << 2) == 0) goto loc_207340;
    v1 = *(u32*)(v1 + -0x6ac0);
    goto *v1; /* computed jump */
    v1 = *(u32*)(__sp);
    ret = *(u32*)(__sp + 4);
    v1 = v1 << 0x15;
    ret = ret | 0x1026;
    goto loc_207338;
loc_207338:
    *(u32*)(a2) = ret;
    a2 = a2 + 4;
loc_207340:
    ret = a2;
    if (s2 != 0) goto loc_20735C;
    *(u32*)(a2) = 0xAF82000C;
    a2 = a2 + 4;
    ret = a2;
loc_20735C:
    return ret;
}

/* Function at 0x00207378 - 0x00207440 */
u32 Compiler_Emit_ADDI(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, s3, t0;
    s1 = a0;
    a0 = t0;
    s2 = a1;
    s3 = a2;
    s0 = a3;
    ret = Compiler_BuildBlockLinkage(a0);
    a0 = 0x201;
    a2 = ret;
    ret = 0x8F82000C;
    v1 = 0x203;
    if (s0 == 0) {
        *(u32*)(a2) = ret;
        a2 = a2 + 4;
    }
    *(u32*)(s3) = a2;
    a1 = 0;
    if (s2 != 0) {
        ret = s2 - a2;
        a1 = ret + -4;
    }
    ret = (signed)a1 >> 2;
    if (s1 != a0) {
        if (s1 != 0x10000000) {
            ret = (signed)a1 >> 2;
            } else {
                v1 = 0x14000000;
            }
        }
    ret = ret & 0xffff;
    a0 = 0x00400000;
    ret = ret | a0;
    *(u32*)(a2) = ret;
    a2 = a2 + 4;
    ret = a2 + 4;
    *(u32*)(a2) = 0;
    return ret;
}

/* Function at 0x00207440 - 0x00207608 */
u32 Compiler_Emit_SUB(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, t0, t1, t2;
    s4 = a0;
    a0 = t2;
    s1 = a2;
    s2 = t1;
    s3 = t0;
    s5 = a3;
    s0 = a1;
    ret = Compiler_BuildBlockLinkage(a0);
    a0 = s0;
    a3 = __sp;
    t2 = ret;
    a1 = 0;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = s1;
    a2 = 0;
    t0 = 1;
    a1 = 0;
    t2 = ret;
    a3 = __sp + 4;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    t0 = 0;
    a2 = ret;
    *(u32*)(s2) = a2;
    if (s3 != 0) {
        ret = s3 - a2;
        t0 = ret + -4;
    }
    a0 = s4 + -0x201;
    t0 = (signed)t0 >> 2;
    if ((unsigned)a0 >= 6) goto loc_2075C0;
    ret = a0 << 2;
    v1 = *(u32*)(v1 + -0x6aa0);
    goto *v1; /* computed jump */
    a0 = *(u32*)(__sp);
    v1 = t0 & 0xffff;
    ret = *(u32*)(__sp + 4);
    a1 = 0x10000000;
    a0 = a0 << 0x15;
    v1 = v1 | a1;
    ret = ret | a0;
    goto loc_2075B4;
loc_2075B4:
    v1 = v1 | ret;
    *(u32*)(a2) = v1;
    a2 = a2 + 4;
loc_2075C0:
    v1 = -s5;
    ret = 0x24000000;
    v1 = v1 & 0xffff;
    a0 = 0x037B0000;
    v1 = v1 | a0;
    ret = a2 + 4;
    *(u32*)(a2) = v1;
    return ret;
}

/* Function at 0x00207608 - 0x00207690 */
u32 Compiler_Emit_SUBI(u32 a0, u32 a1)
{
    u32 ret, v1, a2, a3, t0, t1;
    a3 = *(u32*)(a0);
    t0 = a1 - a0;
    a2 = t0 + -4;
    t1 = (unsigned)a3 >> 0x1a;
    v1 = (signed)a2 >> 2;
    ret = t1 + -2;
    v1 = v1 & 0xffff;
    if ((unsigned)ret < 2) {
        ret = 7 << 16;
        if (a2 == ret) {
            *(u32*)(a0) = 0;
            return ret;
        }
        v1 = v1 + t0;
        ret = t1 << 0x1a;
        if (ret == 0) {
            ret = (signed)a2 >> 2;
            v1 = 0x10000000;
            ret = ret & 0xffff;
            goto loc_207680;
        }
        v1 = (unsigned)a1 >> 2;
    } else {
        ret = a3 & ret;
    }
loc_207680:
    ret = ret | v1;
    *(u32*)(a0) = ret;
    return ret;
}

/* Function at 0x00207690 - 0x002076B8 */
u32 Compiler_Emit_LUI(u32 a0, u32 a1)
{
    u32 ret, v1;
    ret = a1;
    v1 = 0x3C011FFF;
    a0 = 0x3421FFFF;
    *(u32*)(ret) = v1;
    *(u32*)(ret + 4) = a0;
    return ret + 8;
}

/* Function at 0x002076B8 - 0x002076D0 */
u32 Compiler_Emit_JAL(void)
{
    /* Stack frame: 16 bytes */
    u32 a0, a1, a2, a3;
    return Compiler_BuildBlockLinkage(a0);
}

/* Function at 0x002076D0 - 0x00207770 */
u32 Compiler_Emit_ImmediateArith(u32 a0, u32 a1)
{
    u32 ret, v1, a2;
    a2 = a0;
    ret = a2 << 0x10;
    if (a2 == 0) {
        *(u32*)(a1) = 0x102d;
        a1 = a1 + 4;
        goto loc_20775C;
    }
    ret = (signed)ret >> 0x10;
    v1 = (unsigned)a2 >> 0x10;
    if (a2 == ret) {
        ret = a2 & 0xffff;
        a2 = a1 + 4;
        v1 = 0x24000000;
        a0 = 2 << 16;
        ret = ret | a0;
        *(u32*)(a1) = ret;
        goto loc_207758;
    }
    ret = 0x3C000000;
    a0 = 2 << 16;
    v1 = v1 | a0;
    a0 = a2 & 0xffff;
    *(u32*)(a1) = v1;
    a2 = a1 + 4;
    if (a0 == 0) goto loc_207758;
    *(u32*)(a2) = ret | 0x00420000;
    a2 = a1 + 8;
loc_207758:
    a1 = a2;
loc_20775C:
    v1 = 0xAF820000;
    ret = a1 + 4;
    *(u32*)(a1) = v1;
    return ret;
}

/* Function at 0x00207770 - 0x002077C8 */
u32 Compiler_Emit_IndirectJump(u32 a0, u32 a1)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a2, a3, t0, t1, t2;
    t2 = a1;
    a2 = 0;
    a3 = __sp;
    a1 = 0;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    v1 = 0xAC000000;
    a0 = *(u32*)(__sp);
    a1 = 0x03800000;
    t2 = ret;
    a0 = a0 << 0x10;
    ret = t2 + 4;
    a0 = a0 | a1;
    a0 = a0 | v1;
    *(u32*)(t2) = a0;
    return ret;
}

/* Function at 0x002077C8 - 0x002077F8 */
u32 Compiler_EncodeNegateOp(u32 a0, u32 a1)
{
    u32 ret;
    ret = -a0;
    if (a0 != 0) {
        ret = ret | 0x24000000;
        a0 = 0x037B0000;
        *(u32*)(a1) = ret | a0;
        a1 = a1 + 4;
    }
    return a1;
}

/* Function at 0x002077F8 - 0x00207888 */
u32 Compiler_Emit_BiImmediate(u32 a0, u32 a1, u32 a2)
{
    u32 ret, v1, a3;
    ret = a1 << 0x10;
    a0 = a0 + 3;
    v1 = (signed)ret >> 0x10;
    ret = a0 << 0xb;
    a3 = a2 + 4;
    if (a1 == 0) {
        ret = ret | 0x2d;
        *(u32*)(a2) = ret;
        goto loc_207880;
    }
    ret = (unsigned)a1 >> 0x10;
    if (a1 == v1) {
        ret = ret | 0x24000000;
        a0 = a0 << 0x10;
        ret = ret | a0;
    } else {
        a1 = a1 & 0xffff;
        v1 = 0x3C000000;
        a3 = a0 << 0x10;
        *(u32*)(a2) = ret | a3;
        a2 = a2 + 4;
        if (a1 != 0) {
            v1 = a3 | v1;
            ret = ret | v1;
            }
            *(u32*)(a2) = ret;
            a2 = a2 + 4;
        }
    a3 = a2;
loc_207880:
    return a3;
}

/* Function at 0x00207888 - 0x00207930 */
u32 Compiler_Emit_LoadIndexed(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a3, s0, s1, s2;
    ret = a0 + 3;
    s2 = a1 << 2;
    a3 = 0x00500000;
    a3 = a3 + s2;
    a3 = *(u32*)(a3 + -0x6c40);
    s1 = 2;
    s0 = a2;
    if (a0 != 0) s1 = ret;
    a0 = a1;
    if ((signed)a3 < 0) {
        ret = Compiler_FindCacheSlot(a0);
        a0 = 0x8C000000;
        v1 = s2 + 0x10;
        a3 = ret;
        a1 = 0x03800000;
        v1 = v1 & 0xffff;
        ret = s1 << 0x10;
        v1 = v1 | a0;
        ret = ret | a1;
            v1 = s1 << 0xb;
            a0 = a3 << 0x15;
            v1 = v1 | 0x2d;
            ret = s0 + 4;
            v1 = v1 | a0;
            *(u32*)(s0) = v1;
        } else {
            *(u32*)(s0) = v1;
            ret = s0 + 4;
        }
    return ret;
}

/* Function at 0x00207930 - 0x00207980 */
u32 Compiler_Emit_SimpleArithmetic(u32 a0, u32 a1)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a2, a3, t0, t1, t2;
    t2 = a1;
    a2 = 0;
    a3 = __sp;
    a1 = 0;
    t0 = 0;
    t1 = 1;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    v1 = *(u32*)(__sp);
    t2 = ret;
    a0 = 0x0040002D;
    v1 = v1 << 0xb;
    ret = t2 + 4;
    *(u32*)(t2) = v1 | a0;
    return ret;
}

/* Function at 0x00207980 - 0x002079C0 */
u32 Compiler_Emit_BranchLinkage(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, t0;
    v1 = a0 + 3;
    if (a0 != 0) 2 = v1;
    a0 = 0x23;
    v1 = a1;
    a1 = ret | 0x80;
    a2 = a2 << 0x10;
    t0 = a3;
    a3 = (signed)a2 >> 0x10;
    a2 = v1;
    return Compiler_EmitArithmetic(a0, a1, a2, a3);
}

/* Function at 0x002079C0 - 0x002079F0 */
u32 Compiler_Emit_CoprocessorMove(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 16 bytes */
    u32 ret, a3, t0;
    ret = a0;
    a3 = a1 << 0x10;
    t0 = a2;
    a2 = ret;
    a0 = 0x2b;
    a1 = 0x87;
    a3 = (signed)a3 >> 0x10;
    return Compiler_EmitArithmetic(a0, a1, a2, a3);
}

/* Function at 0x002079F0 - 0x00207A58 */
u32 Compiler_Emit_MemoryLoadALU(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a3, s0, t0, t1, t2;
    t2 = a2;
    s0 = a1;
    a2 = 0;
    a3 = __sp;
    a1 = 0;
    t0 = 0;
    t1 = 1;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    a0 = 0x03800000;
    v1 = *(u32*)(__sp);
    t2 = ret;
    s0 = s0 & 0xffff;
    ret = 0x8C000000;
    v1 = v1 << 0x10;
    s0 = s0 | ret;
    v1 = v1 | a0;
    s0 = s0 | v1;
    ret = t2 + 4;
    *(u32*)(t2) = s0;
    return ret;
}

/* Function at 0x00207A58 - 0x00207B48 */
u32 Compiler_Emit_MemoryStoreALU(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, t0, t1, t2;
    t2 = a3;
    s0 = a0;
    s1 = a2;
    a0 = a1;
    a1 = 0;
    a3 = __sp;
    a2 = 0;
    t0 = 1;
    t1 = 0;
    ret = Compiler_CompileInstructionBlock(a0, a1, a2, a3);
    t2 = ret;
    ret = 0xAC000000;
    v1 = s1 & 0xffff;
    a1 = 2 << 16;
    v1 = v1 | ret;
    ret = 0x03820000;
    a0 = 1;
    a1 = 0x00021403;
    v1 = v1 | ret;
    if (s0 != a0) {
        ret = *(u32*)(__sp);
        if (s0 != 0) {
            if (s0 != 2) {
                ret = t2;
                goto loc_207B38;
                }
                v1 = s1 & 0xffff;
                a0 = 0xAC000000;
                goto loc_207B14;
                }
                *(u32*)(t2) = ret | 0x1400;
                t2 = t2 + 4;
                *(u32*)(t2) = a1;
                t2 = t2 + 4;
            } else {
                ret = *(u32*)(__sp);
                v1 = s1 & 0xffff;
                a0 = 0xA4000000;
                loc_207B14:
                a1 = 0x03800000;
                ret = ret << 0x10;
                v1 = v1 | a0;
                ret = ret | a1;
                v1 = v1 | ret;
            }
    *(u32*)(t2) = v1;
    t2 = t2 + 4;
    ret = t2;
loc_207B38:
    return ret;
}

/* Function at 0x00207B48 - 0x00207B80 */
u32 Compiler_Emit_GTEOperation(u32 a0, u32 a1, u32 a2)
{
    u32 ret, v1;
    v1 = a0 + 3;
    if (a0 != 0) 7 = v1;
    v1 = 0x8C000000;
    a1 = a1 & 0xffff;
    ret = ret << 0x10;
    a0 = 0x03800000;
    a1 = a1 | v1;
    ret = ret | a0;
    a1 = a1 | ret;
    ret = a2 + 4;
    *(u32*)(a2) = a1;
    return ret;
}

/* Function at 0x00207B80 - 0x00207BC0 */
u32 Compiler_Emit_MultiplyDivide(u32 a0)
{
    u32 ret, v1, a1, a2, a3;
    a1 = 2 << 16;
    v1 = a0 + 4;
    ret = 0x70401004;
    a1 = 0x00021000;
    a2 = 0x24420001;
    a3 = 0xAF82022C;
    *(u32*)(a0) = ret;
    ret = v1 + 0xc;
    *(u32*)(v1) = a1;
    *(u32*)(v1 + 4) = a2;
    *(u32*)(v1 + 8) = a3;
    return ret;
}

/* Function at 0x00207BC0 - 0x00207D20 */
u32 Compiler_Emit_ShiftOp(u32 a0)
{
    u32 ret, v1, a1, a2, a3, t0, t1;
    v1 = a0 + 4;
    ret = 0x8F8401E4;
    a1 = 0x8F8501E8;
    a2 = 0x8F8601EC;
    a3 = 0xAF8401E0;
    t0 = 0xAF8501E4;
    t1 = 0xAF8601E8;
    *(u32*)(a0) = ret;
    ret = v1 + 0x14;
    *(u32*)(v1) = a1;
    *(u32*)(v1 + 4) = a2;
    *(u32*)(v1 + 8) = a3;
    *(u32*)(v1 + 0xc) = t0;
    *(u32*)(v1 + 0x10) = t1;
    return ret;
}

/* Function at 0x00207D20 - 0x00207DE0 */
u32 Compiler_Emit_RotateOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 128 bytes */
    u32 ret, v1, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, psx;
    *(u64*)(__sp + 8) = t0;
    *(u64*)(__sp + 16) = t1;
    *(u64*)(__sp + 24) = t2;
    *(u64*)(__sp + 32) = t3;
    *(u64*)(__sp + 40) = t4;
    *(u64*)(__sp + 48) = t5;
    *(u64*)(__sp + 56) = t6;
    *(u64*)(__sp + 64) = t7;
    *(u64*)(__sp + 72) = t8;
    *(u64*)(__sp + 80) = t9;
    *(u64*)(__sp + 88) = a0;
    a0 = a0 + a3;
    a0 = a0 & __at;
    v1 = v1 << 2;
    ret = *(u32*)(ret);
    ((PSX_State*)psx)->cop2_insn_count = __k1;
    __asm("mmi2 gp, gp, gp");
    __gp = 0x0050A670;
    ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
    __asm("mmi3 gp, gp, gp");
    __k1 = ((PSX_State*)psx)->cop2_insn_count;
    __at = 0x1FFFFFFF;
    t0 = *(u64*)(__sp + 8);
    t1 = *(u64*)(__sp + 16);
    t2 = *(u64*)(__sp + 24);
    t3 = *(u64*)(__sp + 32);
    t4 = *(u64*)(__sp + 40);
    t5 = *(u64*)(__sp + 48);
    t6 = *(u64*)(__sp + 56);
    t7 = *(u64*)(__sp + 64);
    t8 = *(u64*)(__sp + 72);
    t9 = *(u64*)(__sp + 80);
    a0 = *(u64*)(__sp + 88);
    return ret;
}

/* Function at 0x00207DE0 - 0x00208180 */
u32 Compiler_Emit_SystemCall(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, t0, t1, t2, t3, t4, t5, t6, t7;
    s1 = a3;
    v1 = s1 + v1;
    ret = 0x1FFFFFFF;
    s4 = a2;
    s0 = s4;
    if ((unsigned)ret < (unsigned)v1) {
        a1 = s4;
        a0 = 0x004F9578;
        a2 = s1;
        ret = UI_DMASetup(a0, a1, a2, a3);
        BREAK(); /* breakpoint */
    }
    ret = *(u32*)(0x00500000 + 0x6c00);
    s3 = *(u32*)(s4);
    if ((unsigned)s4 >= (unsigned)ret) goto loc_207E7C;
    ret = *(u32*)(0x00500000 + 0x6c04);
    s3 = *(u32*)(s4);
    if ((unsigned)s4 < (unsigned)ret) goto loc_207E7C;
    a1 = s4;
    a0 = 0x004F95B0;
    a2 = s1;
    ret = UI_DMASetup(a0, a1, a2, a3);
    BREAK(); /* breakpoint */
    s3 = *(u32*)(s4);
loc_207E7C:
    s1 = s1 + 0xC0000000;
    ret = 0x1FFE0130;
    s2 = (unsigned)s3 >> 0x1a;
    if (s1 != ret) {
        ret = PSX_EXP2_END;  /* 0x1F801F5A */
        if (s1 == 0x1F000000) {
            a1 = s4;
            a0 = 0x004F9578;
            a2 = ret;
            ret = UI_DMASetup(a0, a1, a2, a3);
            BREAK(); /* breakpoint */
            goto loc_208130;
        }
        ret = ret | 0x84;
        if (s1 != 0x1F000000) {
            ret = 0x1F000004;
                a1 = s1;
                a0 = 0x004F95E8;
                ret = UI_DMASetup(a0, a1, a2, a3);
                ret = s2 & 8;
                *(u32*)(s4) = 0;
                s0 = s4 + 4;
                } else {
                v1 = v1 | 0x2400FFFF;
                s0 = s4 + 4;
                *(u32*)(s4) = v1;
                goto loc_208130;
            }
            ret = s1 + ret;
            a3 = 0x0FFF0000;
            if ((unsigned)ret >= 0x2000) {
                a2 = s1;
                a0 = 0x004F9608;
                a1 = s4;
                ret = UI_DMASetup(a0, a1, a2, a3);
                BREAK(); /* breakpoint */
                goto loc_208130;
            }
            t6 = 1;
            t5 = 0x382d;
            t4 = 0x24000000;
            a2 = 7 << 16;
            t3 = 0x3C000000;
            t2 = 0x34000000;
            t1 = 0x00E70000;
            t0 = 0x0C000000;
            a3 = 0x0FFFFFFF;
            s1 = 0x00200000;
            t7 = 0x00200000;
            goto loc_207FA0;
            loc_207F90:
            v1 = 4;
            ret = ret & 0x1f;
            if (ret != v1) goto loc_208130;
            loc_207FA0:
            ret = s2 & 8;
            a0 = s2 & 3;
            if (ret != 0) {
                v1 = s1 + 0x7c98;
                if (a0 == 0) goto loc_207FC4;
                v1 = t7 + 0x7cb0;
                if (a0 == t6) goto loc_207FC4;
                v1 = 0x00200000 + 0x7cc8;
                loc_207FC4:
                ret = s3 << 0x10;
                a0 = (signed)ret >> 0x10;
                ret = a0;
                if (a0 == 0) {
                    *(u32*)(s0) = t5;
                    s0 = s0 + 4;
                } else {
                    ret = (unsigned)a0 >> 0x10;
                    if (a0 == ret) {
                        ret = a0 & 0xffff;
                        a0 = s0 + 4;
                        ret = ret | a2;
                        *(u32*)(s0) = ret;
                    } else {
                        a1 = a0 & 0xffff;
                        ret = ret | t3;
                        a0 = s0 + 4;
                        ret = ret | a2;
                        *(u32*)(s0) = ret;
                        if (a1 != 0) {
                            *(u32*)(a0) = ret | t1;
                            a0 = s0 + 8;
                            }
                        }
                    s0 = a0;
                }
                v1 = v1 & a3;
                ret = (unsigned)s3 >> 0x10;
                v1 = (unsigned)v1 >> 2;
                ret = ret & 0x1f;
                v1 = v1 | t0;
                ret = ret << 0x15;
                *(u32*)(s0) = v1;
                s0 = s0 + 4;
                *(u32*)(s0) = ret | 0x282d;
            } else {
                v1 = 0x00200000 + 0x7ce0;
                if (a0 != 0) {
                    if (a0 == t6) {
                        v1 = 0x00200000 + 0x7cf8;
                    } else {
                        v1 = ret + 0x7d10;
                    }
                }
                ret = v1 & a3;
                v1 = s3 << 0x10;
                ret = (unsigned)ret >> 2;
                v1 = (signed)v1 >> 0x10;
                *(u32*)(s0) = ret | t0;
                s0 = s0 + 4;
                if (v1 == 0) {
                    *(u32*)(s0) = t5;
                    s0 = s0 + 4;
                } else {
                    ret = (unsigned)v1 >> 0x10;
                    if (v1 == ret) {
                        ret = v1 & 0xffff;
                        a0 = s0 + 4;
                        *(u32*)(s0) = ret | a2;
                        goto loc_2080F8;
                    }
                    v1 = v1 & 0xffff;
                    ret = ret | t3;
                    a0 = s0 + 4;
                    ret = ret | a2;
                    *(u32*)(s0) = ret;
                    if (v1 == 0) goto loc_2080F8;
                    *(u32*)(a0) = ret | t1;
                    a0 = s0 + 8;
                    loc_2080F8:
                    s0 = a0;
                }
                *(u32*)(s0) = v1 | 0x0040002D;
            }
            s0 = s0 + 4;
            s3 = *(u32*)(s0);
            v1 = 0x20;
            s2 = (unsigned)s3 >> 0x1a;
            if (((unsigned)s3 >> 0x15) == v1) goto loc_207F90;
        }
loc_208130:
    SYNC(); /* memory barrier */
    CACHE(0x18, (s4)); /* cache op */
    SYNC(); /* memory barrier */
    CACHE(0x18, (s0)); /* cache op */
    SYNC(); /* memory barrier */
    SYNC(); /* memory barrier */
    CACHE(0xb, (s4)); /* cache op */
    SYNC(); /* memory barrier */
    CACHE(0xb, (s0)); /* cache op */
    SYNC(); /* memory barrier */
    SYNC(); /* memory barrier */
    EI();
    return ret;
}

/* Function at 0x00208180 - 0x00208258 */
u32 Compiler_Emit_Exception(u32 a0)
{
    /* Stack frame: 128 bytes */
    u32 ret, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6, s7, psx;
    __gp = a0;
    __k1 = ((PSX_State*)psx)->cop2_insn_count;
    __at = 0x1FFFFFFF;
    s0 = ((PSX_State*)psx)->gpr[2];
    s1 = ((PSX_State*)psx)->gpr[3];
    s2 = ((PSX_State*)psx)->gpr[4];
    s3 = ((PSX_State*)psx)->gpr[5];
    s4 = ((PSX_State*)psx)->gpr[6];
    s5 = ((PSX_State*)psx)->gpr[16];
    s6 = ((PSX_State*)psx)->gpr[17];
    s7 = ((PSX_State*)psx)->gpr[29];
    __fp = ((PSX_State*)psx)->gpr[31];
    return Compiler_Emit_InterruptCheck(a0, a1, a2);
loc_2081F0:
    ((PSX_State*)psx)->gpr[2] = s0;
    ((PSX_State*)psx)->gpr[3] = s1;
    ((PSX_State*)psx)->gpr[4] = s2;
    ((PSX_State*)psx)->gpr[5] = s3;
    ((PSX_State*)psx)->gpr[6] = s4;
    ((PSX_State*)psx)->gpr[16] = s5;
    ((PSX_State*)psx)->gpr[17] = s6;
    ((PSX_State*)psx)->gpr[29] = s7;
    ((PSX_State*)psx)->gpr[31] = __fp;
    ((PSX_State*)psx)->cop2_insn_count = __k1;
    return ret;
}

/* Function at 0x00208258 - 0x00208568 */
u32 Compiler_Emit_InterruptCheck(u32 a0, u32 a1, u32 a2)
{
    u32 ret, v1;
    ret = *(u32*)(gp);
    if ((signed)__k1 <= 0) {
        ret = 2;
        return Compiler_Emit_Exception(a0);
    }
    ret = ret & __at;
    a0 = ((signed)ret < (signed)0x1FC00000) ? 1 : 0;
    a2 = *(u32*)(a2 + 0x2748);
    a1 = 0x00200000;
    if (a0 == 0) {
        ret = ret + a1;
    } else {
        a1 = 0x001FFFFF;
        ret = ret & a1;
    }
    v1 = ret + a2;
    a2 = *(u32*)(v1);
    if (a2 == 0) {
        ret = 1;
        return Compiler_Emit_Exception(a0);
    }
    goto *a2; /* computed jump */
    return ret;
    ret = ret + a2;
    a2 = *(u32*)(ret);
    if (a2 == 0) {
        ret = 1;
        goto loc_2081F0; /* tail call into Compiler_Emit_Exception */
    }
    ret = ret << 4;
    *(u32*)(__ra + -8) = ret | 0x0C000000;
    SYNC(); /* memory barrier */
    CACHE(0x18, -8(__ra)); /* cache op */
    SYNC(); /* memory barrier */
    SYNC(); /* memory barrier */
    CACHE(0xb, -8(__ra)); /* cache op */
    SYNC(); /* memory barrier */
    goto *a2; /* computed jump */
    return ret;
loc_208520:
    ret = *(u32*)(a0);
    v1 = v1 + -1;
    a1 = a1 - ret;
    a0 = a0 + 4;
    if (v1 != 0) goto loc_208520;
    if (a1 != 0) goto loc_208520;
    return ret;
}

/* Function at 0x00208568 - 0x00208758 */
u32 Compiler_Emit_FloatLoad(u32 a0, u32 a1)
{
    u32 ret, v1, a2, a3, t0, t1, t2, t3;
    ret = 0x1FFFFFFF;
    v1 = 0x007FFFFF;
    t0 = a0 & ret;
    v1 = ((unsigned)v1 < (unsigned)t0) ? 1 : 0;
    t3 = a1;
    if (v1 == 0) {
        a0 = *(u32*)(0x00500000 + 0x2710);
        ret = t0 & ret;
        v1 = ((PSX_State*)a0)->ram_base;  /* ram_base */
        a2 = v1 + ret;
    } else {
        a1 = 0xE0800000;
        ret = t0 + a1;
        a1 = 0xE0400000;
        if ((unsigned)ret < 0x400) {
            a0 = *(u32*)(0x00500000 + 0x2710);
            v1 = ((PSX_State*)a0)->scratch_base;  /* scratch_base */
            goto loc_20861C;
        }
        ret = 7 << 16;
        v1 = t0 + a1;
        ret = ((unsigned)ret < (unsigned)v1) ? 1 : 0;
        a1 = 0xE0800400;
        ret = t0 + a1;
        a2 = 0;
        if ((unsigned)ret >= 0x400) goto loc_208624;
        a0 = *(u32*)(0x00500000 + 0x2710);
        v1 = ((PSX_State*)a0)->hw_regs_base;  /* hw_regs_base */
        loc_20861C:
        v1 = v1 + t0;
        a2 = v1 + a1;
    }
loc_208624:
    a1 = a2 + 4;
    v1 = a2 << 0x10;
    ret = (unsigned)a2 >> 0x10;
    a0 = a1 << 0x10;
    v1 = (unsigned)v1 >> 0x1f;
    a0 = (unsigned)a0 >> 0x1f;
    v1 = v1 + ret;
    ret = (unsigned)a1 >> 0x10;
    t0 = 0x3C000000;
    a0 = a0 + ret;
    v1 = v1 & 0xffff;
    a3 = *(u32*)(a2);
    t2 = *(u32*)(a1);
    a1 = a1 & 0xffff;
    ret = 2 << 16;
    a0 = a0 & 0xffff;
    v1 = v1 | t0;
    t1 = 0x8C000000;
    v1 = v1 | ret;
    ret = 3 << 16;
    a0 = a0 | t0;
    a2 = a2 & 0xffff;
    *(u32*)(t3) = v1;
    t3 = t3 + 4;
    a0 = a0 | ret;
    ret = 0x00420000;
    a3 = a3 + t2;
    a2 = a2 | t1;
    *(u32*)(t3) = a0;
    t3 = t3 + 4;
    a2 = a2 | ret;
    ret = (unsigned)a3 >> 0x10;
    v1 = 0x00630000;
    a1 = a1 | t1;
    *(u32*)(t3) = a2;
    t3 = t3 + 4;
    a1 = a1 | v1;
    v1 = 4 << 16;
    ret = ret | t0;
    *(u32*)(t3) = a1;
    ret = ret | v1;
    v1 = 0x34000000;
    t3 = t3 + 4;
    a3 = a3 & 0xffff;
    *(u32*)(t3) = ret;
    a3 = a3 | v1;
    a0 = 0x00431021;
    t3 = t3 + 4;
    ret = 0x00830000;  /* CDROM_SECTOR_BUF: CD-ROM sector buffer */
    *(u32*)(t3) = a0;
    t3 = t3 + 4;
    a3 = a3 | ret;
    v1 = 0x002081F0;
    a1 = 0x0FFFFFFF;
    *(u32*)(t3) = a3;
    t3 = t3 + 4;
    ret = 0x10430003;
    v1 = v1 & a1;
    *(u32*)(t3) = ret;
    t3 = t3 + 4;
    ret = 0x08000000;
    v1 = (unsigned)v1 >> 2;
    *(u32*)(t3) = 0;
    t3 = t3 + 4;
    *(u32*)(t3) = v1 | ret;
    t3 = t3 + 4;
    a0 = 0x24020006;
    ret = t3 + 4;
    *(u32*)(t3) = a0;
    return ret;
}

/* Function at 0x00208758 - 0x00208760 */
u32 Compiler_Emit_NoOp(void)
{
    u32 ret;
    return ret;
}

/* Function at 0x00208760 - 0x00208800 */
u32 Compiler_InitializeLookupTables(void)
{
    u32 ret, v1, a0, a1, a2, a3, t0, t1, t2, t3, t4, t5, t6, t7;
    ret = 0x70000300;
    a0 = 0x70000310;
    a1 = 0x70000320;
    v1 = 0x70000330;
    a2 = 0x70000340;
    a3 = -0x8000;
    t3 = 0x7fff;
    t4 = 0xff;
    t0 = 0x81000000;
    t1 = 0x80800000;
    t2 = 0x00400000;
    t5 = 0x00200000;
    t6 = 0x00100000;
    t7 = 8 << 16;
    *(u32*)(ret) = t0;
    *(u32*)(ret + 4) = t1;
    *(u32*)(ret + 8) = t2;
    *(u32*)(ret + 0xc) = 0;
    *(u32*)(a0 + 8) = a3;
    *(u32*)(a0 + 0xc) = 0;
    *(u32*)(a1 + 8) = t3;
    *(u32*)(a1 + 0xc) = 0;
    *(u32*)(v1) = t5;
    *(u32*)(v1 + 4) = t6;
    *(u32*)(v1 + 8) = t7;
    *(u32*)(v1 + 0xc) = 0;
    *(u32*)(a2 + 8) = t4;
    *(u32*)(a2 + 0xc) = 0;
    *(u32*)(a0) = a3;
    *(u32*)(a0 + 4) = a3;
    *(u32*)(a1) = t3;
    *(u32*)(a1 + 4) = t3;
    *(u32*)(a2) = t4;
    *(u32*)(a2 + 4) = t4;
    return ret;
}

/* Function at 0x00208800 - 0x00209E00 */
u32 Compiler_InitializeGTEConstants(u32 a0)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a1, a2, a3, s0, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    s0 = a0;
    ret = Compiler_InitializeLookupTables();
    ret = 0x00210000;
    v1 = 0x00210000;
    a2 = (u32)Compiler_Emit_InterruptCheck;
    ret = (u32)Compiler_Emit_Exception;
    v1 = 0x002082C8;
    a3 = 0x00208360;
    t0 = 0x00208510;
    t1 = 0x00208560;
    t2 = 0x00208460;
    t3 = 0x00208420;
    t4 = 0x002084A0;
    t5 = 0x002084E0;
    *(u32*)(s0) = ret;
    *(u32*)(s0 + 4) = v1;
    *(u32*)(s0 + 0x10) = a2;
    a0 = PSX_IRQ_STAT_ADDR;  /* 0x00506C00 - IRQ status register address */
    *(u32*)(s0 + 0x14) = a3;
    a1 = PSX_IRQ_MASK_ADDR;  /* 0x00506C04 - IRQ mask register address */
    *(u32*)(s0 + 0x18) = t0;
    *(u32*)(s0 + 0x1c) = t1;
    *(u32*)(s0 + 0x20) = t2;
    *(u32*)(s0 + 0x24) = t3;
    *(u32*)(s0 + 0x2c) = t4;
    *(u32*)(s0 + 0x30) = t5;
    *(u32*)(s0 + 8) = a2;
    *(u32*)(s0 + 0xc) = a2;
    *(u32*)(s0 + 0x3c) = 0;
    *(u32*)(s0 + 0x34) = 0;
    *(u32*)(s0 + 0x38) = 0;
    ret = R3000_GetCachePointers(a0, a1);
    return 1;
                t3 = LO;
            HI_LO = (s64)t0 * (s64)t3;
            0 = t1 * t3;
            t4 = ((PSX_State*)a0)->cop0[20];  /* cop0[20] */
            t5 = ((PSX_State*)a0)->cop0[21];  /* cop0[21] */
            __asm("pmfhl ret, 0, 0");
            __asm("mmi3 v1, ret, ret");
            t4 = t4 + ret;
            t5 = t5 + v1;
            t4 = (signed)t4 >> 16;
            t5 = (signed)t5 >> 16;
            ret = -0x400;
            v1 = 0x3ff;
            t6 = 0x80004000;
            t7 = ((signed)t4 < (signed)ret) ? 1 : 0;
            if (t7 != 0) t4 = ret;
            if (t7 != 0) t7 = t6;
            __at = __at | t7;
            t7 = ((signed)v1 < (signed)t4) ? 1 : 0;
            if (t7 != 0) t4 = v1;
            if (t7 != 0) t7 = t6;
            __at = __at | t7;
            t6 = t6 + -0x2000;
            t7 = ((signed)t5 < (signed)ret) ? 1 : 0;
            if (t7 != 0) t5 = ret;
            if (t7 != 0) t7 = t6;
            __at = __at | t7;
            t7 = ((signed)v1 < (signed)t5) ? 1 : 0;
            if (t7 != 0) t5 = v1;
            if (t7 != 0) t7 = t6;
            __at = __at | t7;
            *(u16*)(a1 + 0x30) = t4;
            *(u16*)(a1 + 0x32) = t5;
            t9 = t9 + -1;
            a1 = a1 + 4;
            a2 = a2 + 8;
        ret = *(s16*)&((PSX_State*)a0)->cop0[23];  /* cop0[23] */
        t3 = (s32)((s64)ret * (s64)t3); HI_LO = (s64)ret * (s64)t3;
        v1 = ((PSX_State*)a0)->cop0[24];  /* cop0[24] */
        t3 = t3 + v1;
        ((PSX_State*)a0)->gpr[20] = t3;  /* gpr[20] (store) */
        t3 = (signed)t3 >> 12;
        v1 = 0x1000;
        t6 = ((signed)t3 < (signed)0) ? 1 : 0;
        t7 = ((signed)v1 < (signed)t3) ? 1 : 0;
        if (t6 != 0) t3 = 0;
        if (t7 != 0) t3 = v1;
        t6 = t6 | t7;
        t6 = t6 << 0xc;
        __at = __at | t6;
        ((PSX_State*)a0)->gpr[4] = t3;  /* gpr[4] (store) */
        ((PSX_State*)a0)->cop0[27] = __at;  /* cop0[27] (store) */
        return ret;
    __asm("mmi3 t2, 0, 0");
    goto loc_208BA0;
loc_208BA0:
    t0 = ((PSX_State*)a0)->gpr[4];  /* gpr[4] */
    __asm("mmi3 at, 0, 0");
    __asm("mmi0 t0, t0, t0");
    t1 = ((PSX_State*)a0)->gpr[5];  /* gpr[5] */
    ret = ((PSX_State*)a0)->gpr[6];  /* gpr[6] */
    v1 = ((PSX_State*)a0)->gpr[7];  /* gpr[7] */
    __asm("mmi0 t1, ret, t1");
    __asm("mmi2 t1, v1, t1");
    __asm("mmi0 t0, t0, t0");
    ret = ((PSX_State*)a0)->gpr[17];  /* gpr[17] */
    v1 = ((PSX_State*)a0)->gpr[18];  /* gpr[18] */
    ((PSX_State*)a0)->gpr[16] = ret;  /* gpr[16] (store) */
    ((PSX_State*)a0)->gpr[17] = v1;  /* gpr[17] (store) */
    __asm("mmi2 t0, t0, t1");
    ret = 0x70000000;
    __asm("add_a.w w12, w0, w14");
    __asm("ld.b w12, 0x4f(0)");
    __asm("andi.b w12, w0, 0x58");
    __asm("sdbbp 0x210c");
    if (a1 != 0) goto loc_208BF0;
loc_208BF0:
    __asm("mmi0 t0, t0, t2");
    ret = (s64)t0 >> 32;
    ((PSX_State*)a0)->gpr[21] = t0;  /* gpr[21] (store) */
    __asm("mmi3 v1, t0, t0");
    ((PSX_State*)a0)->gpr[22] = ret;  /* gpr[22] (store) */
    ((PSX_State*)a0)->gpr[23] = v1;  /* gpr[23] (store) */
    __asm("mmi0 ret, t6, t0");
    __asm("mmi0 v1, t6, t0");
    __asm("mmi2 t3, ret, t8");
    __asm("mmi0 ret, v1, t7");
    __asm("mmi3 at, at, t3");
    __asm("mmi2 t3, ret, t8");
    __asm("mmi1 t1, v1, t7");
    __asm("mmi3 at, at, t3");
    ret = (s64)t1 >> 32;
    ((PSX_State*)a0)->gpr[5] = t1;  /* gpr[5] (store) */
    __asm("mmi3 v1, t1, t1");
    ((PSX_State*)a0)->gpr[6] = ret;  /* gpr[6] (store) */
    ((PSX_State*)a0)->gpr[7] = v1;  /* gpr[7] (store) */
    __asm("sdbbp 0x2104");
    v1 = *(u128*)(0x70000000 + 816);  /* lq */
    __asm("andi.b w13, w0, 0x42");
    __asm("mmi0 t3, 0, t0");
    __asm("mmi0 t4, 0, t0");
    __asm("mmi2 t5, t3, v1");
    __asm("mmi0 t3, t4, ret");
    __asm("mmi3 at, at, t5");
    __asm("mmi2 t5, t3, v1");
    __asm("mmi1 t1, t4, ret");
    __asm("mmi3 at, at, t5");
    t3 = *(s8*)(a0 + 0x1b);  /* lb */
    ret = (s64)t1 >> 32;
    *(u8*)&((PSX_State*)a0)->gpr[18] = t1;  /* gpr[18] (store) */
    __asm("mmi3 v1, t1, t1");
    *(u8*)(a0 + 0x59) = ret;
    *(u8*)(a0 + 0x5a) = v1;
    *(u8*)(a0 + 0x5b) = t3;
    ret = (u64)__at >> 32;
    __asm("mmi1 v1, at, at");
    __at = __at | ret;
    __at = __at | v1;
    ret = 0x7F87E000;
    v1 = 0x80000000;
    ret = ret & __at;
    if (ret == 0) v1 = 0;
    __at = __at | v1;
    ((PSX_State*)a0)->cop0[27] = __at;  /* cop0[27] (store) */
    return ret;
    t0 = (signed)t0 >> 12;
    t1 = (signed)t1 >> 12;
    t2 = (signed)t2 >> 12;
    ((PSX_State*)a0)->gpr[21] = t0;  /* gpr[21] (store) */
    ((PSX_State*)a0)->gpr[22] = t1;  /* gpr[22] (store) */
    ((PSX_State*)a0)->gpr[23] = t2;  /* gpr[23] (store) */
    ret = 0x7fff;
    t6 = ((signed)t0 < (signed)0) ? 1 : 0;
    t7 = ((signed)ret < (signed)t0) ? 1 : 0;
    if (t6 != 0) t0 = 0;
    if (t7 != 0) t0 = ret;
    t6 = t6 | t7;
    t6 = t6 << 0x18;
    __at = __at | t6;
    t6 = ((signed)t1 < (signed)0) ? 1 : 0;
    t7 = ((signed)ret < (signed)t1) ? 1 : 0;
    if (t6 != 0) t1 = 0;
    if (t7 != 0) t1 = ret;
    t6 = t6 | t7;
    t6 = t6 << 0x17;
    __at = __at | t6;
    t6 = ((signed)t2 < (signed)0) ? 1 : 0;
    t7 = ((signed)ret < (signed)t2) ? 1 : 0;
    if (t6 != 0) t2 = 0;
    if (t7 != 0) t2 = ret;
    t6 = t6 | t7;
    t6 = t6 << 0x16;
    __at = __at | t6;
    ((PSX_State*)a0)->gpr[5] = t0;  /* gpr[5] (store) */
    ((PSX_State*)a0)->gpr[6] = t1;  /* gpr[6] (store) */
    ((PSX_State*)a0)->gpr[7] = t2;  /* gpr[7] (store) */
    t0 = (signed)t0 >> 4;
    t1 = (signed)t1 >> 4;
    t2 = (signed)t2 >> 4;
    ret = 0xff;
    a1 = ((signed)t0 < (signed)0) ? 1 : 0;
    a2 = ((signed)ret < (signed)t0) ? 1 : 0;
    if (a1 != 0) t0 = 0;
    if (a2 != 0) t0 = ret;
    a1 = a1 | a2;
    a1 = a1 << 0x15;
    __at = __at | a1;
    a1 = ((signed)t1 < (signed)0) ? 1 : 0;
    a2 = ((signed)ret < (signed)t1) ? 1 : 0;
    if (a1 != 0) t1 = 0;
    if (a2 != 0) t1 = ret;
    a1 = a1 | a2;
    a1 = a1 << 0x14;
    __at = __at | a1;
    a1 = ((signed)t2 < (signed)0) ? 1 : 0;
    a2 = ((signed)ret < (signed)t2) ? 1 : 0;
    if (a1 != 0) t2 = 0;
    if (a2 != 0) t2 = ret;
    a1 = a1 | a2;
    a1 = a1 << 0x13;
    __at = __at | a1;
    ret = *(s8*)(a0 + 0x1b);  /* lb */
    *(u8*)&((PSX_State*)a0)->gpr[18] = t0;  /* gpr[18] (store) */
    *(u8*)(a0 + 0x59) = t1;
    *(u8*)(a0 + 0x5a) = t2;
    *(u8*)(a0 + 0x5b) = ret;
    ret = 0x7F87E000;
    v1 = 0x80000000;
    ret = ret & __at;
    if (ret == 0) v1 = 0;
    __at = __at | v1;
    ((PSX_State*)a0)->cop0[27] = __at;  /* cop0[27] (store) */
    return ret;
        v1 = *(u128*)(0x70000000 + 816);  /* lq */
        __asm("andi.b w13, w0, 0x42");
        __asm("mmi0 t6, 0, t8");
        __asm("mmi0 t7, 0, t8");
        __asm("mmi2 a2, t6, v1");
        __asm("mmi0 t6, t7, ret");
        __asm("mmi3 at, at, a2");
        __asm("mmi2 a2, t6, v1");
        __asm("mmi1 t8, t7, ret");
        __asm("mmi3 at, at, a2");
        a2 = a1 << 2;
        a2 = a2 + a0;
        t6 = *(s8*)(a0 + 0x1b);  /* lb */
        ret = (s64)t8 >> 32;
        *(u8*)(a2 + 0x50) = t8;
        __asm("mmi3 v1, t8, t8");
        *(u8*)(a2 + 0x51) = ret;
        *(u8*)(a2 + 0x52) = v1;
        *(u8*)(a2 + 0x53) = t6;
        ret = ((unsigned)a1 < 2) ? 1 : 0;
        a1 = a1 + 1;
        a2 = a1 << 3;
        a2 = a2 + a0;
    __asm("mmi3 ret, a0, a0");
    __asm("sdbbp 0x672c");
    if (ret != 0) goto loc_2096CC;
loc_2096CC:
    ret = (s64)t9 >> 32;
    ((PSX_State*)a0)->gpr[21] = t9;  /* gpr[21] (store) */
    __asm("mmi3 v1, t9, t9");
    ((PSX_State*)a0)->gpr[22] = ret;  /* gpr[22] (store) */
    ((PSX_State*)a0)->gpr[23] = v1;  /* gpr[23] (store) */
    ret = 0x70000000;
    __asm("andi.b w12, w0, 0x43");
    __asm("ld.b w12, 0x42(0)");
    __asm("mmi0 t6, 0, t9");
    __asm("mmi0 t7, 0, t9");
    __asm("mmi2 t8, t6, v1");
    __asm("mmi0 t6, t7, ret");
    __asm("mmi3 at, at, t8");
    __asm("mmi2 t8, t6, v1");
    __asm("mmi1 t9, t7, ret");
    __asm("mmi3 at, at, t8");
    ret = (s64)t9 >> 32;
    ((PSX_State*)a0)->gpr[5] = t9;  /* gpr[5] (store) */
    __asm("mmi3 v1, t9, t9");
    ((PSX_State*)a0)->gpr[6] = ret;  /* gpr[6] (store) */
    ((PSX_State*)a0)->gpr[7] = v1;  /* gpr[7] (store) */
    ret = (u64)__at >> 32;
    __asm("mmi1 v1, at, at");
    __at = __at | ret;
    __at = __at | v1;
    ret = 0x7F87E000;
    v1 = 0x80000000;
    ret = ret & __at;
    if (ret == 0) v1 = 0;
    __at = __at | v1;
    ((PSX_State*)a0)->cop0[27] = __at;  /* cop0[27] (store) */
    return ret;
    HI_LO = (s64)t0 * (s64)ret;
    0 = t3 * ret;
    HI_LO += (s64)t1 * v1;
    __asm("clz v1, t4");
    HI_LO += (s64)t2 * a1;
    __asm("clz a1, t5");
    __asm("pmfhl t0, 0, 0");
    __asm("mmi3 t1, t0, t0");
    HI_LO = (s64)t6 * (s64)ret;
    HI_LO += (s64)t7 * v1;
    HI_LO += (s64)t8 * a1;
    t3 = 0;
    t4 = 0;
    __asm("pmfhl t2, 0, 0");
    t5 = 0;
    if (a3 != 0) {
        t3 = *(u32*)(a3);
        t4 = *(u32*)(a3 + 4);
        t5 = *(u32*)(a3 + 8);
    }
    t3 = t3 << 12;
    t4 = t4 << 12;
    t5 = t5 << 12;
    t0 = t0 + t3;
    t1 = t1 + t4;
    t2 = t2 + t5;
    if (t9 != 0) {
        t0 = (signed)t0 >> 12;
        t1 = (signed)t1 >> 12;
        t2 = (signed)t2 >> 12;
    }
    ((PSX_State*)a0)->gpr[21] = t0;  /* gpr[21] (store) */
    ((PSX_State*)a0)->gpr[22] = t1;  /* gpr[22] (store) */
    ((PSX_State*)a0)->gpr[23] = t2;  /* gpr[23] (store) */
    ret = __at;
    v1 = 0x7fff;
    __at = 0;
    a1 = ((signed)t0 < (signed)ret) ? 1 : 0;
    a2 = ((signed)v1 < (signed)t0) ? 1 : 0;
    if (a1 != 0) t0 = ret;
    if (a2 != 0) t0 = v1;
    a1 = a1 | a2;
    a1 = a1 << 0x18;
    __at = __at | a1;
    a1 = ((signed)t1 < (signed)ret) ? 1 : 0;
    a2 = ((signed)v1 < (signed)t1) ? 1 : 0;
    if (a1 != 0) t1 = ret;
    if (a2 != 0) t1 = v1;
    a1 = a1 | a2;
    a1 = a1 << 0x17;
    __at = __at | a1;
    a1 = ((signed)t2 < (signed)ret) ? 1 : 0;
    a2 = ((signed)v1 < (signed)t2) ? 1 : 0;
    if (a1 != 0) t2 = ret;
    if (a2 != 0) t2 = v1;
    a1 = a1 | a2;
    a1 = a1 << 0x16;
    __at = __at | a1;
    ((PSX_State*)a0)->gpr[5] = t0;  /* gpr[5] (store) */
    ((PSX_State*)a0)->gpr[6] = t1;  /* gpr[6] (store) */
    ((PSX_State*)a0)->gpr[7] = t2;  /* gpr[7] (store) */
    ret = 0x7F87E000;
    v1 = 0x80000000;
    ret = ret & __at;
    if (ret == 0) v1 = 0;
    __at = __at | v1;
    ((PSX_State*)a0)->cop0[27] = __at;  /* cop0[27] (store) */
    return ret;
}

/* Function at 0x00209E00 - 0x00209EF0 */
u32 Compiler_MemoryCopy(u32 a0, u32 a1, u32 a2)
{
    u32 ret, v1, t0, t1;
    ret = a0 & 0xf;
    if (a2 == 0) goto loc_209E3C;
    ret = a1 & 0xf;
    if (ret == 0) goto loc_209E40;
    ret = *(u8*)(a1);
    do {
        a1 = a1 + 1;
        a2 = a2 + -1;
        *(u8*)(a0) = ret;
        a0 = a0 + 1;
        ret = a0 & 0xf;
        if (a2 == 0) goto loc_209E3C;
        ret = *(u8*)(a1);
    } while (ret != 0);
loc_209E3C:
    ret = a1 & 0xf;
loc_209E40:
    if (ret != 0) {
        t1 = ((signed)a2 < 0x10) ? 1 : 0;
        __asm(".word 0x04b80000"); /* 0x00209E4C EE unknown */
        __asm("pref 0, (a1)");
        if (t1 == 0) {
            do {
                __asm("andi.b w0, w0, 0xa8");
                __asm("adds_a.h w0, w0, w9");
                __asm("mmi1 t0, t1, t0");
                a1 = a1 + 0x10;
                __asm("ext t0, a0, 0, 1");
                a2 = a2 + -0x10;
                t1 = ((signed)a2 < 0x10) ? 1 : 0;
                a0 = a0 + 0x10;
            } while (t1 == 0);
        }
        a2 = a2 + -1;
        goto loc_209EB4;
    }
    t1 = ((signed)a2 < 0x10) ? 1 : 0;
    __asm("pref 0, (a1)");
    if (t1 == 0) {
        do {
            __asm("andi.b w0, w0, 0xa8");
            a1 = a1 + 0x10;
            __asm("ext t0, a0, 0, 1");
            a2 = a2 + -0x10;
            t1 = ((signed)a2 < 0x10) ? 1 : 0;
            a0 = a0 + 0x10;
        } while (t1 == 0);
    }
    a2 = a2 + -1;
loc_209EB4:
    if (a2 != -1) {
        v1 = -1;
        do {
            ret = *(u8*)(a1);
            a1 = a1 + 1;
            a2 = a2 + -1;
            *(u8*)(a0) = ret;
            a0 = a0 + 1;
        } while (a2 != v1);
    }
    return ret;
}

/* Function at 0x00209EF0 - 0x00209F80 */
u32 Compiler_MemoryClear(u32 a0, u32 a1)
{
    u32 ret, t0;
    goto loc_209F00;
loc_209EF8:
    *(u8*)(a0) = 0;
    a0 = a0 + 1;
loc_209F00:
    ret = a0 & 0xf;
    if (a1 != 0) {
        a1 = a1 + -1;
        if (ret != 0) goto loc_209EF8;
    }
    if ((signed)a1 >= (signed)0x10) {
        do {
            __asm("ext 0, a0, 0, 1");
            a0 = a0 + 0x10;
            a1 = a1 + -0x10;
            t0 = ((signed)a1 < 0x10) ? 1 : 0;
        } while (t0 == 0);
    }
    ret = -1;
    a1 = a1 + -1;
    if (a1 != ret) {
        do {
            a1 = a1 + -1;
            *(u8*)(a0) = 0;
            a0 = a0 + 1;
        } while (a1 != ret);
    }
    return ret;
}

/* Function at 0x00209F80 - 0x00209F98 */
u32 Compiler_SetCacheFlushFlag(u32 a0)
{
    u32 ret, v1, a1;
    ret = g_compiler_irq0;
    v1 = v1 << a0;
    a0 = 0;
    a1 = g_compiler_irq1;
    ret = ret | v1;
}

/* Function at 0x00209F98 - 0x00209FC8 */
u32 Compiler_RequestCacheFlush(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, a2, a3;
    g_compiler_irq0 = ret;
    if ((ret & a1) != 0) {
        return PSX_SetIRQBit(a0);
    }
    a0 = 0;
    return PSX_ClearIRQBit(a0);
}

/* Function at 0x00209FC8 - 0x0020A000 */
u32 Compiler_GetCacheStatus(void)
{
    u32 ret;
    return ret;
            return g_compiler_irq0;
    return g_compiler_irq1;
}

/* Function at 0x0020A000 - 0x0020A080 */
u32 Compiler_ClearCacheFlushFlag(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a2, a3;
    a0 = a0 & 0xf;
    if (a0 != 0) {
        ret = 4;
        v1 = g_compiler_irq0;
        if (a0 != ret) {
            ret = g_compiler_irq1;
            goto loc_20A04C;
            }
            ret = -1;
            v1 = g_compiler_irq0;
            if (a1 == ret) goto loc_20A070;
            g_compiler_irq0 = v1 & a1;
        } else {
            ret = a1 & 0xffff;
            g_compiler_irq1 = ret;
        }
    ret = g_compiler_irq1;
loc_20A04C:
    ret = v1 & ret;
    if (ret != 0) {
        a0 = 0;
        ret = PSX_SetIRQBit(a0);
    } else {
        a0 = 0;
        ret = PSX_ClearIRQBit(a0);
        loc_20A070:
    }
    return ret;
}

/* Function at 0x0020A080 - 0x0020A090 */
u32 Compiler_ResetCacheState(void)
{
    u32 ret;
    g_compiler_irq1 = 0;
    g_compiler_irq0 = 0;
    return ret;
}
