/* POPS.ELF Decompiled - interrupt.c */
/* Auto-generated by POPS Decompiler */
/* 16 functions */

#include "pops_types.h"
#include "functions.h"

/* Forward declarations */
u32 Interrupt_Init(void);
u32 Interrupt_RegisterIO(u32 a0, u32 a1, u32 a2, u32 a3);
u32 Interrupt_CheckPending(void);
void Interrupt_SetupVector(void);
u32 Interrupt_AccumulateCycles(void);
u32 Interrupt_ProcessChannel(u32 a0);
u32 Interrupt_AcknowledgeChannel(u32 a0);
u32 Interrupt_StartChannel(u32 a0);
u32 Interrupt_ReadIO(u32 a0, u32 a1);
u32 Interrupt_WriteIO(u32 a0, u32 a1, u32 a2);
u32 Interrupt_ScheduleVBlank(void);
u32 Interrupt_ResetCounter(void);
u32 Interrupt_UpdateCounter(u32 a0);
u32 Interrupt_AdvanceTiming(void);
u32 Interrupt_SetCallback(u32 a0, u32 a1);
u32 Interrupt_ResetAll(void);

/* ======================================== */

/* Function at 0x0020A090 - 0x0020A09C */
u32 Interrupt_Init(void)
{
    u32 a0, a2, a3;
    a2 = 0x00210000;
    a3 = 0x00210000;
    a0 = PSX_IO_BASE;  /* 0x1F800000 */
    return Interrupt_RegisterIO(a0, 0, a2, a3);
}

/* Function at 0x0020A09C - 0x0020A0CC */
u32 Interrupt_RegisterIO(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret;
    a2 = a2 + -0x6030;
    a3 = a3 + -0x6000;
    a0 = a0 | 0x1070;  /* PSX_IRQ_BASE: Interrupt Controller (0x1F801070) */
    a1 = 0x10;  /* I/O range size */
    ret = R3000_SetupIOHandlers(a0, a1, a2, a3);
    return 1;
}

/* Function at 0x0020A0CC - 0x0020A110 */
u32 Interrupt_CheckPending(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3;
    v1 = g_compiler_irq1;
    if ((ret & v1) != 0) {
        a0 = 0;
        return PSX_SetIRQBit(a0);
    }
    a0 = 0;
    return PSX_ClearIRQBit(a0);
}

/* Function at 0x0020A110 - 0x0020A138 */
void Interrupt_SetupVector(void)
{
    /* Stack frame: 16 bytes */
    u32 a0, a1, a2, a3;
    a1 = 0;
    a0 = 0x80034030;
    a2 = 0;
    System_BootTimerSetup(a0, a1, a2, a3); return;
}

/* Function at 0x0020A138 - 0x0020A170 */
u32 Interrupt_AccumulateCycles(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3, t9;
    v1 = COP0_REG(25); /* mfc0 */
    ret = ret + v1;
    g_irq_stat = ret;
    v1 = COP0_REG(25); /* mfc0 */
    g_irq_mask = ret + v1;
    return System_GetCOP0Status();
}

/* Function at 0x0020A170 - 0x0020A2F8 */
u32 Interrupt_ProcessChannel(u32 a0)
{
    /* Stack frame: 64 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6;
    s1 = a0;
    s5 = s1 << 1;
    s6 = 0x00500000;
    ret = ret << 3;
    s2 = s6 + 0x6c08;
    ret = ret + s2;
    s4 = s1 << 4;
    s0 = ret + 0x7c;
    v1 = s2 + s4;
    a0 = *(u32*)(s0);
    s3 = *(u32*)(v1 + 8);
    if (a0 != 0) {
        ret = PSX_CancelEvent(a0);
        *(u32*)(s0) = 0;
    }
    ret = ret & 1;
    a0 = s1 + 0x18;
    if (ret == 0) goto loc_20A2BC;
    a1 = *(u32*)(s2 + 0x74);  /* PSX: gpr[25]/$t9 */
    ret = 1;
    v1 = 0x007F0000;
    ret = ret << a0;
    a2 = (unsigned)a1 >> 0x1f;
    a1 = a1 | ret;
    ret = a1 & v1;
    a0 = 0x80FFFFFF;
    ret = ret | a0;
    a1 = a1 & ret;
    v1 = a1 & v1;
    ret = 0x80000000;
    if (v1 != 0) {
        a1 = a1 | ret;
    } else {
        a1 = a1 & 0x7FFFFFFF;
    }
    ret = (unsigned)a1 >> 0x17;
    v1 = s6 + 0x6c08;
    ret = ret & 1;
    *(u32*)(v1 + 0x74) = a1;
    if (ret == 0) goto loc_20A268;
    if (a2 != 0) goto loc_20A268;
    if ((signed)a1 >= 0) goto loc_20A268;
    a0 = 3;
    Compiler_SetCacheFlushFlag(a0);
loc_20A268:
    a0 = s6 + 0x6c08;
    v1 = 0xFEFFFFFF;
    a1 = a0 + s4;
    s3 = s3 & v1;
    ret = s5 + s1;
    *(u32*)(a1 + 8) = s3;
    a1 = 2;
    ret = ret + a0;
    a0 = s4 + a0;
    v1 = *(u32*)(ret + 0x80);  /* PSX: gpr[28]/$gp */
    *(u32*)(a0) = v1;
    if (s1 != a1) goto loc_20A2BC;
    ret = (unsigned)s3 >> 8;
    v1 = 4;
    ret = s5 + s1;
    if (ret == v1) goto loc_20A2C0;
    ret = GPU_WaitBufferReady();
loc_20A2BC:
    ret = s5 + s1;
loc_20A2C0:
    v1 = s6 + 0x6c08;
    ret = ret + v1;
    *(u32*)(ret + 0x8c) = 0;
    return ret;
}

/* Function at 0x0020A2F8 - 0x0020A400 */
u32 Interrupt_AcknowledgeChannel(u32 a0)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6, s7;
    s1 = a0;
    s5 = s1 << 1;
    s7 = 0x00500000;
    a0 = s7 + 0x6c08;
    ret = s5 + s1;
    a1 = a0 + 8;
    s3 = ret << 3;
    s4 = a0 + 0xc;
    s6 = s1 << 4;
    a1 = s6 + a1;
    v1 = s3 + 0x70;
    s2 = v1 + s4;
    s0 = *(u32*)(a1);
    ret = 0xFEFFFFFF;
    v1 = *(u32*)(s2);
    s0 = s0 & ret;
    a0 = v1;
    *(u32*)(a1) = s0;
    if (v1 != 0) {
        ret = PSX_CancelEvent(a0);
        *(u32*)(s2) = 0;
    }
    ret = s3 + s4;
    v1 = *(u32*)(ret + 0x80);  /* PSX: gpr[28]/$gp */
    ret = 2;
    if (v1 != 0) {
        a0 = s5 + s1;
        if (s1 == ret) {
            ret = (unsigned)s0 >> 8;
            v1 = 4;
            ret = s7 + 0x6c08;
            if (ret == v1) {
                ret = Interrupt_ResetCounter();
                a0 = s5 + s1;
                }
                ret = s7 + 0x6c08;
            }
        a0 = a0 << 3;
        a1 = a0 + ret;
        ret = s6 + ret;
        v1 = *(u32*)(a1 + 0x80);  /* PSX: gpr[28]/$gp */
        a0 = a1;
        *(u32*)(ret) = v1;
        *(u32*)(a0 + 0x8c) = 0;
    }
    return ret;
}

/* Function at 0x0020A400 - 0x0020A5FC */
u32 Interrupt_StartChannel(u32 a0)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, psx, s4, s5, s6, s7;
    s1 = 0x00500000;
    s4 = a0;
    psx = s1 + 0x6c08;
    s5 = s4 << 4;
    ret = psx + s5;
    v1 = s4 << 2;
    s7 = *(u32*)(ret + 8);
    a0 = ((PSX_State*)psx)->channel_status;  /* channel_status */
    ret = (unsigned)s7 >> 0x18;
    a0 = (unsigned)a0 >> v1;
    ret = ret & 1;
    a0 = a0 & 8;
    if (ret == 0) goto loc_20A5C8;
    s0 = s4 << 1;
    a2 = psx + 0xc;
    ret = s0 + s4;
    a1 = ret << 3;
    v1 = a1 + a2;
    ret = *(u32*)(v1 + 0x80);  /* PSX: gpr[28]/$gp */
    if (ret != 0) goto loc_20A5CC;
    ret = a1 + 0x70;
    if (a0 == 0) goto loc_20A5C8;
    s2 = ret + a2;
    a0 = *(u32*)(s2);
    ret = 2;
    if (a0 != 0) {
        ret = PSX_CancelEvent(a0);
        *(u32*)(s2) = 0;
        ret = 2;
    }
    s0 = s0 + s4;
    if (s4 == ret) {
        ret = (unsigned)s7 >> 8;
        v1 = 4;
        ret = ret & 7;
        s1 = PSX_DMA_STATE;  /* 0x00506C08 - DMA/interrupt state base */
        if (ret == v1) {
            ((PSX_State*)psx)->int_pending_flag = 1;  /* int_pending_flag (store) */
            return Interrupt_ScheduleVBlank();
            }
            s1 = s1 + 0x6c08;
        }
    s0 = s0 << 3;
    s2 = s1 + 8;
    s6 = s0 + 0x70;
    s0 = s0 + 0x80;
    a3 = s5 + s2;
    psx = s5 + s1;
    v1 = s6 + s2;
    s2 = s0 + s2;
    a0 = s1 + s5;
    s5 = s1 + 0xc;
    a1 = *(u32*)(a0 + 4);
    s0 = s0 + s5;
    a2 = *(u32*)(a3);
    ret = *(u32*)(v1);
    a0 = *(u32*)(psx);
    ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
    a0 = s7 & 1;
    v1 = a0 << 3;
    a1 = ((signed)ret < 0) ? 1 : 0;
    v1 = v1 - a0;
    a0 = ret;
    v1 = v1 + s4;
    a3 = ret + 3;
    v1 = v1 << 2;
    if (a1 != 0) a0 = a3;
    a2 = 0x00500000;
    a2 = a2 + v1;
    a2 = *(u32*)(a2 + -0x69c0);
    v1 = (unsigned)s7 >> 1;
    a1 = *(u32*)(psx);
    a0 = (signed)a0 >> 2;
    a2 = (s32)((s64)a0 * (s64)a2); HI_LO = (s64)a0 * (s64)a2;
    v1 = v1 & 1;
    a0 = a1 + ret;
    a1 = a1 - ret;
    if (v1 == 0) a1 = a0;
    v1 = s1 + s6;
    s1 = v1;
    a0 = 1;
    *(u32*)(v1 + 0x10) = a1;
    *(u32*)(s2) = ret;
    *(u32*)(s1 + 0x14) = a2;
    *(u32*)(s0) = a0;
    if (s4 == a0) goto loc_20A5C8;
    a0 = a2;
    a1 = (u32)Interrupt_ProcessChannel;
    a2 = s4;
    PSX_GetEventTimeout();
    v1 = s6 + s5;
    *(u32*)(v1) = ret;
loc_20A5C8:
loc_20A5CC:
    return ret;
}

/* Function at 0x0020A5FC - 0x0020A844 */
u32 Interrupt_ReadIO(u32 a0, u32 a1)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, a2, a3, s0, s1, s2, s3, s4, s5, s6, s7;
    ret = ret | 0xef80;
    s6 = a0 + ret;
    v1 = ((unsigned)s6 < 0x70) ? 1 : 0;
    s7 = a1;
    if (v1 == 0) goto loc_20A788;
    v1 = s6 & 0xc;
    s2 = (unsigned)s6 >> 4;
    if (v1 != 0) {
        ret = 8;
        if (v1 != 2) {
            goto loc_20A78C;
            }
            ret = 2;
            a0 = 0x00500000;
            if (s2 == ret) {
            v1 = 4;
            a1 = a0 + 0x6c08;
            ret = ((PSX_State*)a1)->gpr[6];  /* gpr[6] */
            ret = s2 << 1;
            if (ret == v1) {
                ret = ((PSX_State*)a1)->cop0[11];  /* COP0: BPCM */
                ret = Interrupt_UpdateCounter(a0);
                ret = 2;
                goto loc_20A78C;
                }
                ret = s2 << 1;
            }
            s5 = a0 + 0x6c08;
            ret = ret + s2;
            a1 = s5 + 0xc;
            a0 = ret << 3;
            v1 = a0 + a1;
            ret = *(u32*)(v1 + 0x80);  /* PSX: gpr[28]/$gp */
            s4 = a0 + 0x70;
            if (ret == 0) goto loc_20A788;
            ret = s4 + a1;
            s3 = *(u32*)(ret);
            s1 = s2 << 4;
            if (s3 == 0) goto loc_20A788;
            ret = s5 + s1;
            s1 = s1 + s5;
            s0 = *(u32*)(ret + 8);
            ret = PSX_GetElapsedTime();
            a3 = *(u32*)(s3 + 8);
            a0 = s5 + s4;
            a2 = s0 & 1;
            s0 = (unsigned)s0 >> 1;
            v1 = a2 << 3;
            a1 = *(u32*)(a0 + 0x10);  /* PSX: gpr[0]/$zero */
            v1 = v1 - a2;
            ret = ret - a3;
            v1 = v1 + s2;
            s0 = s0 & 1;
            v1 = v1 << 2;
            a0 = 0x00500000;
            a0 = a0 + v1;
            a0 = *(u32*)(a0 + -0x69c0);
            ret = ret << 2;
            v1 = a1 + ret;
            a1 = a1 - ret;
            if (s0 == 0) a1 = v1;
            *(u32*)(s1) = a1;
            goto loc_20A788;
        }
    ret = s2 << 1;
    v1 = 0x00500000;
    ret = ret + s2;
    a0 = v1 + 0x6c08;
    ret = ret + a0;
    v1 = *(u32*)(ret + 0x8c);  /* PSX: gpr[31]/$ra */
    ret = 2;
    if (v1 == 0) goto loc_20A788;
    v1 = 4;
    if (s2 != ret) goto loc_20A78C;
    ret = ret & 7;
    if (2 != v1) goto loc_20A78C;
    ret = Interrupt_UpdateCounter(a0);
loc_20A788:
    ret = 2;
loc_20A78C:
    if (s7 != ret) {
        ret = ((unsigned)s7 < 3) ? 1 : 0;
        if (s7 != 1) {
            ret = 0;
            goto loc_20A810;
            }
            if (s7 != ret) {
                ret = 0;
                } else {
                ret = *(u8*)(ret + 0x6c08);
                goto loc_20A814;
                }
                ret = *(u16*)(ret + 0x6c08);
                goto loc_20A814;
        }
loc_20A810:
loc_20A814:
    return ret;
}

/* Function at 0x0020A844 - 0x0020AC30 */
u32 Interrupt_WriteIO(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a3, s0, s1, t0, t1;
    ret = ret | 0xef80;
    v1 = ((unsigned)a2 < 4) ? 1 : 0;
    a3 = a0 + ret;
    t1 = a1;
    if (v1 == 0) goto loc_20A8D0;
    a1 = a2 ^ 1;
    ret = a3 & 3;
    v1 = 0xffff;
    a0 = -4;
    t0 = 0xff;
    ret = ret << 3;
    if (a1 != 0) t0 = v1;
    a3 = a3 & a0;
    t0 = t0 << ret;
    ret = t1 << ret;
    a1 = 0x00500000;
    a1 = a1 + a3;
    a1 = *(u32*)(a1 + 0x6c08);
    v1 = ~(0 | t0);
    a0 = 0x74;
    t1 = ret & t0;
    a1 = a1 & v1;
    if (a3 == a0) {
        ret = t0 & ret;
        t1 = t1 | a1;
        if (ret != 0) goto loc_20A8D0;
        a1 = a1 & 0x80FFFFFF;
    }
    t1 = t1 | a1;
loc_20A8D0:
    ret = ((unsigned)a3 < 0x70) ? 1 : 0;
    if (-4 == 0) goto loc_20A998;
    v1 = a3 & 0xc;
    ret = 2;
    a0 = (unsigned)a3 >> 4;
    if (v1 == ret) goto loc_20A940;
    ret = ((signed)v1 < 3) ? 1 : 0;
    if (v1 != 0) {
        } else {
        if (v1 == 8) goto loc_20A940;
        if (v1 != ret) {
            } else {
            v1 = a0 << 4;
            ret = t1 & ret;
            __at = 0x00500000;
            __at = __at + v1;
            *(u32*)(__at + 0x6c08) = ret;
            goto loc_20AA68;
            loc_20A940:
            ret = a0 << 4;
            __at = 0x00500000;
            __at = __at + ret;
            *(u32*)(__at + 0x6c0c) = t1;
        } else {
            ret = (unsigned)t1 >> 0x18;
            v1 = a0 << 4;
            ret = ret & 1;
            __at = 0x00500000;
            __at = __at + v1;
            *(u32*)(__at + 0x6c10) = t1;
            if (ret != 0) {
                return Interrupt_StartChannel(a0);
            }
            return Interrupt_AcknowledgeChannel(a0);
            loc_20A998:
            v1 = 0x70;
            a0 = a3 & ret;
            ret = 0x74;
            if (a0 != v1) {
                if (a0 != ret) {
                    } else {
                    ret = 8 << 16;
                    v1 = 0x00500000;
                    ret = t1 | ret;
                    s0 = 0;
                    *(u32*)(v1 + 0x6c78) = ret;
                    a0 = s0;
                    do {
                        s0 = s0 + 1;
                        ret = Interrupt_StartChannel(a0);
                        ret = ((signed)s0 < 7) ? 1 : 0;
                        a0 = s0;
                    } while (ret != 0);
                    goto loc_20AA68;
                }
                s1 = 0x00500000;
                a0 = ~(0 | t1);
                v1 = s1 + 0x6c08;
                s0 = *(u32*)(v1 + 0x74);  /* PSX: gpr[25]/$t9 */
                a2 = 0x7F000000;
                ret = 0x80FFFFFF;
                a0 = s0 & a0;
                ret = t1 & ret;
                a0 = a0 & a2;
                a2 = (unsigned)s0 >> 0x1f;
                v1 = ((unsigned)0 < (unsigned)a0) ? 1 : 0;
                a1 = 0x7FFFFFFF;
                s0 = ret | a0;
                v1 = v1 << 0x1f;
                s0 = s0 & a1;
                s0 = s0 | v1;
                s0 = s0 & 0xFFFF7FFF;
                ret = s1 + 0x6c08;
                if ((signed)s0 < 0) goto loc_20AA60;
                ret = s1 + 0x6c08;
                if (a2 == 0) goto loc_20AA60;
                a0 = 3;
                ret = Compiler_GetCacheStatus();
                ret = s1 + 0x6c08;
                loc_20AA60:
                *(u32*)(ret + 0x74) = s0;
                }
                }
                loc_20AA68:
                }
    return ret;
        ret = 7 << 16;
        v1 = a1 + a0;
        ret = 0x0007FFFF;
        v1 = g_psx;
        if ((unsigned)ret >= (unsigned)v1) {
            ret = *(u32*)(v1 + 0x2d4);  /* counter_1 */
        } else {
            a0 = 0xE0800400;
            ret = a1 + a0;
            a2 = 0;
            if ((unsigned)ret >= 0x400) goto loc_20AB40;
            v1 = g_psx;
            ret = *(u32*)(v1 + 0x2dc);  /* counter_3 */
        }
        loc_20AB38:
        ret = ret + a1;
        a2 = ret + a0;
loc_20AB40:
    a3 = a3 + -1;
    a1 = a3 << 2;
    ret = 0x00FFFFFF;
    a2 = a2 - a1;
    a0 = t1 & ret;
    v1 = a2;
    a2 = a2 + 4;
    *(u32*)(v1) = ret;
    t1 = a0 - a1;
    if (a3 == 0) goto loc_20AB9C;
    if (a2 == 0) goto loc_20AB9C;
    do {
        a2 = a2 + 4;
        a3 = a3 + -1;
        *(u32*)(ret) = t1;
        v1 = a2 & 0xf;
        t1 = t1 + 4;
        if (a3 == 0) goto loc_20AB9C;
        ret = a2;
    } while (v1 != 0);
loc_20AB9C:
    v1 = v1 | 8;
    __asm("mmi2 v1, v1, v1");
    v1 = (u64)v1 << 32;
    a3 = a3 + -1;
    if ((unsigned)a3 >= 4) {
        do {
            __asm("mmi0 t0, t1, t1");
            __asm("mmi2 t0, t0, t0");
            a3 = a3 + -4;
            __asm("mmi1 t0, t0, v1");
            t1 = t1 + 0x10;
            __asm("ext t0, a2, 0, 1");
            a2 = a2 + 0x10;
            ret = ((unsigned)a3 < 4) ? 1 : 0;
        } while (ret == 0);
        a3 = a3 + -1;
    }
    ret = -1;
    if (a3 != 0) {
        v1 = -1;
        do {
            ret = a2;
            a2 = a2 + 4;
            a3 = a3 + -1;
            *(u32*)(ret) = t1;
            t1 = t1 + 4;
        } while (a3 != v1);
        ret = 0;
    }
    return ret;
}

/* Function at 0x0020AC30 - 0x0020ACC8 */
u32 Interrupt_ScheduleVBlank(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3, psx;
    psx = 0x00500000 + 0x6c08;
    v1 = 0x00FFFFFF;
    ret = ((PSX_State*)psx)->gpr[4];  /* gpr[4] */
    a0 = ret & v1;
    if (a0 != v1) {
        ((PSX_State*)psx)->hw_state[4] = 0;  /* hw_state[4] (store) */
            a0 = 2;
            return Interrupt_ProcessChannel(a0);
        }
    a3 = 0xac44;
    ((PSX_State*)psx)->hw_state[5] = 0;  /* hw_state[5] (store) */
    a1 = 0;
    a2 = 1;
    ret = GPU_ConfigureBuffer(a0, a1, a2, a3);
    ret = ((PSX_State*)psx)->hw_state[5];  /* hw_state[5] */
    a0 = 0xac44;
    __at = 0xac44;
    ret = __at + ret;
    a1 = (u32)Interrupt_AdvanceTiming;
    ((PSX_State*)psx)->hw_state[5] = ret;  /* hw_state[5] (store) */
    a2 = 0;
    ret = PSX_GetEventTimeout();
    ((PSX_State*)psx)->cop0[7] = ret;  /* COP0: DCIC (store) */
    return ret;
}

/* Function at 0x0020ACC8 - 0x0020AD00 */
u32 Interrupt_ResetCounter(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3;
    ret = GPU_FlushAndWait();
    *(u32*)(0x00506C08 + 0x20) = ret;
    *(u32*)(v1 + 0x124) = 0;
    *(u32*)(v1 + 0xb0) = ret;
    *(u32*)(v1 + 0x120) = 0;
    return ret;
}

/* Function at 0x0020AD00 - 0x0020ADF0 */
u32 Interrupt_UpdateCounter(u32 a0)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, psx;
    psx = 0x00500000 + 0x6c08;
    v1 = ((PSX_State*)psx)->hw_state[5];  /* hw_state[5] */
    ret = ((PSX_State*)psx)->hw_state[4];  /* hw_state[4] */
    if (v1 == ret) goto loc_20ADD4;
    ret = GPU_WaitForSync();
    ret = GPU_GetDisplayListID();
    v1 = ((PSX_State*)psx)->cop0[7];  /* COP0: DCIC */
    ((PSX_State*)psx)->gpr[4] = ret;  /* gpr[4] (store) */
    ((PSX_State*)psx)->cop0[8] = ret;  /* COP0: BadVaddr (store) */
    if (v1 == 0) goto loc_20ADD4;
    ret = GPU_IsBufferReady();
    if (ret == 0) goto loc_20ADD8;
    ret = GPU_ResetPendingCount();
    v1 = ((PSX_State*)psx)->hw_state[4];  /* hw_state[4] */
    s2 = ((PSX_State*)psx)->cop0[7];  /* COP0: DCIC */
    v1 = v1 + ret;
    s1 = ((PSX_State*)psx)->hw_state[5];  /* hw_state[5] */
    ((PSX_State*)psx)->hw_state[4] = v1;  /* hw_state[4] (store) */
    ret = PSX_GetElapsedTime();
    s0 = *(u32*)(s2 + 8);
    a0 = ((PSX_State*)psx)->cop0[7];  /* COP0: DCIC */
    s0 = s0 - ret;
    ret = PSX_CancelEvent(a0);
    ret = ((PSX_State*)psx)->hw_state[4];  /* hw_state[4] */
    s1 = s1 - s0;
    a1 = (u32)Interrupt_ProcessChannel;
    a2 = 2;
    v1 = ret - s1;
    a0 = 2;
    ((PSX_State*)psx)->hw_state[5] = ret;  /* hw_state[5] (store) */
    ((PSX_State*)psx)->cop0[7] = 0;  /* COP0: DCIC (store) */
    if ((signed)v1 <= 0) {
        ret = Interrupt_ProcessChannel(a0);
        goto loc_20ADD8;
    }
    a0 = v1;
    ret = PSX_GetEventTimeout();
    ((PSX_State*)psx)->cop0[7] = ret;  /* COP0: DCIC (store) */
loc_20ADD4:
loc_20ADD8:
    return ret;
}

/* Function at 0x0020ADF0 - 0x0020AED8 */
u32 Interrupt_AdvanceTiming(void)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a0, a1, a2, a3, s0, psx;
    ret = GPU_GetDisplayListID();
    psx = 0x00500000 + 0x6c08;
    ((PSX_State*)psx)->gpr[4] = ret;  /* gpr[4] (store) */
    ((PSX_State*)psx)->cop0[8] = ret;  /* COP0: BadVaddr (store) */
    ret = GPU_IsBufferReady();
    s0 = ret;
    ret = GPU_ResetPendingCount();
    v1 = ((PSX_State*)psx)->hw_state[4];  /* hw_state[4] */
    a1 = (u32)Interrupt_AdvanceTiming;
    a2 = 0;
    v1 = v1 + ret;
    ((PSX_State*)psx)->hw_state[4] = v1;  /* hw_state[4] (store) */
    if (s0 != 0) {
        ret = ((PSX_State*)psx)->hw_state[5];  /* hw_state[5] */
        ((PSX_State*)psx)->hw_state[5] = v1;  /* hw_state[5] (store) */
        ret = v1 - ret;
        a0 = ret;
        if ((signed)ret <= 0) {
            a0 = 2;
            return Interrupt_ProcessChannel(a0);
            }
            ret = ((PSX_State*)psx)->hw_state[5];  /* hw_state[5] */
            a0 = v1 - ret;
            if ((((signed)a0 < 0) ? 1 : 0) != 0) a0 = 0;
            __at = 0xac44;
            a0 = __at + a0;
            ret = ret + a0;
            ((PSX_State*)psx)->hw_state[5] = ret;  /* hw_state[5] (store) */
            PSX_GetEventTimeout();
            a0 = 0xac44;
            ((PSX_State*)psx)->cop0[7] = ret;  /* COP0: DCIC (store) */
            return GPU_AddPendingCount(a0);
        }
    a2 = 2;
    a1 = (u32)Interrupt_ProcessChannel;
    ret = PSX_GetEventTimeout();
    ((PSX_State*)psx)->cop0[7] = ret;  /* COP0: DCIC (store) */
    return ret;
}

/* Function at 0x0020AED8 - 0x0020AEF8 */
u32 Interrupt_SetCallback(u32 a0, u32 a1)
{
    u32 ret;
    ret = ret << 3;
    __at = 0x00500000;
    __at = __at + ret;
    *(u32*)(__at + 0x6c80) = a1;
    return ret;
}

/* Function at 0x0020AEF8 - 0x0020AF68 */
u32 Interrupt_ResetAll(void)
{
    /* Stack frame: 32 bytes */
    u32 ret, a0, a1, a2, a3, s0, i, s2;
    s2 = 0x00500000;
    ret = s2 + 0x6c08;
    s0 = ret + 0x88;
    i = 0;
    do {
        a0 = i;
        i = i + 1;
        ret = Interrupt_AcknowledgeChannel(a0);
        *(u32*)(s0 + -8) = 0;
        ret = ((signed)i < 7) ? 1 : 0;
        *(u32*)(s0 + -4) = 0;
        *(u32*)(s0) = 0;
        s0 = s0 + 0x18;
    } while (ret != 0);
    a0 = s2 + 0x6c08;
    a1 = 0;
    a2 = 0x78;
    return Libc_Memset(a0, a1, a2);
}
