#ifndef POPS_TYPES_H
#define POPS_TYPES_H

/* POPS.ELF Decompiled Source - PS1 Emulator for PS2 */
/* Auto-generated by POPS Decompiler */

typedef unsigned char u8;
typedef signed char s8;
typedef unsigned short u16;
typedef signed short s16;
typedef unsigned int u32;
typedef signed int s32;
typedef unsigned long long u64;
typedef signed long long s64;
#ifdef __GNUC__
typedef unsigned __int128 u128;
typedef signed __int128 s128;
#else
/* IntelliSense/MSVC fallback - __int128 not supported */
typedef u64 u128;
typedef s64 s128;
#endif

/* EE-specific macros */
#ifdef __GNUC__
#define SYSCALL()           __asm volatile("syscall")
#define SYNC()              __asm volatile("sync")
#define EI()                __asm volatile("ei")
#define DI()                __asm volatile("di")
#define BREAK()             __asm volatile("break")
#define CACHE(op, addr)     __asm volatile("cache " #op ", %0" :: "m"(addr))
#else
#define SYSCALL()           ((void)0)
#define SYNC()              ((void)0)
#define EI()                ((void)0)
#define DI()                ((void)0)
#define BREAK()             ((void)0)
#define CACHE(op, addr)     ((void)0)
/* Make inline asm a no-op for IntelliSense */
#define __asm(x)            ((void)0)
#endif
#define COP0_REG(n)         __cop0_reg[n]
#define FPU_REG(n)          __fpu_reg[n]
#define FPU_F(n)            (*(float*)&__fpu_reg[n])  /* float interpretation */
#define FPU_D(n)            (*(double*)&__fpu_reg[n]) /* double interpretation (uses fN and fN+1) */

/* Unaligned 64-bit load/store macros (ldl/ldr, sdl/sdr) */
#ifdef __GNUC__
#define LOAD_DWORD_LEFT(addr)        __ldl(addr)
#define LOAD_DWORD_RIGHT(addr)       __ldr(addr)
#define STORE_DWORD_LEFT(addr, val)  __sdl(addr, val)
#define STORE_DWORD_RIGHT(addr, val) __sdr(addr, val)
#else
#define LOAD_DWORD_LEFT(addr)        (addr)
#define LOAD_DWORD_RIGHT(addr)       (addr)
#define STORE_DWORD_LEFT(addr, val)  ((void)(addr), (void)(val))
#define STORE_DWORD_RIGHT(addr, val) ((void)(addr), (void)(val))
#endif

/* Indirect function call cast (for MIPS jalr through register) */
typedef u32 (*func_ptr_t)(u32, u32, u32, u32);
#define CALL_INDIRECT(addr)  ((func_ptr_t)(addr))

/* FPU register indices for FPU_REG() macro */
#define f0  0
#define f1  1
#define f2  2
#define f3  3
#define f4  4
#define f5  5
#define f6  6
#define f7  7
#define f8  8
#define f9  9
#define f10 10
#define f11 11
#define f12 12
#define f13 13
#define f14 14
#define f15 15
#define f16 16
#define f17 17
#define f18 18
#define f19 19
#define f20 20
#define f21 21
#define f22 22
#define f23 23
#define f24 24
#define f25 25
#define f26 26
#define f27 27
#define f28 28
#define f29 29
#define f30 30
#define f31 31

#ifdef __GNUC__
#define LOAD_WORD_LEFT(addr)        __lwl(addr)
#define LOAD_WORD_RIGHT(addr)       __lwr(addr)
#define STORE_WORD_LEFT(addr, val)  __swl(addr, val)
#define STORE_WORD_RIGHT(addr, val) __swr(addr, val)
#else
#define LOAD_WORD_LEFT(addr)        (addr)
#define LOAD_WORD_RIGHT(addr)       (addr)
#define STORE_WORD_LEFT(addr, val)  ((void)(addr), (void)(val))
#define STORE_WORD_RIGHT(addr, val) ((void)(addr), (void)(val))
#endif

#ifdef __GNUC__
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else
#define likely(x)   (x)
#define unlikely(x) (x)
#endif

/* Hardware register access */
#define HW_REG8(addr)   (*(volatile u8*)(addr))
#define HW_REG16(addr)  (*(volatile u16*)(addr))
#define HW_REG32(addr)  (*(volatile u32*)(addr))
#define HW_REG64(addr)  (*(volatile u64*)(addr))
#define HW_REG128(addr) (*(volatile u128*)(addr))

/* PS2 EE Hardware Registers */
#define EE_D_CTRL    HW_REG32(0x1000E000)
#define EE_D_STAT    HW_REG32(0x1000E010)
#define EE_INTC_STAT HW_REG32(0x1000F000)
#define EE_INTC_MASK HW_REG32(0x1000F010)
#define EE_GS_CSR    HW_REG64(0x12001000)
#define EE_GS_IMR    HW_REG64(0x12001010)

/* PS1 Memory Map (emulated) */
#define PSX_RAM_SIZE     0x200000   /* 2MB main RAM */
#define PSX_BIOS_SIZE    0x80000    /* 512KB BIOS ROM */
#define PSX_SCRATCH_SIZE 0x400      /* 1KB scratchpad */

/* PS1 I/O Port Base Addresses (emulated hardware registers) */
#define PSX_IO_BASE       0x1F800000  /* PS1 hardware I/O base */
#define PSX_MEM_CTRL      0x1F801004  /* Memory Control registers */
#define PSX_SIO_BASE      0x1F801040  /* Serial I/O: Joy/Memcard (32 bytes) */
#define PSX_IRQ_BASE      0x1F801070  /* Interrupt Controller: I_STAT/I_MASK (16 bytes) */
#define PSX_DMA_BASE      0x1F801080  /* DMA Controller: 7 channels (128 bytes) */
#define PSX_COUNTER_BASE  0x1F801100  /* Counter/Timer registers (48 bytes) */
#define PSX_CDROM_BASE    0x1F801800  /* CD-ROM Controller (16 bytes) */
#define PSX_GPU_BASE      0x1F801810  /* GPU: GP0 (data) / GP1 (control) (16 bytes) */
#define PSX_MDEC_BASE     0x1F801820  /* MDEC: Motion Decoder (8 bytes) */
#define PSX_MDEC_BASE_ADDR 0x1F801820 /* MDEC command/data port */
#define PSX_SPU_BASE      0x1F801C00  /* SPU: Sound Processing Unit (608 bytes) */
#define PSX_EXP2_END      0x1F801F5A  /* Expansion 2 region end */

/* Emulator interrupt callback slots (Interrupt_SetCallback indices) */
#define IRQ_CB_VBLANK   0   /* VBlank interrupt handler */
#define IRQ_CB_GPU      1   /* GPU interrupt handler */
#define IRQ_CB_COUNTER  2   /* Counter/timer VBlank handler */
#define IRQ_CB_CDROM    3   /* CD-ROM interrupt handler */
#define IRQ_CB_SPU      4   /* SPU DMA interrupt handler */
#define IRQ_CB_SIO      5   /* Serial I/O interrupt handler */
#define IRQ_CB_DMA      6   /* DMA completion handler */

/* PSX DMA Channel Indices */
#define PSX_DMA_MDEC_IN   0   /* MDEC decoder input */
#define PSX_DMA_MDEC_OUT  1   /* MDEC decoder output */
#define PSX_DMA_GPU       2   /* GPU linked list / image transfer */
#define PSX_DMA_CDROM     3   /* CD-ROM disc reading */
#define PSX_DMA_SPU       4   /* SPU sound data */
#define PSX_DMA_PIO       5   /* Parallel I/O (expansion port) */
#define PSX_DMA_OTC       6   /* Ordering table clear (reverse) */

/* Emulator data structure base addresses */
#define PSX_DMA_CHANNELS   0x00506D30  /* DMA_Channel array (7 channels, 0x20 each) */
#define PSX_GPU_HANDLERS   0x00506D90  /* GPU_HandlerSlot array (2 slots, 0x1C each) */
#define PSX_DMA_STATE      0x00506C08  /* DMA/interrupt state base */
#define PSX_IRQ_STAT_ADDR  0x00506C00  /* IRQ status register mirror */
#define PSX_IRQ_MASK_ADDR  0x00506C04  /* IRQ mask register mirror */
#define PSX_SERIAL_PORTS   0x00597CC0  /* Serial_Port array (2 ports) */
#define PSX_SPU_STATE      0x00850970  /* SPU_State struct */
#define PSX_JIT_SLOTS      0x0024AA00  /* JIT_CacheSlot array (10 slots) */

/* Major data region base addresses */
#define SYS_DATA_BASE      0x00860000  /* System/boot data region */
#define SYS_CONFIG_BASE    0x004F0000  /* System configuration / SIF state */
#define SUBSYS_DATA_BASE   0x005A0000  /* Subsystem data (CDROM/MDEC/serial) */
#define JIT_CODE_CACHE     0x00250000  /* JIT compiled code cache */
#define SPU_SAMPLE_BUF     0x007AB980  /* SPU sample buffer */
#define SERIAL_DATA_BASE   0x00590000  /* Serial controller data area */
#define CDROM_DATA_BASE    0x005B0000  /* CD-ROM data area */
#define CDROM_SECTOR_BUF   0x00830000  /* CD-ROM sector buffer */

/*
 * MIPS R5900 register variables.
 * The decompiled code uses MIPS register names directly as local variables.
 * In a real recompile these would be proper locals; for now they are globals
 * so the decompiled pseudocode compiles without errors.
 *
 * Naming: ret=v0, v1, a0-a3, t0-t9, s0-s7, __gp, __sp, __fp, __ra, __at
 */
extern u32 ret;            /* $v0 - return value / general result */
extern u32 v1;             /* $v1 */
extern u32 a0, a1, a2, a3; /* $a0-$a3 - function arguments */
extern u32 t0, t1, t2, t3; /* $t0-$t3 - temporaries (caller-saved) */
extern u32 t4, t5, t6, t7; /* $t4-$t7 */
extern u32 s0, s1, s2, s3; /* $s0-$s3 - saved (callee-saved) */
extern u32 s4, s5, s6, s7; /* $s4-$s7 */
extern u32 t8, t9;         /* $t8-$t9 */
extern u32 __at;           /* $at - assembler temporary */
extern u32 __gp;           /* $gp - global pointer */
extern u32 __sp;           /* $sp - stack pointer */
extern u32 __fp;           /* $fp - frame pointer */
extern u32 __ra;           /* $ra - return address */
extern u32 __k0, __k1;     /* $k0-$k1 - kernel temporaries */

extern u32 HI, LO;         /* HI/LO multiply-divide registers */
extern u32 ac0, ac2, ac3;  /* EE multimedia accumulator registers (pipeline 0/1) */
extern u64 HI_LO;          /* Combined HI:LO for 64-bit multiply results */

extern u32 __cop0_reg[32]; /* COP0 registers */
extern u32 __fpu_reg[32];  /* FPU registers (as u32 bit patterns) */
extern u32 __fpu_cc;       /* FPU condition code flag (c.lt.s result) */

/*
 * ==========================================================================
 *  PS1 GTE (Geometry Transformation Engine) Register Layout
 *  Verified from PSX_ResetCPUState zeroing loops and GTE command code.
 * ==========================================================================
 */

/* GTE Data Registers (cop2d[0..31]) - 128 bytes at PSX_State+0x1B0 */
typedef struct {
    /* Vectors V0, V1, V2 (input vertices/normals) */
    s16  vxy0[2];       /* 0x00: V0 X,Y (packed) */
    s16  vz0;           /* 0x04: V0 Z */
    s16  _pad0;
    s16  vxy1[2];       /* 0x08: V1 X,Y */
    s16  vz1;           /* 0x0C: V1 Z */
    s16  _pad1;
    s16  vxy2[2];       /* 0x10: V2 X,Y */
    s16  vz2;           /* 0x14: V2 Z */
    s16  _pad2;
    u8   rgbc[4];       /* 0x18: Color + code (R,G,B,Code) */
    u16  otz;           /* 0x1C: Average Z value (for ordering table) */
    u16  _pad3;
    /* Intermediate registers */
    s32  ir0;           /* 0x20: Interpolation factor */
    s32  ir1;           /* 0x24: Intermediate result 1 */
    s32  ir2;           /* 0x28: Intermediate result 2 */
    s32  ir3;           /* 0x2C: Intermediate result 3 */
    /* Screen XY FIFO (output from RTPS/RTPT) */
    s32  sxy0;          /* 0x30: Screen X,Y 0 (packed s16+s16) */
    s32  sxy1;          /* 0x34: Screen X,Y 1 */
    s32  sxy2;          /* 0x38: Screen X,Y 2 */
    s32  sxyp;          /* 0x3C: Screen X,Y projection result */
    /* Screen Z FIFO */
    u32  sz0;           /* 0x40: Screen Z 0 */
    u32  sz1;           /* 0x44: Screen Z 1 */
    u32  sz2;           /* 0x48: Screen Z 2 */
    u32  sz3;           /* 0x4C: Screen Z 3 */
    /* Color FIFO (output from NCS/NCDS/etc.) */
    u32  rgb0;          /* 0x50: Color result 0 (R,G,B,Code packed) */
    u32  rgb1;          /* 0x54: Color result 1 */
    u32  rgb2;          /* 0x58: Color result 2 */
    u32  _reserved;     /* 0x5C: Reserved */
    /* Accumulator registers */
    s32  mac0;          /* 0x60: MAC0 (accumulator for perspective) */
    s32  mac1;          /* 0x64: MAC1 */
    s32  mac2;          /* 0x68: MAC2 */
    s32  mac3;          /* 0x6C: MAC3 */
    /* Color conversion / leading zero count */
    u32  irgb;          /* 0x70: Color conversion input */
    u32  orgb;          /* 0x74: Color conversion output */
    s32  lzcs;          /* 0x78: Leading zero count source */
    u32  lzcr;          /* 0x7C: Leading zero count result */
} GTE_DataRegs;         /* 128 bytes */

/* GTE Control Registers (cop2c[0..31]) - 128 bytes at PSX_State+0x230 */
typedef struct {
    /* Rotation matrix (3x3, packed s16 pairs) */
    s16  rt[2];         /* 0x80: R11, R12 */
    s16  rt2[2];        /* 0x84: R13, R21 */
    s16  rt3[2];        /* 0x88: R22, R23 */
    s16  rt4[2];        /* 0x8C: R31, R32 */
    s16  rt5;           /* 0x90: R33 */
    s16  _pad0;
    /* Translation vector */
    s32  trx;           /* 0x94: Translation X */
    s32  try_;          /* 0x98: Translation Y */
    s32  trz;           /* 0x9C: Translation Z */
    /* Light source direction matrix (3x3, packed s16 pairs) */
    s16  l[2];          /* 0xA0: L11, L12 */
    s16  l2[2];         /* 0xA4: L13, L21 */
    s16  l3[2];         /* 0xA8: L22, L23 */
    s16  l4[2];         /* 0xAC: L31, L32 */
    s16  l5;            /* 0xB0: L33 */
    s16  _pad1;
    /* Background color */
    s32  rbk;           /* 0xB4: Red background */
    s32  gbk;           /* 0xB8: Green background */
    s32  bbk;           /* 0xBC: Blue background */
    /* Light color matrix (3x3, packed s16 pairs) */
    s16  lc[2];         /* 0xC0: LR1, LR2 */
    s16  lc2[2];        /* 0xC4: LR3, LG1 */
    s16  lc3[2];        /* 0xC8: LG2, LG3 */
    s16  lc4[2];        /* 0xCC: LB1, LB2 */
    s16  lc5;           /* 0xD0: LB3 */
    s16  _pad2;
    /* Far color */
    s32  rfc;           /* 0xD4: Red far color */
    s32  gfc;           /* 0xD8: Green far color */
    s32  bfc;           /* 0xDC: Blue far color */
    /* Screen offset and projection */
    s32  ofx;           /* 0xE0: Screen offset X (fixed 16.16) */
    s32  ofy;           /* 0xE4: Screen offset Y (fixed 16.16) */
    u16  h;             /* 0xE8: Projection plane distance */
    s16  _pad3;
    s16  dqa;           /* 0xEC: Depth queing parameter A (fixed 8.8) */
    s16  _pad4;
    s32  dqb;           /* 0xF0: Depth queing parameter B (fixed 8.24) */
    /* Z scale factors */
    s16  zsf3;          /* 0xF4: Z scale factor 3 */
    s16  _pad5;
    s16  zsf4;          /* 0xF8: Z scale factor 4 */
    s16  _pad6;
    u32  flag;          /* 0xFC: Error/overflow flags */
} GTE_CtrlRegs;         /* 128 bytes */

/*
 * Note on offsets: GTE_CtrlRegs fields list the offset from the GTE data
 * base (PSX_State+0x1B0). In the code, GTE commands receive a pointer to
 * GTE_DataRegs and access control registers at data_ptr + 0x80.
 */

/*
 * ==========================================================================
 *  PS1 R3000A COP0 Register Indices
 *  Array at PSX_State+0x90, indexed as cop0[n].
 * ==========================================================================
 */
#define COP0_BPC     3   /* Breakpoint PC */
#define COP0_BDA     5   /* Breakpoint Data Address */
#define COP0_TAR     6   /* Target Address */
#define COP0_DCIC    7   /* Debug and Cache Invalidate Control */
#define COP0_BADVADDR 8  /* Bad Virtual Address */
#define COP0_BDAM    9   /* Data Address Mask */
#define COP0_BPCM   11   /* Execute Address Mask */
#define COP0_SR     12   /* Status Register (offset 0xC0) */
#define COP0_CAUSE  13   /* Cause Register (offset 0xC4) */
#define COP0_EPC    14   /* Exception PC (offset 0xC8) */
#define COP0_PRID   15   /* Processor ID (offset 0xCC, set to 0x200 = R3000A) */

/* Status Register bits */
#define SR_IEc      (1 << 0)   /* Interrupt Enable (current) */
#define SR_KUc      (1 << 1)   /* Kernel/User mode (current) */
#define SR_IEp      (1 << 2)   /* Interrupt Enable (previous) */
#define SR_KUp      (1 << 3)   /* Kernel/User (previous) */
#define SR_IEo      (1 << 4)   /* Interrupt Enable (old) */
#define SR_KUo      (1 << 5)   /* Kernel/User (old) */
#define SR_IM_MASK  0x0000FF00 /* Interrupt Mask (bits 8-15) */
#define SR_BEV      (1 << 22)  /* Boot Exception Vectors */

/*
 * ==========================================================================
 *  Main PSX Emulator State Structure
 *  Pointed to by *(u32*)(__gp - 0x7F60).
 *  Layout verified from PSX_ResetCPUState zeroing pattern and cross-
 *  referenced with GTE_Init, PSX_CheckPendingIRQ, counter/interrupt code.
 * ==========================================================================
 */
typedef struct {
    /* 0x000: CPU core state */
    u32  pc;                /* 0x000: Program Counter (set to 0xBFC00000 on reset) */
    u32  next_pc;           /* 0x004: Next PC / branch delay slot target */
    u32  hi;                /* 0x008: HI register (mult/div result high) */
    u32  lo;                /* 0x00C: LO register (mult/div result low) */

    /* 0x010: R3000A General Purpose Registers */
    u32  gpr[32];           /* 0x010-0x08F: GPR[0]=$zero .. GPR[31]=$ra */

    /* 0x090: COP0 Registers (cop0[0..31]) */
    u32  cop0[32];          /* 0x090-0x10F: COP0[12]=SR@0xC0, COP0[13]=Cause@0xC4 */

    /* 0x110: Additional CPU / hardware emulation state */
    u32  hw_state[32];      /* 0x110-0x18F: Zeroed on reset, partially mapped:
                               0x120 = GPU pending command
                               0x124 = GPU status accumulator */

    /* 0x190: Execution handler state (used by r3000.c) */
    u32  exec_handlers[8];  /* 0x190-0x1AF: Exception vector handlers or
                               memory region function pointers */

    /* 0x1B0: GTE Data Registers (cop2d[0..31]) */
    GTE_DataRegs gte_data;  /* 0x1B0-0x22F */

    /* 0x230: GTE Control Registers (cop2c[0..31]) */
    union {
        GTE_CtrlRegs gte_ctrl_s;
        u32 gte_ctrl[32];   /* indexed access for COP2 ctrl register ops */
    };  /* 0x230-0x2AF */

    /* 0x2B0: GTE Function Dispatch Pointers (set by GTE_Init) */
    u32  gte_read_data;     /* 0x2B0: Read GTE data register handler */
    u32  gte_read_ctrl;     /* 0x2B4: Read GTE control register handler */
    u32  gte_write_data;    /* 0x2B8: Write GTE data register handler */
    u32  gte_write_ctrl;    /* 0x2BC: Write GTE control register handler */
    u32  gte_execute;       /* 0x2C0: GTE command execution handler */

    /* 0x2C4: Execution control */
    u32  cop2_insn_count;   /* 0x2C4: COP2 instruction batch count */
    u32  field_2C8;         /* 0x2C8: Reserved / padding */
    u32  irq_pending;       /* 0x2CC: Interrupt pending flag (1 = pending) */

    /* 0x2D0: R3000A Memory Region Base Pointers (set by R3000_Init) */
    u32  ram_base;          /* 0x2D0: PS1 RAM base (2MB, cleared on reset) */
    u32  bios_base;         /* 0x2D4: PS1 BIOS/ROM base (512KB) */
    u32  scratch_base;      /* 0x2D8: PS1 scratchpad base (1KB, cleared on reset) */
    u32  hw_regs_base;      /* 0x2DC: PS1 hardware regs / I/O (1KB, cleared on reset) */
    u32  mem_ctrl[3];       /* 0x2E0-0x2E8: Memory control / execution state */

    /* 0x2EC-0x31F: Extended emulator state (reserved/unknown) */
    u8   _extended[0x320 - 0x2EC];  /* padding to GPU state */

    /* 0x320-0x39F: GPU Display/Rendering State
       These fields are accessed in ui.c for GPU display list management. */
    float gpu_depth_bias;       /* 0x320: GPU depth bias / Z offset */
    u8   _gpu_pad1[0x330 - 0x324];

    /* GPU transformation matrices (4x float each) */
    float gpu_matrix[4];        /* 0x330-0x33C: GPU model matrix */
    float gpu_viewport[4];      /* 0x340-0x34C: GPU viewport matrix */
    u8   _gpu_pad2[0x35E - 0x350];

    /* Display configuration */
    u16  disp_x_start;          /* 0x35E: Display area X start */
    u16  disp_y_start;          /* 0x360: Display area Y start */
    u8   _gpu_pad3[0x364 - 0x362];
    u16  disp_x_end;            /* 0x364: Display area X end */
    u8   _gpu_pad4[0x368 - 0x366];
    u16  disp_width;            /* 0x368: Display width */
    u16  disp_height;           /* 0x36A: Display height */
    u32  gpu_ot_head;           /* 0x36C: GPU ordering table head */
    u8   _gpu_pad5[0x37C - 0x370];

    /* GPU DMA and VRAM */
    u32  gpu_packet_list;       /* 0x37C: GPU display list / packet list */
    u8   _gpu_pad6[0x384 - 0x380];
    u32  gpu_vram_ptr;          /* 0x384: GPU VRAM pointer */
    u32  gpu_dma_ctrl;          /* 0x388: GPU DMA control */
    u32  gpu_dma_size;          /* 0x38C: GPU DMA transfer size */
    u32  gpu_draw_env[3];       /* 0x390-0x398: GPU drawing environment */
} PSX_State;

/*
 * ==========================================================================
 *  Global Pointer Variables (accessed via __gp + offset)
 *  These are individual globals, NOT part of PSX_State.
 * ==========================================================================
 *
 *  __gp - 0x7F60: PSX_State* g_psx    (main emulator state pointer)
 *  __gp - 0x7F58: u32 g_running       (emulator running flag)
 *  __gp - 0x7F54: u32 g_bios_version  (cached BIOS version)
 *  __gp - 0x7F4C: u32 g_init_flag     (initialization state)
 *  __gp - 0x7F10: u32 g_irq_stat      (interrupt status shadow)
 *  __gp - 0x7F0C: u32 g_irq_mask      (interrupt mask shadow)
 *  __gp - 0x7F00: u32 g_counter_state (counter subsystem state)
 *  __gp - 0x77EC: u32 g_target_cycles (target cycle count)
 *  __gp - 0x77E8: float g_time_scale  (timing scale factor)
 *  __gp - 0x77CC: u32 g_jit_flag      (JIT enable flag)
 *  __gp - 0x77C8: u32 g_jit_cache     (JIT code cache pointer)
 *  __gp - 0x77C4: u32 g_jit_state     (JIT compiler state - heavy R/W)
 *  __gp - 0x77C0: u32 g_compiler_irq0 (compiler/interrupt shared)
 *  __gp - 0x77BC: u32 g_compiler_irq1 (compiler/interrupt shared)
 *  __gp - 0x77B8: u32 g_gpu_state     (GPU state flag)
 *  __gp - 0x77B0: u32 g_serial_ctrl0  (serial control 0)
 *  __gp - 0x77A8: u32 g_serial_ctrl1  (serial control 1)
 *  __gp - 0x77A0: u32 g_serial_ctrl2  (serial control 2)
 *  __gp - 0x779C: u32 g_memcard_flag  (memcard state flag)
 *  __gp - 0x7798: u32 g_memcard_ctrl0 (memcard/serial shared)
 *  __gp - 0x7794: u32 g_memcard_ctrl1 (memcard/serial shared)
 *  __gp - 0x7790: u32 g_serial_base   (serial port base address)
 *  __gp - 0x7788: u32 g_mdec_ctrl     (MDEC control state)
 *  __gp - 0x7768: u32 g_cdrom_ctrl0   (CDROM control)
 *  __gp - 0x7764: u32 g_cdrom_ctrl1   (CDROM control)
 *  __gp - 0x7760: u32 g_cdrom_ctrl2   (CDROM control)
 *  __gp - 0x775C: u32 g_cdrom_ctrl3   (CDROM control)
 *  __gp - 0x7758: u32 g_spu_ctrl0     (SPU control)
 *  __gp - 0x7754: u32 g_spu_ctrl1     (SPU control)
 *  __gp - 0x7750: u32 g_spu_ctrl2     (SPU control)
 *  __gp - 0x774C: u32 g_spu_ctrl3     (SPU control)
 *  __gp - 0x7748: u32 g_spu_ctrl4     (SPU control)
 *  __gp - 0x7740: u32 g_spu_ctrl5     (SPU control)
 *  __gp - 0x7738: u32 g_spu_ctrl6     (SPU control)
 */

/* GP-relative global variable externs */
extern PSX_State *g_psx;         /* __gp - 0x7F60: main emulator state pointer */
extern u32 g_running;            /* __gp - 0x7F58: emulator running flag */
extern u32 g_bios_version;       /* __gp - 0x7F54: cached BIOS version */
extern u32 g_init_flag;          /* __gp - 0x7F4C: initialization state */
extern u32 g_irq_stat;           /* __gp - 0x7F10: interrupt status shadow */
extern u32 g_irq_mask;           /* __gp - 0x7F0C: interrupt mask shadow */
extern u32 g_counter_state;      /* __gp - 0x7F00: counter subsystem state */
extern u32 g_target_cycles;      /* __gp - 0x77EC: target cycle count */
extern u32 g_time_scale;         /* __gp - 0x77E8: timing scale factor */
extern u32 g_time_accum;         /* __gp - 0x77E4: timing accumulator */
extern u32 g_cycle_base;         /* __gp - 0x77E0: cycle base counter */
extern u32 g_jit_flag;           /* __gp - 0x77CC: JIT enable flag */
extern u32 g_jit_cache;          /* __gp - 0x77C8: JIT code cache pointer */
extern u32 g_jit_state;          /* __gp - 0x77C4: JIT compiler state */
extern u32 g_compiler_irq0;      /* __gp - 0x77C0: compiler/interrupt shared */
extern u32 g_compiler_irq1;      /* __gp - 0x77BC: compiler/interrupt shared */
extern u32 g_gpu_state;          /* __gp - 0x77B8: GPU state flag */
extern u32 g_gpu_ctrl;           /* __gp - 0x77B4: GPU control */
extern u32 g_serial_ctrl0;       /* __gp - 0x77B0: serial control 0 */
extern u32 g_serial_ctrl2;       /* __gp - 0x77A0: serial control 2 */
extern u32 g_memcard_flag;       /* __gp - 0x779C: memcard state flag */
extern u32 g_memcard_ctrl0;      /* __gp - 0x7798: memcard/serial shared */
extern u32 g_memcard_ctrl1;      /* __gp - 0x7794: memcard/serial shared */
extern u32 g_serial_base;        /* __gp - 0x7790: serial port base address */
extern u32 g_mdec_ctrl;          /* __gp - 0x7788: MDEC control state */
extern u32 g_cdrom_ctrl0;        /* __gp - 0x7768: CDROM control */
extern u32 g_cdrom_ctrl1;        /* __gp - 0x7764: CDROM control */
extern u32 g_cdrom_ctrl2;        /* __gp - 0x7760: CDROM control */
extern u32 g_cdrom_ctrl3;        /* __gp - 0x775C: CDROM control */
extern u32 g_spu_ctrl0;          /* __gp - 0x7758: SPU control */
extern u32 g_spu_ctrl1;          /* __gp - 0x7754: SPU control */
extern u32 g_spu_ctrl2;          /* __gp - 0x7750: SPU control */
extern u32 g_spu_ctrl3;          /* __gp - 0x774C: SPU control */
extern u32 g_spu_ctrl4;          /* __gp - 0x7748: SPU control */
extern u32 g_spu_ctrl6;          /* __gp - 0x7738: SPU control */

/* Additional globals found in source (not from GP_GLOBALS mapping) */
extern u32 g_bios_ver2;          /* secondary BIOS version */
extern u32 g_counter_base;       /* counter base address */
extern u32 g_hw_init_flag;       /* hardware init flag */
extern u32 g_hw_reg_base;        /* hardware register base */
extern u32 g_irq_stat2;          /* secondary IRQ status */
extern u32 g_irq_mask2;          /* secondary IRQ mask */
extern u32 g_event_active_list;  /* active event list head */
extern u32 g_event_free_list;    /* free event list head */
extern u32 g_event_pending;      /* pending events count */
extern u32 g_event_timeout;      /* event timeout value */
extern u32 g_cdrom_dma_flag;     /* CDROM DMA flag */
extern u32 g_cdrom_state0;       /* CDROM state 0 */
extern u32 g_cdrom_state1;       /* CDROM state 1 */
extern u32 g_cdrom_state2;       /* CDROM state 2 */
extern u32 g_cdrom_state3;       /* CDROM state 3 */
extern u32 g_mdec_state1;        /* MDEC state 1 */
extern u32 g_mdec_state2;        /* MDEC state 2 */
extern u32 g_mdec_state3;        /* MDEC state 3 */
extern u32 g_mdec_state4;        /* MDEC state 4 */
extern u32 g_mdec_state5;        /* MDEC state 5 */
extern u32 g_mdec_state6;        /* MDEC state 6 */
extern u32 g_spu_state0;         /* SPU state 0 */
extern u32 g_spu_state1;         /* SPU state 1 */

/*
 * ==========================================================================
 *  PS1 DMA Channel State (emulated)
 *  7 DMA channels, each 0x20 bytes.
 *  Base at 0x00506D30, indexed as channel * 0x20.
 *  Verified from DMA_StartTransfer, DMA_CalcProgress, DMA_ScheduleEvent,
 *  DMA_ReadRegister, DMA_WriteRegister field access patterns.
 * ==========================================================================
 */
typedef struct {
    u32  chcr;           /* 0x00: Channel Control Register
                                  bit 0x10 = transfer active
                                  bit 0x40 = cache flush needed
                                  bit 0x08 = block mode */
    u32  bcr;            /* 0x04: Block Control Register (block size/count) */
    u32  blocks_done;    /* 0x08: Progress - blocks transferred so far */
    u32  elapsed;        /* 0x0C: Accumulated elapsed cycles */
    u32  start_time;     /* 0x10: Timestamp from PSX_GetElapsedTime */
    u32  speed_shift;    /* 0x14: Timing shift value for speed calculation
                                  set based on channel config (bits 8-9 of CHCR) */
    u32  event_handle;   /* 0x18: Scheduled event (from PSX_GetEventTimeout,
                                  cancelled with PSX_CancelEvent on restart) */
    u32  madr;           /* 0x1C: Memory Address Register (DMA base addr,
                                  passed to Compiler_SetCacheFlushFlag) */
} DMA_Channel;           /* 0x20 = 32 bytes */

/* DMA subsystem state base addresses (from DMA_RegisterIO) */
#define DMA_STATE_BASE    0x00506C08  /* Full DMA state, 0x128 bytes, zeroed on init */
#define DMA_CHANNEL_BASE  0x00506D30  /* Channel table (7 channels * 0x20) */
#define DMA_NUM_CHANNELS  7

/*
 * ==========================================================================
 *  PS1 Serial Port State (emulated)
 *  Two ports (port 0 = controller, port 1 = memcard).
 *  Base at 0x00597CC0, each port 0x1C bytes.
 *  Verified from Serial_Reset (memset 0x1C) and field access patterns
 *  in Serial_ProcessCommand, Serial_ReadRegister, Serial_WriteRegister.
 *
 *  PS1 SIO registers: 0x1F801040 (data) through 0x1F80105E (baud)
 * ==========================================================================
 */
typedef struct {
    u32  data;           /* 0x00: SIO_DATA - transmit/receive data */
    u32  stat;           /* 0x04: SIO_STAT - status register */
    u16  mode;           /* 0x08: SIO_MODE - mode register */
    u16  ctrl;           /* 0x0A: SIO_CTRL - control register */
    u32  baud;           /* 0x0C: SIO_BAUD / misc control */
    u32  rx_data;        /* 0x10: Receive buffer / response data (accessed as u32, s16+s16) */
    u32  callback;       /* 0x14: Handler callback pointer */
    u32  event_handle;   /* 0x18: Scheduled event handle */
} Serial_Port;           /* 0x1C = 28 bytes */

/* Serial subsystem memory layout (from Serial_Reset memsets) */
#define SERIAL_PORT_BASE   0x00597CC0  /* Port 0 state (0x1C bytes) */
#define SERIAL_PORT1_BASE  0x00597CDC  /* Port 1 state (0x1C bytes) */
#define SERIAL_BUFFER_BASE 0x00597CE0  /* Serial buffers (0x80 bytes) */
#define SERIAL_PAD_BASE    0x00597D60  /* Pad response data (0x4100 bytes) */
#define SERIAL_EXTRA_BASE  0x0059BE60  /* Extra serial state (0x80 bytes) */

/*
 * ==========================================================================
 *  PS1 SPU State (emulated)
 *  SPU RAM: 512KB at 0x007AB980 (standard PS1 SPU memory).
 *  SPU control state: 12 bytes at 0x00850970.
 *  SPU I/O range: 0x1F801C00, size 0x260.
 *  Verified from SPU_RegisterIO and SPU_ProcessSamples.
 * ==========================================================================
 */
typedef struct {
    u32  buffer_pos;     /* 0x00: Current position in output buffer */
    u32  field_04;       /* 0x04: Unknown */
    u32  sample_count;   /* 0x08: Sample count / buffer index */
} SPU_State;             /* 0x0C = 12 bytes */

#define SPU_RAM_BASE      0x007AB980  /* SPU RAM (512KB), zeroed on init */
#define SPU_RAM_SIZE_EMU  0x00080000  /* 512KB */
#define SPU_STATE_BASE    0x00850970  /* SPU control state (12 bytes) */
#define SPU_VOICE_COUNT   24          /* PS1 SPU has 24 voices */

/*
 * ==========================================================================
 *  PS1 Interrupt State (emulated)
 *  I/O range: 0x1F801070, size 0x10.
 *  Uses __gp globals for stat/mask shadows.
 *  Callback table: 0x78 (120) bytes = 10 entries * 12 bytes each
 *  (or similar structure, zeroed with memset).
 *  IRQ channels: 0=MDEC_in, 1=MDEC_out, 2=GPU_vblank, 3=CDROM,
 *                4=DMA, 5=Timer, 6=Pad, 7-9=SIO/SPU/Lightgun
 * ==========================================================================
 */
#define IRQ_MDEC_IN    0
#define IRQ_MDEC_OUT   1
#define IRQ_VBLANK     2
#define IRQ_CDROM      3
#define IRQ_DMA        4
#define IRQ_TIMER      5
#define IRQ_PAD        6
#define IRQ_SIO        7
#define IRQ_SPU        8
#define IRQ_LIGHTGUN   9

/*
 * ==========================================================================
 *  GPU Handler Slot
 *  Base at 0x00506D90, 0x1C bytes per slot.
 *  Verified from GPU_Init (memset 0x38 = 2 slots), GPU_ProcessQueue.
 *  GPU iterates slots with stride 0x1C.
 * ==========================================================================
 */
typedef struct {
    u32  status;         /* 0x00: Status/control register */
    u32  ctrl_bits;      /* 0x04: Control flags */
    u32  state;          /* 0x08: GPU state word */
    u32  list_index;     /* 0x0C: Display list index */
    u32  handler_offset; /* 0x10: Handler table offset */
    u32  insn_count;     /* 0x14: Instruction counter */
    u32  insn_data;      /* 0x18: Current instruction data */
} GPU_HandlerSlot;       /* 0x1C = 28 bytes */

#define GPU_HANDLER_BASE  0x00506D90  /* GPU handler slots (2 * 0x1C = 56 bytes) */

/*
 * ==========================================================================
 *  JIT Compiler State and Cache
 *  State base at 0x00503B20, size 0x3060 (12,384 bytes).
 *  Zeroed on init by both Compiler_Init and R3000_Init.
 *  Cache slot table at 0x0024AA00, 10 entries * 0x10 bytes.
 *  Also accesses many positive __gp offsets (0x18-0x2C4) for
 *  code cache management, block tracking, and recompiler state.
 * ==========================================================================
 */
typedef struct {
    u32  cached_value;   /* 0x00: Cached code block value */
    u32  key;            /* 0x04: Address key for lookup */
    u32  reserved;       /* 0x08: Reserved / padding */
    u32  allocated;      /* 0x0C: Allocation flag (1 = in use) */
} JIT_CacheSlot;         /* 0x10 = 16 bytes */

#define JIT_STATE_BASE    0x00503B20  /* JIT compiler state (0x3060 bytes) */
#define JIT_STATE_SIZE    0x00003060
#define JIT_CACHE_TABLE   0x0024AA00  /* JIT cache slot table */
#define JIT_CACHE_SLOTS   10

/*
 * ==========================================================================
 *  MDEC (Motion Decoder) State
 *  I/O range: 0x1F801820, size 0x10.
 *  State buffer: 0x140 (320) bytes, zeroed on init.
 *  Request queue: 0x28-byte slots for decode requests.
 *  Lookup tables: 0x40 (64) bytes at 0x0059D5D8.
 *  MDEC __gp offsets (-0x7788 to -0x776C) use byte-level
 *  accesses suggesting packed control flags.
 * ==========================================================================
 */
typedef struct {
    u32  command;        /* 0x00: Slot status/command (0 = free) */
    u8   status_byte;    /* 0x04: Status byte (at offset +1) */
    u8   _pad0[3];
    u32  data_ptr;       /* 0x08: Data pointer (zeroed on init) */
    u32  cmd_id;         /* 0x0C: Command ID (4=ReadN, 5=ReadS) */
    u32  active;         /* 0x10: Active flag (1=active) */
    u32  count;          /* 0x14: Transfer count/size */
    u8   state[8];       /* 0x18-0x1F: State bytes (error flags, status bits) */
    u32  sector_data;    /* 0x20: Sector data word (LOAD/STORE WORD access) */
    u32  buffer_ptr;     /* 0x24: Pointer to output buffer */
} MDEC_Request;          /* 0x28 = 40 bytes */

#define MDEC_STATE_SIZE   0x140       /* 320 bytes */
#define MDEC_TABLE_BASE   0x0059D5D8  /* MDEC lookup tables (64 bytes) */
#define MDEC_REQUEST_SLOTS 8

/*
 * ==========================================================================
 *  CDROM State
 *  I/O range: 0x1F801800, size 0x10.
 *  State includes sector cache, TOC, audio FIFO.
 *  Audio buffer area: 0xD50 (3,408) bytes at state+0x350.
 *  IRQ callback registered on channel 3 (IRQ_CDROM).
 * ==========================================================================
 */

/*
 * ==========================================================================
 *  PS1 Hardware Emulation State Block
 *  Base at 0x00506C08, total 0x128 bytes, zeroed on DMA init.
 *  Shared between DMA and interrupt subsystems.
 *  Verified from Interrupt_ProcessChannel, Interrupt_ResetAll.
 * ==========================================================================
 */
#define HW_EMU_STATE_BASE 0x00506C08  /* Hardware emu state (0x128 bytes) */
/*  Offsets from HW_EMU_STATE_BASE:
 *    0x20:  u32 display_list_id  (from GPU_GetDisplayListID)
 *    0x70:  u32 channel_status   (per-channel bits, tested >> channel*2)
 *    0x74:  u32 int_status       (main interrupt status/control register)
 *    0x80:  u32 event_pending    (0=none, !=0=scheduled event exists)
 *    0x8C:  u32 ack_clear        (always zeroed for acknowledge)
 *    0xAC:  u32 event_handle     (event timeout handle)
 *    0xB0:  u32 frame_counter    (frame number / cycle counter)
 *    0xBC:  u32 int_pending_flag (set to 1 in StartChannel)
 *    0x120: u32 pending_count    (interrupt accumulator, zeroed on reset)
 *    0x124: u32 queued_count     (interrupt accumulator, zeroed on reset)
 */

/*
 * ==========================================================================
 *  Serial Device State (full controller/memcard device)
 *  Two devices at 0x507000 + device*0x90, stride 0x90 bytes.
 *  This is the full pad/memcard protocol handler, larger than
 *  the Serial_Port I/O register mirror (0x1C bytes at 0x597CC0).
 *  Verified from Serial_ProcessCommand loop (s3 < 2, v1 += 0x90).
 * ==========================================================================
 */
#define SERIAL_DEVICE_BASE  0x00507000  /* Device 0 state */
#define SERIAL_DEVICE_SIZE  0x90        /* 144 bytes per device */
#define SERIAL_DEVICE_COUNT 2           /* 2 controller ports */

/*
 * ==========================================================================
 *  PS1 I/O Handler Map (registered via R3000_SetupIOHandlers)
 *  Maps PS1 hardware register addresses to emulator read/write handlers.
 * ==========================================================================
 *
 *  0x1F801040 - 0x1F80105F  Serial (pads, memcards)  [serial.c]
 *  0x1F801070 - 0x1F80107F  Interrupt Controller      [interrupt.c]
 *  0x1F801080 - 0x1F8010FF  DMA Controller            [dma.c]
 *  0x1F801100 - 0x1F80112F  Timers/Counters           [counter.c]
 *  0x1F801800 - 0x1F80180F  CDROM                     [cdrom.c]
 *  0x1F801810 - 0x1F80181F  GPU                       [gpu.c]
 *  0x1F801820 - 0x1F80182F  MDEC                      [mdec.c]
 *  0x1F801C00 - 0x1F801E5F  SPU                       [spu.c]
 */

#endif /* POPS_TYPES_H */
