/* POPS.ELF Decompiled - r3000.c */
/* Auto-generated by POPS Decompiler */
/* 59 functions */

#include "pops_types.h"
#include "functions.h"

/* Forward declarations */
u32 R3000_Init(void);
u32 R3000_InitHandlers(u32 a0, u32 a1);
u32 R3000_ReadMemory(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_WriteMemory(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_ReadIOPort(u32 a0, u32 a1);
u32 R3000_WriteIOPort(u32 a0);
u32 R3000_SetupIOHandlers(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_MapAddressRange(u32 a0, u32 a1);
u32 R3000_Reset(u32 a0);
u32 R3000_MapMemory(void);
u32 R3000_InvalidateAllBlocks(void);
u32 R3000_InvalidateRange(u32 a0, u32 a1);
u32 R3000_MarkPagesWritten(u32 a0, u32 a1, u32 a2);
void R3000_GetCodeCacheEntry(void);
u32 R3000_AllocCodeBlock(u32 a0);
u32 R3000_CompileBlock(u32 a0);
u32 R3000_GetCachePointers(u32 a0, u32 a1);
u32 R3000_GetCacheBase(void);
u32 R3000_InitCodeCache(void);
u32 R3000_AllocTranslationBuffers(void);
u32 R3000_ExecuteBlocks(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_HandleBranchBlock(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitDelaySlot(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitStoreDelay(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_HandleConditionalBranch(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitCOP0Read(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitCOP0Write(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitLoadOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitStoreOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitALUOp(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitBranch(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitJump(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitJumpRegister(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitGTEDataRead(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitGTEDataWrite(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitGTEControlRead(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitGTEControlWrite(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitGTEDataReadAlt(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitSyscall(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitBreak(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitCOP0Op(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitCOP0OpWrite(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitCOP2DataReadAlt(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitExceptionReturn(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitSyscallImmediate(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_EmitMemoryAccess(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_FlushPendingStores(u32 a0);
u32 R3000_BuildBlockDescriptor(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_DecodeInstruction(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_TranslateBlockRange(u32 a0, u32 a1, u32 a2);
u32 R3000_TranslateFromPC(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_TranslateAndCompile(u32 a0);
u32 R3000_ExecutionLoop(u32 a0, u32 a1, u32 a2, u32 a3);
u32 R3000_ClassifyAddress(u32 a0);
u32 R3000_UpdateBlockSize(u32 a0);
u32 R3000_SetBlockSize(u32 a0, u32 a1);
u32 R3000_GetBlockSize(void);
void R3000_GetCurrentBlock(void);
u32 R3000_ResetCompiler(void);

/* ======================================== */

/* Function at 0x00201770 - 0x0020177C */
u32 R3000_Init(void)
{
    u32 ret, v1, a1;
    ret = 0x00200000;
    v1 = 0x00200000;
    a1 = 0x00200000;
    return R3000_InitHandlers(0, a1);
}

/* Function at 0x0020177C - 0x002017DC */
u32 R3000_InitHandlers(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a2, a3;
    ret = ret + 0x1300;
    v1 = v1 + 0x1350;
    a1 = a1 + 0x1420;
    ((PSX_State*)a0)->exec_handlers[0] = ret;  /* exec_handlers[0] (store) */
    ((PSX_State*)a0)->exec_handlers[1] = v1;  /* exec_handlers[1] (store) */
    ((PSX_State*)a0)->exec_handlers[4] = a1;  /* exec_handlers[4] (store) */
    ((PSX_State*)a0)->gte_execute = 0;  /* gte_execute (store) */
    ((PSX_State*)a0)->exec_handlers[2] = 0;  /* exec_handlers[2] (store) */
    ((PSX_State*)a0)->exec_handlers[3] = 0;  /* exec_handlers[3] (store) */
    ((PSX_State*)a0)->gte_read_data = 0;  /* gte_read_data (store) */
    ((PSX_State*)a0)->gte_read_ctrl = 0;  /* gte_read_ctrl (store) */
    ((PSX_State*)a0)->gte_write_data = 0;  /* gte_write_data (store) */
    ((PSX_State*)a0)->gte_write_ctrl = 0;  /* gte_write_ctrl (store) */
    a0 = g_psx;
    ret = PSX_ResetCPUState(a0);
    return 1;
}

/* Function at 0x002017DC - 0x0020190C */
u32 R3000_ReadMemory(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, t0;
    ret = a3 + ret;
    v1 = ((unsigned)ret < 0x2000) ? 1 : 0;
    t0 = a1;
    if (v1 != 0) {
        a3 = g_psx;
        v1 = v1 << 2;
        a2 = *(u32*)(a3 + 0x2c4);  /* cop2_insn_count */
        ret = *(u32*)(ret + -0x6780);
        a2 = a2 + -3;
        *(u32*)(a3 + 0x2c4) = a2;  /* cop2_insn_count (store) */
        ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
        goto loc_2018F4;
    }
    a0 = 0xE0800000;
    a2 = a3 + a0;
    a1 = g_psx;
    if ((unsigned)a2 < 0x400) {
        v1 = 1;
        ret = ((PSX_State*)a1)->cop2_insn_count;  /* cop2_insn_count */
        ret = ret + 4;
        ((PSX_State*)a1)->cop2_insn_count = ret;  /* cop2_insn_count (store) */
        if (t0 == v1) {
            v1 = ((PSX_State*)a1)->scratch_base;  /* scratch_base */
        } else {
            ret = 2;
            v1 = ((PSX_State*)a1)->scratch_base;  /* scratch_base */
            if (t0 != ret) goto loc_2018D0;
            v1 = v1 + a2;
            goto loc_2018C8;
    }
        a0 = 0xE0800400;
        a2 = a3 + a0;
        if ((unsigned)a2 < 0x400) {
            a1 = g_psx;
            v1 = 1;
            ret = ((PSX_State*)a1)->cop2_insn_count;  /* cop2_insn_count */
            ret = ret + 4;
            ((PSX_State*)a1)->cop2_insn_count = ret;  /* cop2_insn_count (store) */
            if (t0 == v1) {
                v1 = ((PSX_State*)a1)->hw_regs_base;  /* hw_regs_base */
                }
                v1 = v1 + a0;
                ret = *(u8*)(v1);
                goto loc_2018F0;
            }
            ret = 2;
            v1 = ((PSX_State*)a1)->hw_regs_base;  /* hw_regs_base */
            if (t0 != ret) goto loc_2018D0;
            v1 = v1 + a2;
            loc_2018C8:
            ret = *(u16*)(v1);
            goto loc_2018F0;
            loc_2018D0:
            v1 = v1 + a2;
            ret = *(u32*)(v1);
        } else {
            ret = -1;
            if ((((unsigned)v1 < 0x400) ? 1 : 0) != 0) ret = 0;
        }
loc_2018F0:
loc_2018F4:
    return ret;
}

/* Function at 0x0020190C - 0x00201A0C */
u32 R3000_WriteMemory(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, t0, t1;
    v1 = a3 + ret;
    t1 = a1;
    t0 = a2;
    if ((unsigned)v1 < 0x2000) {
        t0 = g_psx;
        ret = ret << 2;
        v1 = *(u32*)(t0 + 0x2c4);  /* cop2_insn_count */
        a3 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        a3 = a3 + ret;
        a3 = *(u32*)(a3 + -0x5f80);
        v1 = v1 + -7;
        *(u32*)(t0 + 0x2c4) = v1;  /* cop2_insn_count (store) */
        ret = CALL_INDIRECT(a3)(a0, a1, a2, a3);
    } else {
        a0 = 0xE0800000;
        a2 = a3 + a0;
        v1 = 1;
        if ((unsigned)a2 < 0x400) {
            a1 = g_psx;
            if (t0 == v1) {
                ret = ((PSX_State*)a1)->scratch_base;  /* scratch_base */
                goto loc_2019C0;
            }
            ret = ((PSX_State*)a1)->scratch_base;  /* scratch_base */
            if (t0 != ret) goto loc_2019E8;
            ret = ret + a2;
            goto loc_2019E0;
        }
        a0 = 0xE0800400;
        a2 = a3 + a0;
        if ((unsigned)a2 >= 0x400) goto loc_2019F4;
        v1 = 1;
        a1 = g_psx;
        if (t0 == v1) {
            ret = ((PSX_State*)a1)->hw_regs_base;  /* hw_regs_base */
            loc_2019C0:
            ret = ret + a0;
            *(u8*)(ret) = t1;
        } else {
            ret = ((PSX_State*)a1)->hw_regs_base;  /* hw_regs_base */
            if (t0 != ret) goto loc_2019E8;
            ret = ret + a2;
            loc_2019E0:
            *(u16*)(ret) = t1;
            goto loc_2019F0;
            loc_2019E8:
            ret = ret + a2;
            *(u32*)(ret) = t1;
        }
        loc_2019F0:
    }
loc_2019F4:
    return ret;
}

/* Function at 0x00201A0C - 0x00201B7C */
u32 R3000_ReadIOPort(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a2, a3;
    a1 = a1 | 0x1018;
    a0 = a0 & ret;
    if (a0 == a1) return R3000_ReadIOPort(a0, a1);
    ret = ((unsigned)a1 < (unsigned)a0) ? 1 : 0;
    a1 = 0;
    ret = PSX_HandleException(a0, a1, a2, a3);
    ret = -1;
    return ret;
}

/* Function at 0x00201B7C - 0x00201CC8 */
u32 R3000_WriteIOPort(u32 a0)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a1, a2, a3;
    v1 = v1 | 0x1014;
    a0 = a0 & ret;
    if (a0 == v1) return R3000_WriteIOPort(a0);
    ret = ((unsigned)v1 < (unsigned)a0) ? 1 : 0;
    return ret;
}

/* Function at 0x00201CC8 - 0x00201D38 */
u32 R3000_SetupIOHandlers(u32 a0, u32 a1, u32 a2, u32 a3)
{
    u32 ret, v1, t0, t1, t2, t3;
    a1 = (unsigned)a1 >> 4;
    a0 = a0 + 0xE07FF000;
    a0 = (unsigned)a0 >> 4;
    if (a2 == 0) {
        a2 = 0x00200000 + 0x1a00;
    }
    ret = 0x00200000;
    if (a3 == 0) {
        a3 = ret + 0x1b70;
    }
    t1 = 0;
    if (a1 != 0) {
        ret = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        t3 = ret + -0x6780;
        t2 = v1 + -0x5f80;
        t0 = a0 << 2;
        do {
            t1 = t1 + 1;
            ret = t0 + t3;
            a0 = t0 + t2;
            t0 = t0 + 4;
            v1 = ((unsigned)t1 < (unsigned)a1) ? 1 : 0;
            *(u32*)(ret) = a2;
            *(u32*)(a0) = a3;
        } while (v1 != 0);
    }
    return ret;
}

/* Function at 0x00201D38 - 0x00201D68 */
u32 R3000_MapAddressRange(u32 a0, u32 a1)
{
    u32 ret, v1, a2;
    a1 = (unsigned)a1 >> 0x1c;
    a1 = a1 << 4;
    a1 = a1 + a0;
    ret = *(u64*)(a2);
    v1 = *(u64*)(a2 + 8);
    *(u64*)(a1) = ret;
    *(u64*)(a1 + 8) = v1;
    return ret;
}

/* Function at 0x00201D68 - 0x00201F08 */
u32 R3000_Reset(u32 a0)
{
    /* Stack frame: 64 bytes */
    u32 local_0C;
    u32 ret, v1, a1, a2, a3, s0, s1, psx, s3, t0;
    s3 = 0x00500000;
    s0 = s3 + 0x38c8;
    psx = a0;
    ((PSX_State*)psx)->mem_ctrl[0] = s0;  /* mem_ctrl[0] (store) */
    ret = R3000_MapMemory();
    s1 = 0x00200000;
    if (ret == 0) {
        a0 = 0x004F9108;
        ret = AssertionFailed(a0, a1, a2, a3);
        ret = 0;
    } else {
        ret = 0x00200000;
        v1 = s0;
        a3 = ret + 0x1a00;
        a1 = 0;
        a0 = 0x0FFFFFFF;
        a2 = s1 + 0x1b70;
        do {
            a1 = a1 + 1;
            *(u32*)(v1) = 0;
            ret = ((unsigned)a1 < 0x10) ? 1 : 0;
            *(u32*)(v1 + 4) = a0;
            *(u32*)(v1 + 8) = a3;
            *(u32*)(v1 + 0xc) = a2;
            v1 = v1 + 0x10;
        } while (ret != 0);
        s0 = s3 + 0x38c8;
        v1 = ((PSX_State*)psx)->bios_base;  /* bios_base */
        ret = 7 << 16;
        a2 = __sp;
        ret = 0x0007FFFF;
        a0 = s0;
        a1 = 0xB0000000;
        s1 = 0x00201B70;
        *(u32*)(__sp) = v1;
        *(u32*)(__sp + 4) = ret;
        *(u32*)(__sp + 8) = 0;
        local_0C = s1;
        ret = R3000_MapAddressRange(a0, a1);
        v1 = ((PSX_State*)psx)->ram_base;  /* ram_base */
        a2 = __sp;
        ret = 0x001FFFFF;
        a1 = 0;
        a0 = s0;
        *(u32*)(__sp) = v1;
        *(u32*)(__sp + 4) = ret;
        *(u32*)(__sp + 8) = 0;
        local_0C = 0;
        ret = R3000_MapAddressRange(a0, a1);
        a2 = __sp;
        a0 = s0;
        a1 = 0x80000000;
        ret = R3000_MapAddressRange(a0, a1);
        a0 = s0;
        a2 = __sp;
        a1 = 0xA0000000;
        ret = R3000_MapAddressRange(a0, a1);
        v1 = 0x002017D0;
        a3 = 0x00201900;
        ret = 0x0FFFFFFF;
        a0 = s0;
        a1 = 0x10000000;
        a2 = __sp;
        *(u32*)(__sp + 4) = ret;
        *(u32*)(__sp + 8) = v1;
        local_0C = a3;
        *(u32*)(__sp) = 0;
        ret = R3000_MapAddressRange(a0, a1);
        ret = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        v1 = 0x00200000;
        a0 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
        t0 = ret + -0x6780;
        a3 = v1 + 0x1a00;
        a2 = a0 + -0x5f80;
        a1 = 0;
        do {
            ret = a1 << 2;
            a1 = a1 + 1;
            a0 = ret + a2;
            ret = ret + t0;
            v1 = ((unsigned)a1 < 0x200) ? 1 : 0;
            *(u32*)(ret) = a3;
            *(u32*)(a0) = s1;
        } while (v1 != 0);
        ret = 1;
    }
    return ret;
}

/* Function at 0x00201F08 - 0x00201FC0 */
u32 R3000_MapMemory(void)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a0, a1, a2, a3, i, s1, j, t0;
    i = COP0_REG(6); /* mfc0 */
    ret = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    j = 0;
    s1 = ret + -0x5780;
    a1 = *(u32*)(s1);
    do {
        a0 = i;
        a2 = *(u32*)(s1 + 4);
        j = j + 1;
        a3 = *(u32*)(s1 + 8);
        i = i + 1;
        t0 = *(u32*)(s1 + 0xc);  /* GTE data: vz1 */
        s1 = s1 + 0x10;
        ret = System_SifDmaSetup(a0);
        v1 = ((unsigned)j < 7) ? 1 : 0;
        a1 = *(u32*)(s1);
    } while (v1 != 0);
    COP0_REG(6) = i; /* mtc0 */
    SYNC(); /* memory barrier */
    a0 = (u32)Compiler_Emit_SystemCall;
    ret = System_SifRpcExec1(a0);
    v1 = g_psx;
    ret = 0x5F800400;
    a0 = 0x40000000;
    a1 = 0x5FC00000;
    a2 = 0x5F800000;
    *(u32*)(v1 + 0x2dc) = ret;  /* counter_3 (store) */
    ret = 1;
    *(u32*)(v1 + 0x2d0) = a0;  /* counter_0 (store) */
    *(u32*)(v1 + 0x2d4) = a1;  /* counter_1 (store) */
    *(u32*)(v1 + 0x2d8) = a2;  /* counter_2 (store) */
    return ret;
}

/* Function at 0x00201FC0 - 0x00202050 */
u32 R3000_InvalidateAllBlocks(void)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, a0, a1, a2, a3, i, s1, s2, s3;
    s3 = 0x00500000;
    i = 0;
    s1 = 0;
    s2 = s3 + 0x3a18;
    do {
        v1 = i + s2;
        ret = *(u8*)(v1);
        i = i + 1;
        if (ret != 0) {
            a0 = s1 << 30;
            a0 = (s64)a0 >> 32;
            ret = g_counter_base;
            a0 = a0 << 2;
            a1 = 0x2000;
            a0 = ret + a0;
            ret = Compiler_MemoryClear(a0, a1);
        }
        ret = ((unsigned)i < 0x100) ? 1 : 0;
        s1 = s1 + 8192;
    } while (ret != 0);
    ret = g_bios_ver2;
    a0 = s3 + 0x3a18;
    a1 = 0x100;
    g_irq_mask2 = ret;
    return Compiler_MemoryClear(a0, a1);
}

/* Function at 0x00202050 - 0x002021A0 */
u32 R3000_InvalidateRange(u32 a0, u32 a1)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, a2, a3, s0, s1, t0, t1, t2, t3, t4;
    s0 = a0;
    s1 = a1;
    ret = R3000_GetBlockSize();
    ret = ret << 2;
    t0 = s0 & 0x1FFFFFFF;
    s0 = s0 + s1;
    a0 = ((unsigned)t0 < (unsigned)ret) ? 1 : 0;
    s0 = s0 & v1;
    if (a0 != 0) t0 = ret;
    ret = t0 - ret;
    s0 = s0 + 1023;
    ret = (unsigned)ret >> 0xa;
    v1 = 0x001FFFFF;
    ret = (u64)ret << 32;
    s0 = (signed)s0 >> 10;
    t0 = ret << 10;
    t0 = (s64)t0 >> 32;
    t1 = (u64)s0 << 42;
    t1 = (s64)t1 >> 32;
    v1 = ((unsigned)v1 < (unsigned)t0) ? 1 : 0;
    t3 = 0;
    if (v1 != 0) goto loc_202134;
    a1 = t0;
    if ((unsigned)t0 >= (unsigned)t1) goto loc_202134;
    ret = 0x00500000;
    t2 = 1;
    t4 = ret + 0x3a18;
loc_2020E0:
    ret = (unsigned)a1 >> 0xa;
    v1 = (unsigned)a1 >> 0xd;
    ret = ret & 7;
    a2 = v1 + t4;
    ret = t2 << ret;
    v1 = *(u8*)(a2);
    ret = (s64)ret >> 32;
    a1 = a1 + 0x400;
    a0 = ~(0 | ret);
    a0 = v1 & a0;
    v1 = v1 & ret;
    a3 = ((unsigned)a1 < (unsigned)t1) ? 1 : 0;
    if (v1 != 0) {
        *(u8*)(a2) = a0;
        ret = 1;
        goto loc_20212C;
    }
    ret = 0;
loc_20212C:
    if (ret != 0) t3 = t2;
    if (a3 != 0) goto loc_2020E0;
loc_202134:
    if (t3 == 0) goto loc_20218C;
    a0 = g_counter_base;
    v1 = t0 & 0x001FFFFF;
    ret = t1 & ret;
    v1 = (unsigned)v1 >> 2;
    a1 = a0 + ret;
    v1 = a0 + v1;
    if (v1 == a1) goto loc_202190;
    ret = *(u32*)(v1);
loc_202168:
    *(u32*)(v1) = 0;
    if (ret != 0) goto loc_202170;
loc_202170:
    v1 = v1 + 4;
    ret = *(u32*)(v1);
    if (v1 != a1) goto loc_202168;
loc_20218C:
loc_202190:
    return ret;
}

/* Function at 0x002021A0 - 0x00202258 */
u32 R3000_MarkPagesWritten(u32 a0, u32 a1, u32 a2)
{
    u32 ret, v1, a3, t0, t1, t2;
    ret = 0x1FFFFFFF;
    a3 = 0x001FFFFF;
    a0 = a0 & ret;
    t2 = a2;
    ret = a0 & a3;
    a3 = ((unsigned)a3 < (unsigned)a0) ? 1 : 0;
    v1 = (unsigned)a0 >> 0xa;
    ret = (unsigned)ret >> 2;
    t0 = (unsigned)a0 >> 0xd;
    v1 = v1 & 7;
    t1 = ret << 2;
    a2 = a0 + a1;
    if (a3 == 0) {
        a0 = (unsigned)a2 >> 0xa;
        a1 = 0x00503A18;
        a3 = (unsigned)a2 >> 0xd;
        a3 = a3 + a1;
        a1 = t0 + a1;
        ret = 1;
        a0 = a0 & 7;
        a0 = ret << a0;
        ret = ret << v1;
        v1 = *(u8*)(a1);
        ret = ret & 0xff;
        a2 = g_counter_base;
        a0 = a0 & 0xff;
        *(u8*)(a1) = v1 | ret;
        a2 = t1 + a2;
        ret = ret | a0;
        *(u8*)(a3) = ret;
        *(u32*)(a2) = t2;
        return ret;
    }
    v1 = g_counter_base;
    ret = ret + v1;
    *(u32*)(ret) = t2;
    return ret;
}

/* Function at 0x00202258 - 0x0020225C */
void R3000_GetCodeCacheEntry(void)
{
    u32 v1;
    v1 = 0x1FFF0000;
}

/* Function at 0x0020225C - 0x002022C8 */
u32 R3000_AllocCodeBlock(u32 a0)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a1, a2, a3, s0;
    v1 = v1 | 0xffff;
    s0 = a0 & v1;
    ret = 0x001FFFFF;
    if ((unsigned)ret >= (unsigned)s0) {
        ret = g_irq_mask2;
        if (ret == 0) goto loc_2022B4;
        ret = R3000_InvalidateAllBlocks();
        ret = g_irq_mask2;
        goto loc_2022B4;
    }
    ret = g_irq_stat2;
loc_2022B4:
    *(u32*)(ret + 0x10) = s0;
    return ret;
}

/* Function at 0x002022C8 - 0x00202478 */
u32 R3000_CompileBlock(u32 a0)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, s3;
    s2 = a0;
    s1 = s2 + 0x1c;
    a2 = s1;
    *(u32*)(s2 + 0x18) = 0;
    ret = ret + 0x1c;
    s3 = s2 + ret;
    *(u32*)(s3) = 0;
    *(u32*)(s3 + 4) = 0;
    *(u32*)(s2 + 8) = s3;
    a0 = *(u32*)(s2 + 0x10);  /* GTE data: vxy2 */
    *(u16*)(s3 + 0x14) = 0;
    *(u32*)(s3 + 8) = 0;
    *(u16*)(s3 + 0x16) = 0;
    ret = R3000_MarkPagesWritten(a0, a1, a2);
    s0 = *(u16*)(s2 + 0x14);  /* GTE data: vz2 */
    a0 = s1;
    s0 = s1 + s0;
    a1 = s0;
    ret = UI_DCacheInvalidateSync(a0, a1);
    ret = TLB_SetupEntries();
    v1 = -0x40;
    a0 = 0;
    s0 = s0 & v1;
    s1 = s1 & v1;
    a1 = -0x2000;
loc_202350:
    SYNC(); /* memory barrier */
    CACHE(0, (a0)); /* cache op */
    SYNC(); /* memory barrier */
    ret = COP0_REG(28); /* mfc0 */
    ret = ret + a0;
    v1 = ((unsigned)s0 < (unsigned)ret) ? 1 : 0;
    if ((unsigned)ret < (unsigned)s1) goto loc_202390;
    if (v1 != 0) goto loc_202390;
    SYNC(); /* memory barrier */
    SYNC(); /* memory barrier */
    CACHE(7, (a0)); /* cache op */
    SYNC(); /* memory barrier */
loc_202390:
    SYNC(); /* memory barrier */
    CACHE(0, 1(a0)); /* cache op */
    SYNC(); /* memory barrier */
    ret = COP0_REG(28); /* mfc0 */
    ret = ret + a0;
    v1 = ((unsigned)s0 < (unsigned)ret) ? 1 : 0;
    if ((unsigned)ret < (unsigned)s1) goto loc_2023CC;
    if (v1 != 0) goto loc_2023CC;
    SYNC(); /* memory barrier */
    CACHE(7, 1(a0)); /* cache op */
    SYNC(); /* memory barrier */
loc_2023CC:
    SYNC(); /* memory barrier */
    a0 = a0 + 0x40;
    if ((signed)a0 < 0x2000) goto loc_202350;
    ret = System_EnableInterrupts();
    v1 = *(u32*)(s2 + 0x10);  /* GTE data: vxy2 */
    ret = 0x001FFFFF;
    g_irq_stat2 = s3;
    if ((unsigned)ret >= (unsigned)v1) {
        g_irq_mask2 = s3;
    }
    return ret;
    v1 = g_counter_base;
    return *(u32*)(ret);
}

/* Function at 0x00202478 - 0x002024A8 */
u32 R3000_GetCachePointers(u32 a0, u32 a1)
{
    u32 ret, v1;
    *(u32*)(a0) = g_bios_ver2;
    ret = g_bios_ver2;
    __at = 0x00300000;
    ret = __at + ret;
    *(u32*)(a1) = ret;
    return ret;
}

/* Function at 0x002024A8 - 0x002024AC */
u32 R3000_GetCacheBase(void)
{
    u32 v1;
    v1 = g_bios_ver2;
}

/* Function at 0x002024AC - 0x00202500 */
u32 R3000_InitCodeCache(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a0, a1, a2, a3;
    a0 = g_counter_base;
    a1 = 0x00280000;
    ret = ret + v1;
    g_irq_mask2 = v1;
    g_irq_stat2 = ret;
    g_hw_init_flag = ret;
    ret = Compiler_MemoryClear(a0, a1);
    ret = R3000_InvalidateAllBlocks();
    a0 = 0x00503A18;
    a1 = 0x100;
    return Compiler_MemoryClear(a0, a1);
}

/* Function at 0x00202500 - 0x002026C0 */
u32 R3000_AllocTranslationBuffers(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, a0, a1, a2, a3, t0, t1, t2, t3, t4, t5, v1;
    a0 = 0x1000;
    a1 = 0x00280000;
    ret = EEKernel_SyscallWrapper(a0, a1);
    a0 = 0x1000;
    a1 = 0x00300000;
    g_counter_base = ret;
    ret = EEKernel_SyscallWrapper(a0, a1);
    a1 = 0x00300000;
    a0 = ret;
    g_bios_ver2 = a0;
    if (a0 != 0) {
        ret = Compiler_MemoryClear(a0, a1);
        R3000_GetCacheBase();
        ret = 1;
    }
    return ret;
    a0 = 0xE0800000;
    ret = a2 + a0;
    a0 = 0xE0400000;
    if ((unsigned)ret < 0x400) {
        v1 = g_psx;
        ret = *(u32*)(v1 + 0x2d8);  /* counter_2 */
    } else {
        ret = 7 << 16;
        v1 = a2 + a0;
        ret = 0x0007FFFF;
        v1 = g_psx;
        if ((unsigned)ret >= (unsigned)v1) {
            ret = *(u32*)(v1 + 0x2d4);  /* counter_1 */
        } else {
            a0 = 0xE0800400;
            ret = a2 + a0;
            a0 = 0;
            if ((unsigned)ret < 0x400) {
                v1 = g_psx;
                ret = *(u32*)(v1 + 0x2dc);  /* counter_3 */
                }
                }
                ret = ret + a2;
                a0 = ret + a0;
            }
    *(u32*)(t4) = a0;
    if ((unsigned)a1 < (unsigned)0x00503B20) goto loc_202688;
    ret = ret + t4;
    t0 = ret + 0xc;
loc_202630:
    ret = *(u32*)(v1);
    v1 = v1 + 0x30;
    ret = ret ^ 1;
    a3 = ((unsigned)ret < 1) ? 1 : 0;
    a2 = ((unsigned)a1 < (unsigned)v1) ? 1 : 0;
    if (a3 != 0) {
        ret = *(u32*)(a0);
        t5 = t5 + ret;
    }
    t3 = a3;
    if (a3 == t3) {
        t1 = t1 + 1;
        goto loc_202680;
    }
    *(u32*)(t0) = t1;
    if (t3 != 0) {
        *(u32*)(t0 + 4) = t1;
        t0 = t0 + 8;
        t2 = t2 + 1;
    }
    t1 = 1;
loc_202680:
    a0 = a0 + 4;
    if (a2 == 0) goto loc_202630;
loc_202688:
    ret = t2 << 4;
    if (t3 != 0) {
        ret = t4 + ret;
        *(u32*)(ret + 0xc) = t1;  /* field_0C (LO) (store) */
        ret = t2 << 4;
    }
    a0 = t2 + 1;
    ret = t4 + ret;
    v1 = -4;
    ret = ret + 0x13;
    *(u32*)(t4 + 4) = t5;
    *(u32*)(t4 + 8) = a0;
    return ret & v1;
}

/* Function at 0x002026C0 - 0x002029C8 */
u32 R3000_ExecuteBlocks(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 96 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, s6, s7, t0, t1;
    s5 = a0;
    ret = 0x1FFFFFFF;
    v1 = 0x007F0000;
    s3 = 0;
    s4 = 0;
    s6 = a1;
    s7 = 0x00500000;
    ret = s5 & ret;
    *(u32*)(__sp) = a2;
    v1 = ((unsigned)v1 < (unsigned)ret) ? 1 : 0;
    ret = 1;
    *(u32*)(t1) = 0;
    *(u32*)(s7 + 0x6b80) = 0;
    *(u32*)(__sp + 8) = t0;
    g_jit_state = ret;
    *(u32*)(__sp + 4) = a3;
    t0 = *(u32*)(__sp);
    if (v1 == 0) {
        a1 = t0;
        t0 = Compiler_Emit_FloatLoad(a0, a1);
    }
    a0 = t0;
    t0 = Compiler_InitCacheBuffer(a0);
    s0 = 0x00500000 + 0x3b20;
    v1 = *(u32*)(__sp);
    if (v1 != 0) goto loc_202984;
    __fp = 1;
loc_202770:
    v1 = *(u32*)(s0);
    ret = v1 & 0x200;
    if (ret == 0) goto loc_202970;
    a1 = t0;
    if (ret != 0) {
        a0 = 0;
        g_jit_state = __fp;
        *(u32*)(s7 + 0x6b80) = 0;
        ret = Compiler_Emit_SW(a0, a1);
        v1 = *(u32*)(s0);
        t0 = ret;
    }
    ret = v1 & 0x400;
    s1 = t0;
    if (ret != 0) {
        a1 = t0;
        a0 = 1;
        ret = Compiler_Emit_SW(a0, a1);
        v1 = *(u32*)(s0);
        t0 = ret;
    }
    ret = v1 & 2;
    v1 = v1 | 0x100;
    if (ret != 0) {
        ret = *(u32*)(s0 + 4);
        a0 = *(u32*)(s0 + 0x34);  /* GTE data: sxy1 */
        a1 = s4;
        s3 = s3 + ret;
        ret = *(u32*)(s0 + 0x2c);  /* GTE data: ir3 */
        *(u32*)(s0) = v1;
        s3 = s3 + a0;
        *(u32*)(s0 + 0xc) = s1;
        a2 = s3;
        *(u32*)(s0 + 0x3c) = s1;
        a0 = s5;
        a3 = s0;
        ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
        v1 = *(u32*)(s0);
        a0 = *(u32*)(s0 + 0x30);  /* GTE data: sxy0 */
        t0 = ret;
        ret = -0x101;
        v1 = v1 & ret;
        a0 = a0 & 8;
        *(u32*)(s0) = v1;
        if (a0 == 0) {
            s2 = s4 + 4;
            s1 = s0 + 0x30;
            ret = *(u32*)(s0 + 0x5c);  /* GTE data: _reserved */
            a0 = s5;
            a1 = s2;
            a2 = s3;
            a3 = s1;
            ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
            t0 = ret;
        } else {
            s2 = s4 + 4;
            s1 = s0 + 0x30;
        }
        ret = *(u32*)(s0 + 0x2c);  /* GTE data: ir3 */
        a1 = s4;
        a0 = s5;
        a2 = s3;
        a3 = s0;
        ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
        t0 = ret;
        ret = ret & 8;
        a2 = s3;
        if (ret != 0) {
            ret = *(u32*)(s0 + 0x5c);  /* GTE data: _reserved */
            a0 = s5;
            a1 = s2;
            a3 = s1;
            ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
            t0 = ret;
        }
        g_jit_state = __fp;
        s0 = s1;
        *(u32*)(s7 + 0x6b80) = 0;
        s4 = s2;
        s3 = 0;
        goto loc_202954;
    }
    a0 = *(u32*)(s0 + 0x14);  /* GTE data: vz2 */
    ret = *(u32*)(s0 + 4);
    if (a0 == ret) {
        a1 = *(u32*)(s0 + 4);
        a2 = 1;
        a3 = a1;
        if ((unsigned)a2 >= (unsigned)a1) goto loc_202924;
        v1 = s0 + 0x30;
        s3 = s3 + a1;
        if ((unsigned)s6 < (unsigned)v1) goto loc_202934;
        ret = *(u32*)(v1 + 0x14);  /* GTE data: vz2 */
        s3 = s3 + a1;
        if (ret == a0) goto loc_202934;
        t1 = 0x12;
        a2 = a2 + 1;
        do {
            v1 = v1 + 0x30;
            a0 = ((unsigned)s6 < (unsigned)v1) ? 1 : 0;
            a1 = a1 + -1;
            if ((unsigned)a2 >= (unsigned)a3) goto loc_202924;
            s3 = s3 + a1;
            if (a0 != 0) goto loc_202934;
            ret = *(u32*)(v1 + 0x14);  /* GTE data: vz2 */
            a2 = a2 + 1;
        } while (ret != t1);
        loc_202924:
        s3 = s3 + a1;
    } else {
        s3 = s3 + ret;
    }
loc_202934:
    *(u32*)(s0 + 0xc) = t0;
    a0 = s5;
    ret = *(u32*)(s0 + 0x2c);  /* GTE data: ir3 */
    a1 = s4;
    a2 = s3;
    a3 = s0;
    ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
    t0 = ret;
loc_202954:
    ret = ret & 0x1000;
    s0 = s0 + 0x30;
    if (ret == 0) goto loc_202974;
    g_jit_state = __fp;
    s3 = 0;
    *(u32*)(s7 + 0x6b80) = 0;
loc_202970:
    s0 = s0 + 0x30;
loc_202974:
    s4 = s4 + 4;
    if ((unsigned)s6 >= (unsigned)s0) goto loc_202770;
    v1 = *(u32*)(__sp);
loc_202984:
    ret = t0 - v1;
    v1 = *(u32*)(__sp + 4);
    *(u32*)(v1) = ret;
    v1 = *(u32*)(__sp + 8);
    *(u32*)(v1) = ret;
    return ret;
}

/* Function at 0x002029C8 - 0x00202A20 */
u32 R3000_HandleBranchBlock(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    s0 = a1;
    s1 = a0;
    a1 = t0;
    ret = *(u32*)(a3 + 4);
    a0 = a2 - ret;
    ret = Compiler_EncodeNegateOp(a0, a1);
    a0 = s1 + s0;
    a1 = ret;
    ret = Compiler_Emit_SB(a0, a1);
    v1 = 1;
    a0 = 0x00500000;
    g_jit_state = v1;
    *(u32*)(a0 + 0x6b80) = 0;
    return ret;
}

/* Function at 0x00202A20 - 0x00202AA8 */
u32 R3000_EmitDelaySlot(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    a2 = t0;
    s0 = a3;
    v1 = v1 & 0x2000;
    ret = a2;
    if (v1 == 0) {
        ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
        a1 = ret;
        if (ret != 0) {
            a3 = *(u32*)(s0 + 0x10);  /* GTE data: vxy2 */
            a0 = *(u8*)(s0 + 0x14);  /* GTE data: vz2 */
            a2 = *(u32*)(s0 + 0x1c);  /* GTE data: otz */
            a3 = (unsigned)a3 >> 6;
            a3 = a3 & 0x1f;
            ret = Compiler_EmitAddressCalculation(a0, a1, a2, a3);
            a0 = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
            a2 = ret;
            ret = ret << a0;
            v1 = g_jit_state;
            ret = ~(0 | ret);
            g_jit_state = v1 & ret;
        }
        ret = a2;
    }
    return ret;
}

/* Function at 0x00202AA8 - 0x00202B18 */
u32 R3000_EmitStoreDelay(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    a2 = t0;
    s0 = a3;
    ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
    a1 = ret;
    if (ret != 0) {
        a0 = *(u32*)(s0 + 0x14);  /* GTE data: vz2 */
        a2 = *(u32*)(s0 + 0x1c);  /* GTE data: otz */
        a3 = *(u32*)(s0 + 0x18);  /* GTE data: rgbc */
        ret = Compiler_EmitMemoryReference(a0, a1, a2, a3);
        v1 = 1;
        a2 = ret;
        ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
        a0 = g_jit_state;
        v1 = ~(0 | v1);
        a0 = a0 & v1;
        g_jit_state = a0;
    }
    return a2;
}

/* Function at 0x00202B18 - 0x00202BB8 */
u32 R3000_HandleConditionalBranch(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    ret = a1;
    s0 = 8;
    s1 = a2;
    v1 = 0x4c;
    a1 = t0;
    a3 = *(u32*)(a3 + 0x14);  /* GTE data: vz2 */
    a0 = a0 + ret;
    if (a3 != v1) {
        ret = 0x4d;
        v1 = 0xa;
        s0 = 9;
        ret = a3 ^ ret;
        if (ret != 0) s0 = v1;
    }
    ret = Compiler_Emit_ImmediateArith(a0, a1);
    a0 = ret;
    ret = Compiler_Emit_JAL();
    a0 = 1;
    a1 = s0;
    a2 = ret;
    ret = Compiler_Emit_BiImmediate(a0, a1, a2);
    v1 = g_jit_cache;
    a2 = s1;
    a3 = ret;
    a0 = *(u32*)(v1 + 0x14);  /* GTE data: vz2 */
    a1 = 0;
    ret = Compiler_Emit_LB(a0, a1, a2, a3);
    v1 = 1;
    a0 = 0x00500000;
    g_jit_state = v1;
    *(u32*)(a0 + 0x6b80) = 0;
    return ret;
}

/* Function at 0x00202BB8 - 0x00202C28 */
u32 R3000_EmitCOP0Read(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    s0 = a3;
    a3 = t0;
    ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
    a2 = ret;
    if (ret != 0) {
        a0 = *(u32*)(s0 + 0x14);  /* GTE data: vz2 */
        a1 = 0;
        a0 = a0 ^ 0x52;
        a0 = ((unsigned)a0 < 1) ? 1 : 0;
        ret = Compiler_EmitRegisterStore(a0, a1, a2, a3);
        a0 = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
        t0 = ret;
        ret = ret << a0;
        v1 = g_jit_state;
        ret = ~(0 | ret);
        g_jit_state = v1 & ret;
    }
    return t0;
}

/* Function at 0x00202C28 - 0x00202C58 */
u32 R3000_EmitCOP0Write(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, t0;
    ret = a3;
    a1 = 1;
    a3 = t0;
    a0 = *(u32*)(ret + 0x14);  /* GTE data: vz2 */
    a2 = *(u32*)(ret + 0x18);  /* GTE data: rgbc */
    a0 = a0 ^ 0x53;
    a0 = ((unsigned)a0 < 1) ? 1 : 0;
    return Compiler_EmitRegisterStore(a0, a1, a2, a3);
}

/* Function at 0x00202C58 - 0x00202CC8 */
u32 R3000_EmitLoadOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    a2 = t0;
    s0 = a3;
    ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
    a1 = ret;
    if (ret != 0) {
        a0 = *(u32*)(s0 + 0x14);  /* GTE data: vz2 */
        a2 = *(u32*)(s0 + 0x18);  /* GTE data: rgbc */
        a3 = *(u32*)(s0 + 0x1c);  /* GTE data: otz */
        ret = Compiler_EmitEpilogue(a0, a1, a2, a3);
        v1 = 1;
        a2 = ret;
        ret = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
        a0 = g_jit_state;
        v1 = ~(0 | v1);
        a0 = a0 & v1;
        g_jit_state = a0;
    }
    return a2;
}

/* Function at 0x00202CC8 - 0x00202CF0 */
u32 R3000_EmitStoreOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, t0;
    ret = a3;
    a3 = t0;
    a2 = *(u32*)(ret + 0x1c);  /* GTE data: otz */
    a0 = *(u32*)(ret + 0x14);  /* GTE data: vz2 */
    a1 = *(u32*)(ret + 0x18);  /* GTE data: rgbc */
    return Compiler_EmitRegisterLoad(a0, a1, a2, a3);
}

/* Function at 0x00202CF0 - 0x00203040 */
u32 R3000_EmitALUOp(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, s2, t0;
    ret = t0;
    s1 = a3;
    a0 = *(u32*)(s1);
    s2 = *(u32*)(s1 + 0x18);  /* GTE data: rgbc */
    v1 = a0 & 0x2000;
    s0 = *(u32*)(s1 + 0x1c);  /* GTE data: otz */
    if (v1 != 0) goto loc_203024;
    if (s0 == 0) goto loc_203028;
    a1 = *(u32*)(s1 + 0x14);  /* GTE data: vz2 */
    ret = 0xf;
    a3 = *(u16*)(s1 + 0x10);  /* GTE data: vxy2 */
    if (a1 != ret) goto loc_202DFC;
    ret = a0 & 0x1004;
    v1 = 0;
    if (ret == 0) {
        ret = ret & 0x200;
        v1 = ((unsigned)ret < 1) ? 1 : 0;
    }
    ret = g_jit_state;  /* lwu */
    if (v1 == 0) goto loc_202DC0;
    ret = g_jit_state;  /* lwu */
    if (ret != s0) goto loc_202DC0;
    ret = g_jit_state;  /* lwu */
    if (ret != s0) goto loc_202DC0;
    ret = *(u32*)(s1 + 0x44);  /* GTE data: sz1 */
    v1 = 0x20;
    ret = g_jit_state;  /* lwu */
    if (ret != v1) goto loc_202DC0;
    ret = 1;
    a0 = *(u32*)(s1 + 0x10);  /* GTE data: vxy2 */
    a1 = g_jit_state;
    ret = (s64)ret >> 32;
    a0 = a0 << 0x10;
    a1 = a1 | ret;
    v1 = s0 << 2;
    g_jit_state = a1;
    __at = 0x00500000;
    __at = __at + v1;
    *(u32*)(__at + 0x6b80) = a0;
    ret = t0;
    goto loc_203024;
loc_202DC0:
    ret = (s64)ret >> 32;
    a3 = *(u16*)(s1 + 0x10);  /* GTE data: vxy2 */
    if (ret == 0) goto loc_202DFC;
    ret = s0 << 2;
    v1 = *(u32*)(s1 + 0x10);  /* GTE data: vxy2 */
    a0 = 0x00500000;
    a0 = a0 + ret;
    a0 = *(u32*)(a0 + 0x6b80);
    v1 = v1 << 0x10;
    ret = t0;
    if (a0 == v1) goto loc_203024;
    a3 = *(u16*)(s1 + 0x10);  /* GTE data: vxy2 */
loc_202DFC:
    a0 = a1;
    a2 = s2;
    a1 = s0;
    ret = Compiler_EmitPrologue(a0, a1, a2, a3);
    t0 = ret;
    ret = ret + -8;
    v1 = ((unsigned)ret < 8) ? 1 : 0;
    ret = 1;
    if (v1 != 0) {
        ret = ret << 2;
        v1 = *(u32*)(v1 + -0x6ed0);
        goto *v1; /* computed jump */
        ret = 1;
        a1 = *(u32*)(s1 + 0x10);  /* GTE data: vxy2 */
        a0 = g_jit_state;
        ret = (s64)ret >> 32;
        a1 = a1 << 0x10;
        a0 = a0 | ret;
        v1 = s0 << 2;
        __at = 0x00500000;
        __at = __at + v1;
        *(u32*)(__at + 0x6b80) = a1;
        g_jit_state = a0;
        goto loc_203020;
    }
loc_203020:
    ret = t0;
loc_203024:
loc_203028:
    return ret;
}

/* Function at 0x00203040 - 0x00203318 */
u32 R3000_EmitBranch(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 96 bytes */
    u32 local_0C;
    u32 local_10;
    u32 ret, v1, s0, s1, s2, s3, s4, s5, s6, t0, t1, t2;
    s0 = t0;
    s1 = a3;
    a3 = a2;
    s5 = a1;
    s6 = a0;
    a0 = *(u32*)(s1);
    ret = *(u32*)(s1 + 0x28);  /* GTE data: ir2 */
    v1 = a0 & 0x20;
    s3 = *(u32*)(s1 + 0x20);  /* GTE data: ir0 */
    s4 = ret - s6;
    a1 = *(u32*)(s1 + 0x18);  /* GTE data: rgbc */
    a2 = *(u32*)(s1 + 0x1c);  /* GTE data: otz */
    s2 = *(u32*)(s1 + 0x14);  /* GTE data: vz2 */
    if (v1 != 0) {
        ret = a0 & 0x100;
            s2 = s2 ^ 7;
            ret = a0 & 0x100;
        }
    ret = a0 & 0x8000;
    if (ret != 0) {
        ret = *(u8*)(s1 + 0x54);  /* GTE data: rgb1 */
        a3 = 0;
        if (s3 != 0) {
            t2 = s0;
            if (s3 == a1) goto loc_2030F4;
            a0 = s2;
            if (s3 == a2) goto loc_2030F8;
        }
        a3 = 1;
        if (ret != 0) {
            t2 = s0;
            if (ret == a1) goto loc_2030F4;
            a0 = s2;
            if (ret == a2) goto loc_2030F8;
            a3 = 1;
        }
        t2 = s0;
        loc_2030F4:
        a0 = s2;
        loc_2030F8:
        t0 = 0;
        t1 = __sp;
        ret = Compiler_Emit_ADD(a0, a1, a2, a3);
        s0 = ret;
        ret = *(u32*)(__sp);
        if (ret != 0) {
            *(u32*)(s1) = ret | 0x8000;
        }
        a0 = s6 + s5;
        if (s3 == 0) goto loc_2032EC;
        a2 = s0;
        a1 = s3;
        a0 = a0 + 8;
        ret = Compiler_Emit_LH(a0, a1, a2);
        s0 = ret;
    } else {
        ret = a0 & 0x20;
        if (ret != 0) {
            if ((signed)s5 < (signed)s4) {
                t2 = s0;
                if (ret == 0) {
                    t0 = s0;
                    t1 = __sp + 4;
                    t2 = t0;
                    a0 = s2;
                    ret = Compiler_Emit_SUB(a0, a1, a2, a3);
                    v1 = *(u32*)(s1 + 8);
                    a3 = ret;
                    a2 = 0;
                    a1 = *(u32*)(v1 + 0xc);  /* GTE data: vz1 */
                    a0 = s1 + 0x10;
                    ret = Compiler_EncodeLoadStoreAddressing(a0, a1, a2, a3);
                    a0 = *(u32*)(s1 + 0x28);  /* GTE data: ir2 */
                    a1 = ret;
                    ret = Compiler_Emit_ImmediateArith(a0, a1);
                    v1 = g_jit_cache;
                    a1 = 0;
                    a2 = ret;
                    a0 = *(u32*)(v1 + 8);
                    s0 = Compiler_Emit_SH(a0, a1, a2);
                    a0 = *(u32*)(__sp + 4);
                } else {
                    a0 = s2;
                    t0 = 0;
                    t1 = s1 + 0x10;
                    s0 = Compiler_Emit_SUB(a0, a1, a2, a3);
                    } else {
                    t0 = s0;
                    a0 = s2;
                    t1 = __sp + 8;
                    t2 = t0;
                    ret = Compiler_Emit_SUB(a0, a1, a2, a3);
                    a0 = *(u32*)(s1 + 0x28);  /* GTE data: ir2 */
                    a1 = ret;
                    s0 = Compiler_Emit_SB(a0, a1);
                    a0 = *(u32*)(__sp + 8);
                    goto loc_203280;
        }
                a1 = s0;
                a0 = a3;
                ret = Compiler_EncodeNegateOp(a0, a1);
                a0 = ret;
                ret = Compiler_Emit_JAL();
                s0 = ret;
                ret = ret & 0x20;
                if ((signed)s5 < (signed)s4) {
                    t0 = s0;
                    if (ret == 0) {
                        a1 = s0;
                        a2 = __sp + 0xc;
                        t0 = a1;
                        a0 = s2;
                        a3 = 0;
                        ret = Compiler_Emit_ADDI(a0, a1, a2, a3);
                        v1 = *(u32*)(s1 + 8);
                        a3 = ret;
                        a2 = 0;
                        a1 = *(u32*)(v1 + 0xc);  /* GTE data: vz1 */
                        a0 = s1 + 0x10;
                        ret = Compiler_EncodeLoadStoreAddressing(a0, a1, a2, a3);
                        a0 = *(u32*)(s1 + 0x28);  /* GTE data: ir2 */
                        a1 = ret;
                        ret = Compiler_Emit_ImmediateArith(a0, a1);
                        v1 = g_jit_cache;
                        a1 = 0;
                        a2 = ret;
                        a0 = *(u32*)(v1 + 8);
                        s0 = Compiler_Emit_SH(a0, a1, a2);
                        a0 = local_0C;
                        }
                        loc_203280:
                        a1 = s0;
                        ret = Compiler_Emit_SUBI(a0, a1);
                        ret = s0;
                    } else {
                        a0 = s2;
                        a1 = 0;
                        a2 = s1 + 0x10;
                        a3 = 0;
                        ret = Compiler_Emit_ADDI(a0, a1, a2, a3);
                        s0 = ret;
                        }
                        *(u32*)(s1) = ret | 0x10;
                        } else {
                        a1 = s0;
                        a0 = s2;
                        t0 = a1;
                        a2 = __sp + 0x10;
                        a3 = 0;
                        ret = Compiler_Emit_ADDI(a0, a1, a2, a3);
                        a0 = *(u32*)(s1 + 0x28);  /* GTE data: ir2 */
                        a1 = ret;
                        ret = Compiler_Emit_SB(a0, a1);
                        s0 = ret;
                        a0 = local_10;
                        a1 = s0;
                        ret = Compiler_Emit_SUBI(a0, a1);
                        }
                        }
                        loc_2032EC:
                        ret = s0;
                    }
    return ret;
}

/* Function at 0x00203318 - 0x00203440 */
u32 R3000_EmitJump(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    s0 = a3;
    ret = *(u32*)(s0);
    v1 = ret & 0x20;
    ret = ret & 0x100;
    s1 = a2;
    if (ret != 0) {
        if ((*(u32*)(s0 + 0x14)) != 0x100) goto loc_203428;  /* GTE data: vz2 */
        a0 = a0 + a1;
        a1 = 0x1f;
        a2 = t0;
        a0 = a0 + 8;
        ret = Compiler_Emit_LH(a0, a1, a2);
        t0 = ret;
        goto loc_203424;
    }
    ret = a0 + a1;
    if (v1 != 0) {
        v1 = *(u32*)(s0 + 0x28);  /* GTE data: ir2 */
        a1 = t0;
        if ((unsigned)ret >= (unsigned)v1) {
            a0 = s1;
            ret = Compiler_EncodeNegateOp(a0, a1);
            a0 = ret;
            ret = Compiler_Emit_JAL();
            v1 = *(u32*)(s0 + 8);
            a3 = ret;
            a2 = 0;
            a1 = *(u32*)(v1 + 0xc);  /* GTE data: vz1 */
            a0 = s0 + 0x10;
            ret = Compiler_EncodeLoadStoreAddressing(a0, a1, a2, a3);
            a0 = *(u32*)(s0 + 0x28);  /* GTE data: ir2 */
            a1 = ret;
            ret = Compiler_Emit_ImmediateArith(a0, a1);
            v1 = g_jit_cache;
            a2 = ret;
            a1 = 0;
            a0 = *(u32*)(v1 + 8);
            ret = Compiler_Emit_SH(a0, a1, a2);
            t0 = ret;
        } else {
            a0 = t0;
            ret = Compiler_Emit_JAL();
            a0 = 0;
            a3 = ret;
            a1 = s0 + 0x10;
            a2 = s1;
            ret = Compiler_Emit_LB(a0, a1, a2, a3);
            t0 = ret;
            *(u32*)(s0) = ret | 0x10;
            } else {
            a1 = t0;
            a0 = s1;
            ret = Compiler_EncodeNegateOp(a0, a1);
            a0 = *(u32*)(s0 + 0x28);  /* GTE data: ir2 */
            a1 = ret;
            t0 = Compiler_Emit_SB(a0, a1);
            }
        }
loc_203424:
loc_203428:
    return t0;
}

/* Function at 0x00203440 - 0x002034E8 */
u32 R3000_EmitJumpRegister(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    s0 = a3;
    s1 = a2;
    a3 = a0;
    ret = ret & 0x100;
    a0 = t0;
    if (ret != 0) {
        v1 = *(u32*)(s0 + 0x14);  /* GTE data: vz2 */
        ret = 0x100;
        a0 = *(u32*)(s0 + 0x18);  /* GTE data: rgbc */
        if (v1 == ret) {
            a0 = a3 + a1;
            a1 = *(u32*)(s0 + 0x20);  /* GTE data: ir0 */
            a2 = t0;
            a0 = a0 + 8;
            t0 = Compiler_Emit_LH(a0, a1, a2);
            a0 = *(u32*)(s0 + 0x18);  /* GTE data: rgbc */
        }
        a1 = t0;
        ret = Compiler_Emit_IndirectJump(a0, a1);
        t0 = ret;
    } else {
        ret = Compiler_Emit_JAL();
        v1 = g_jit_cache;
        a3 = ret;
        a1 = 0;
        a0 = *(u32*)(v1 + 0x10);  /* GTE data: vxy2 */
        a2 = s1;
        t0 = Compiler_Emit_LB(a0, a1, a2, a3);
    }
    return t0;
}

/* Function at 0x002034E8 - 0x00203550 */
u32 R3000_EmitGTEDataRead(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    a2 = t0;
    a1 = *(u32*)(a3 + 0x20);  /* GTE data: ir0 */
    s0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
    a1 = a1 << 2;
    a0 = s0;
    a1 = a1 + 0x90;
    if (s0 != 0) {
        ret = Compiler_Emit_MemoryLoadALU(a0, a1, a2);
        v1 = g_jit_state;
        t0 = ret;
        ret = ~(0 | ret);
        g_jit_state = v1 & ret;
    }
    return t0;
}

/* Function at 0x00203550 - 0x00203598 */
u32 R3000_EmitGTEDataWrite(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, s0, t0;
    a2 = t0;
    s0 = a3;
    a0 = 0;
    a1 = *(u32*)(s0 + 0x1c);  /* GTE data: otz */
    a1 = a1 << 2;
    a1 = a1 + 0x90;
    ret = Compiler_Emit_GTEOperation(a0, a1, a2);
    a0 = *(u32*)(s0 + 0x18);  /* GTE data: rgbc */
    a1 = *(s16*)(s0 + 0x10);  /* GTE data: vxy2 */
    a2 = ret;
    return Compiler_Emit_CoprocessorMove(a0, a1, a2);
}

/* Function at 0x00203598 - 0x00203628 */
u32 R3000_EmitGTEControlRead(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    a2 = t0;
    v1 = *(u32*)(a3 + 0x20);  /* GTE data: ir0 */
    s0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
    ret = v1 << 2;
    s1 = ret + 0x1b0;
    if (s0 != 0) {
        ret = 0x1d;
        a1 = s1;
        if (v1 == ret) {
            ret = g_jit_cache;
            a1 = 0;
            a0 = *(u32*)(ret + 0x2c);  /* GTE data: ir3 */
            a2 = Compiler_EmitCoprocessorOp(a0, a1, a2);
            a1 = s1;
        }
        a0 = s0;
        ret = Compiler_Emit_MemoryLoadALU(a0, a1, a2);
        v1 = g_jit_state;
        a2 = ret;
        ret = ~(0 | ret);
        g_jit_state = v1 & ret;
    }
    return a2;
}

/* Function at 0x00203628 - 0x00203778 */
u32 R3000_EmitGTEControlWrite(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 96 bytes */
    u32 ret, v1, s0, s1, s2, t0, t1, t2, t3, t4, t5;
    a2 = t0;
    ret = a2;
    t0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
    v1 = *(u32*)(a3);
    a0 = t0 << 2;
    s0 = *(u32*)(a3 + 0x18);  /* GTE data: rgbc */
    v1 = v1 & 0x2000;
    s1 = a0 + 0x1b0;
    s2 = *(s16*)(a3 + 0x10);  /* GTE data: vxy2 */
    if (v1 != 0) goto loc_20375C;
    t3 = 0;
    t5 = 0x3a;
    t4 = 0x1d;
    t2 = __sp + 0x14;
    do {
        ret = ret & 0x1004;
        v1 = 0;
        if (ret == 0) {
            ret = ret & 0x200;
            v1 = ((unsigned)ret < 1) ? 1 : 0;
        }
        t1 = a3 + 0x30;
        if (v1 == 0) goto loc_2036F4;
        ret = *(u32*)(a3 + 0x44);  /* GTE data: sz1 */
        a0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
        v1 = *(u32*)(a3 + 0x48);  /* GTE data: sz2 */
        if (ret != t5) goto loc_2036F4;
        if (s0 != v1) goto loc_2036F4;
        if (a0 == t4) goto loc_2036F4;
        ret = *(u32*)(a3 + 0x4c);  /* GTE data: sz3 */
        t3 = t3 + 1;
        v1 = *(u32*)(t1);
        a1 = ((unsigned)t3 < 4) ? 1 : 0;
        ret = ret + 0x1b0;
        v1 = v1 | 0x2000;
        *(u32*)(t2 + -4) = ret;
        a0 = *(s16*)(a3 + 0x40);  /* GTE data: sz0 */
        a3 = t1;
        *(u32*)(t1) = v1;
        *(u32*)(t2) = a0;
        t2 = t2 + 0xc;
    } while (a1 != 0);
loc_2036F4:
    a3 = a2;
    if (t3 != 0) {
        a2 = __sp;
        a0 = t3 + 1;
        a1 = s0;
        *(u32*)(__sp + 4) = s1;
        *(u32*)(__sp + 8) = s2;
        ret = Compiler_EmitStoreOpcode(a0, a1, a2, a3);
        goto loc_203760;
    }
    ret = 0x1d;
    a1 = s1;
    if (t0 == ret) {
        ret = g_jit_cache;
        a1 = 0;
        a0 = *(u32*)(ret + 0x2c);  /* GTE data: ir3 */
        a2 = Compiler_EmitCoprocessorOp(a0, a1, a2);
        a1 = s1;
    }
    a0 = 0;
    ret = Compiler_Emit_GTEOperation(a0, a1, a2);
    a0 = s0;
    a1 = s2;
    a2 = ret;
    ret = Compiler_Emit_CoprocessorMove(a0, a1, a2);
loc_20375C:
loc_203760:
    return ret;
}

/* Function at 0x00203778 - 0x002037E0 */
u32 R3000_EmitGTEDataReadAlt(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    a2 = t0;
    a1 = *(u32*)(a3 + 0x20);  /* GTE data: ir0 */
    s0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
    a1 = a1 << 2;
    a0 = s0;
    a1 = a1 + 0x230;
    if (s0 != 0) {
        ret = Compiler_Emit_MemoryLoadALU(a0, a1, a2);
        v1 = g_jit_state;
        t0 = ret;
        ret = ~(0 | ret);
        g_jit_state = v1 & ret;
    }
    return t0;
}

/* Function at 0x002037E0 - 0x002038D0 */
u32 R3000_EmitSyscall(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, t0;
    s1 = a3;
    s2 = a2;
    s3 = a0;
    s4 = a1;
    a2 = t0;
    a0 = 2;
    a1 = *(u32*)(s1 + 0x1c);  /* GTE data: otz */
    s0 = *(u32*)(s1 + 0x20);  /* GTE data: ir0 */
    ret = Compiler_Emit_LoadIndexed(a0, a1, a2);
    a0 = 1;
    a2 = ret;
    a1 = s0;
    ret = Compiler_Emit_BiImmediate(a0, a1, a2);
    v1 = g_jit_cache;
    a2 = ret;
    a1 = 0;
    a0 = *(u32*)(v1 + 0x20);  /* GTE data: ir0 */
    ret = Compiler_EmitCoprocessorOp(a0, a1, a2);
    a0 = 2;
    a1 = ret;
    ret = Compiler_Emit_LUI(a0, a1);
    a1 = ret;
    if (s0 != 0xc) goto loc_2038AC;
    ret = ret & 4;
    if (ret != 0) goto loc_2038AC;
    a0 = s2;
    ret = Compiler_EncodeNegateOp(a0, a1);
    a0 = s3 + s4;
    a1 = ret;
    a0 = a0 + 4;
    ret = Compiler_Emit_ImmediateArith(a0, a1);
    a0 = ret;
    ret = Compiler_Emit_JAL();
    v1 = g_jit_cache;
    a1 = 0;
    a2 = ret;
    a0 = *(u32*)(v1 + 0xc);  /* GTE data: vz1 */
    a1 = Compiler_Emit_SH(a0, a1, a2);
loc_2038AC:
    return a1;
}

/* Function at 0x002038D0 - 0x00203938 */
u32 R3000_EmitBreak(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, s0, t0;
    ret = a3;
    a0 = 2;
    a3 = t0;
    a2 = *(s16*)(ret + 0x10);  /* GTE data: vxy2 */
    a1 = *(u32*)(ret + 0x18);  /* GTE data: rgbc */
    s0 = *(u32*)(ret + 0x1c);  /* GTE data: otz */
    ret = Compiler_Emit_BranchLinkage(a0, a1, a2, a3);
    a0 = 1;
    a1 = s0;
    a2 = ret;
    ret = Compiler_Emit_BiImmediate(a0, a1, a2);
    v1 = g_jit_cache;
    a2 = ret;
    a1 = 0;
    a0 = *(u32*)(v1 + 0x20);  /* GTE data: ir0 */
    ret = Compiler_EmitCoprocessorOp(a0, a1, a2);
    a0 = 2;
    a1 = ret;
    return Compiler_Emit_LUI(a0, a1);
}

/* Function at 0x00203938 - 0x00203A18 */
u32 R3000_EmitCOP0Op(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1, t0;
    ret = a3;
    a3 = t0;
    s0 = *(u32*)(ret + 0x20);  /* GTE data: ir0 */
    s1 = *(u32*)(ret + 0x1c);  /* GTE data: otz */
    a2 = s0 << 2;
    a0 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    a0 = a0 + a2;
    a0 = *(u32*)(a0 + -0x5710);
    a2 = a2 + 0x1b0;
    a1 = s1;
    ret = Compiler_Emit_MemoryStoreALU(a0, a1, a2, a3);
    a1 = 0;
    a0 = ret;
    ret = 0x1c;
    a2 = a0;
    v1 = ((unsigned)s0 < 0x1d) ? 1 : 0;
    if (s0 != ret) {
        ret = 0x1e;
        if (v1 != 0) {
            if (s0 != 0xf) {
                ret = a0;
                } else {
                if (s0 != ret) {
                    ret = a0;
                    } else {
                    ret = Compiler_Emit_ShiftOp(a0);
                    a0 = ret;
                    } else {
                    ret = g_jit_cache;
                    a0 = *(u32*)(ret + 0x30);  /* GTE data: sxy0 */
                    a0 = Compiler_EmitCoprocessorOp(a0, a1, a2);
                    goto loc_2039FC;
                }
                a2 = a0;
                a0 = 0;
                a1 = s1;
                ret = Compiler_Emit_LoadIndexed(a0, a1, a2);
                a0 = ret;
                ret = Compiler_Emit_MultiplyDivide(a0);
                a0 = ret;
                }
                loc_2039FC:
                ret = a0;
                }
            }
    return ret;
}

/* Function at 0x00203A18 - 0x00203BF8 */
u32 R3000_EmitCOP0OpWrite(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 112 bytes */
    u32 ret, v1, s0, s1, s2, s3, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    ret = t0;
    s0 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
    v1 = *(u32*)(a3);
    t4 = s0 << 2;
    t3 = *(u32*)(a3 + 0x18);  /* GTE data: rgbc */
    v1 = v1 & 0x2000;
    t6 = t4 + 0x1b0;
    t5 = *(s16*)(a3 + 0x10);  /* GTE data: vxy2 */
    if (v1 != 0) goto loc_203BD8;
    s3 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    t2 = 0;
    s2 = 0x32;
    s1 = 0x1e;
    t9 = 0x1c;
    t8 = 0xf;
    t7 = s3 + -0x5710;
    t1 = __sp + 0x14;
    do {
        ret = ret & 0x1004;
        v1 = 0;
        if (ret == 0) {
            ret = ret & 0x200;
            v1 = ((unsigned)ret < 1) ? 1 : 0;
        }
        a2 = a3 + 0x30;
        if (v1 == 0) goto loc_203B10;
        ret = *(u32*)(a3 + 0x44);  /* GTE data: sz1 */
        v1 = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
        a0 = *(u32*)(a3 + 0x48);  /* GTE data: sz2 */
        if (ret != s2) goto loc_203B10;
        ret = s3 + -0x5710;
        if (t3 != a0) goto loc_203B14;
        if (v1 == s1) goto loc_203B14;
        ret = t4 + ret;
        if (v1 == t9) goto loc_203B18;
        if (v1 == t8) goto loc_203B18;
        ret = *(u32*)(a3 + 0x4c);  /* GTE data: sz3 */
        t2 = t2 + 1;
        a0 = *(u32*)(a2);
        a1 = ((unsigned)t2 < 4) ? 1 : 0;
        ret = ret << 2;
        v1 = ret + t7;
        ret = ret + 0x1b0;
        v1 = *(u32*)(v1);
        a0 = a0 | 0x2000;
        *(u32*)(t1 + -4) = ret;
        *(u32*)(t1 + -8) = v1;
        ret = *(s16*)(a3 + 0x40);  /* GTE data: sz0 */
        a3 = a2;
        *(u32*)(a2) = a0;
        *(u32*)(t1) = ret;
        t1 = t1 + 0xc;
    } while (a1 != 0);
loc_203B10:
    ret = s3 + -0x5710;
loc_203B14:
    ret = t4 + ret;
loc_203B18:
    v1 = *(u32*)(ret);
    if (t2 != 0) {
        a0 = t2 + 1;
        a1 = t3;
        a3 = t0;
        a2 = __sp;
        *(u32*)(__sp) = v1;
        *(u32*)(__sp + 4) = t6;
        *(u32*)(__sp + 8) = t5;
        ret = Compiler_EmitLoadOpcode(a0, a1, a2, a3);
    } else {
        a0 = v1;
        a1 = t3;
        a2 = t5;
        a3 = t6;
        ret = Compiler_EmitSpecialOp(a0, a1, a2, a3);
        t0 = ret;
        ret = ((unsigned)s0 < 0x1d) ? 1 : 0;
        if (s0 != ret) {
            ret = t0;
            if (s0 != ret) {
                } else {
                ret = t0;
                if (s0 != ret) {
                    } else {
                    a0 = t0;
                    ret = Compiler_Emit_ShiftOp(a0);
                    t0 = ret;
                    } else {
                    ret = g_jit_cache;
                    a2 = t0;
                    a1 = 0;
                    a0 = *(u32*)(ret + 0x30);  /* GTE data: sxy0 */
                    t0 = Compiler_EmitCoprocessorOp(a0, a1, a2);
                    goto loc_203BD4;
                }
                a0 = t0;
                ret = Compiler_Emit_MultiplyDivide(a0);
                t0 = ret;
                }
                loc_203BD4:
                ret = t0;
                loc_203BD8:
                    }
                }
    return ret;
}

/* Function at 0x00203BF8 - 0x00203C30 */
u32 R3000_EmitCOP2DataReadAlt(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, t0;
    ret = a3;
    a3 = t0;
    a2 = *(u32*)(ret + 0x20);  /* GTE data: ir0 */
    a1 = *(u32*)(ret + 0x1c);  /* GTE data: otz */
    a2 = a2 << 2;
    a0 = 0x00250000;  /* JIT_CODE_CACHE: JIT compiled code cache */
    a0 = a0 + a2;
    a0 = *(u32*)(a0 + -0x5690);
    a2 = a2 + 0x230;
    return Compiler_Emit_MemoryStoreALU(a0, a1, a2, a3);
}

/* Function at 0x00203C30 - 0x00203C80 */
u32 R3000_EmitExceptionReturn(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, t0;
    a1 = 0x01FFFFFF;
    a2 = t0;
    a0 = 1;
    ret = *(u32*)(a3 + 0x10);  /* GTE data: vxy2 */
    a1 = ret & a1;
    ret = Compiler_Emit_BiImmediate(a0, a1, a2);
    v1 = g_jit_cache;
    a2 = ret;
    a1 = 1;
    a0 = *(u32*)(v1 + 0x24);  /* GTE data: ir1 */
    ret = Compiler_EmitCoprocessorOp(a0, a1, a2);
    a0 = 1;
    a1 = ret;
    return Compiler_Emit_LUI(a0, a1);
}

/* Function at 0x00203C80 - 0x00203CA0 */
u32 R3000_EmitSyscallImmediate(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 16 bytes */
    u32 t0;
    a1 = t0;
    a0 = *(u32*)(a3 + 0x10);  /* GTE data: vxy2 */
    return Compiler_Emit_LW(a0, a1);
}

/* Function at 0x00203CA0 - 0x00203EC8 */
u32 R3000_EmitMemoryAccess(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 144 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, t0, t1, t2, t3, t4, t5, t6, t7;
    ret = g_psx;
    s1 = a3;
    s2 = t0;
    v1 = *(u32*)(s1);
    a0 = *(s16*)(ret + 0xc2);
    ret = s2;
    t4 = *(u32*)(s1 + 0x14);  /* GTE data: vz2 */
    v1 = v1 & 0x2000;
    t3 = a0 & 1;
    a1 = *(u32*)(s1 + 0x18);  /* GTE data: rgbc */
    s3 = *(u32*)(s1 + 0x1c);  /* GTE data: otz */
    s4 = t4 & 8;
    t5 = *(s16*)(s1 + 0x10);  /* GTE data: vxy2 */
    if (v1 != 0) goto loc_203EA4;
    ret = g_jit_state;  /* lwu */
    if (s4 != 0) {
        if (t3 != 0) goto loc_203EA8;
        ret = g_jit_state;  /* lwu */
    }
    ret = (s64)ret >> 32;
    v1 = g_jit_state;
    if (ret != 0) {
        ret = a1 << 2;
        s0 = 0x00500000;
        s0 = s0 + ret;
        s0 = *(u32*)(s0 + 0x6b80);
        s0 = s0 + t5;
        a0 = s0;
        ret = R3000_ClassifyAddress(a0);
        a0 = *(u32*)(s1 + 0x14);  /* GTE data: vz2 */
        t0 = s2;
        a2 = ret;
        a3 = s0;
        a1 = s3;
        s2 = Compiler_EmitLogicalOp(a0, a1, a2, a3);
        goto loc_203E74;
    }
    t2 = v1;
    a3 = s1;
    a0 = 0;
    t7 = 0x20;
    t6 = 1;
    a2 = __sp + 0x14;
    goto loc_203DF8;
loc_203D80:
    v1 = *(u32*)(a3 + 0x48);  /* GTE data: sz2 */
    ret = t1 & 0xfff0;
    t0 = *(u32*)(a3 + 0x4c);  /* GTE data: sz3 */
    if (ret != t7) goto loc_203E28;
    ret = t1 & 8;
    if (a1 != v1) goto loc_203E28;
    if (ret == 0) {
        ret = *(u32*)(a3 + 0x1c);  /* GTE data: otz */
        if (a1 == ret) goto loc_203E28;
        ret = t6 << t0;
        if (t0 != 0) {
            ret = ~(0 | ret);
            t2 = t2 & ret;
            } else {
            if (t3 != 0) goto loc_203E28;
            }
        }
    ret = *(u32*)(a3 + 0x30);  /* GTE data: sxy0 */
    a0 = a0 + 1;
    v1 = *(s16*)(a3 + 0x40);  /* GTE data: sz0 */
    ret = ret | 0x2000;
    *(u32*)(a2 + -8) = t1;
    *(u32*)(a2 + -4) = t0;
    *(u32*)(a2) = v1;
    a2 = a2 + 0xc;
    *(u32*)(a3 + 0x30) = ret;
    a3 = a3 + 0x30;
loc_203DF8:
    if ((unsigned)a0 >= 7) goto loc_203E28;
    ret = ret & 0x1004;
    v1 = 0;
    if (ret == 0) {
        ret = ret & 0x200;
        v1 = ((unsigned)ret < 1) ? 1 : 0;
    }
    t1 = *(u32*)(a3 + 0x44);  /* GTE data: sz1 */
    if (v1 != 0) goto loc_203D80;
loc_203E28:
    g_jit_state = t2;
    if (a0 != 0) {
        a3 = s2;
        a0 = a0 + 1;
        a2 = __sp;
        *(u32*)(__sp) = t4;
        *(u32*)(__sp + 8) = t5;
        *(u32*)(__sp + 4) = s3;
        s2 = Compiler_EmitComparison(a0, a1, a2, a3);
        goto loc_203E74;
    }
    a2 = a1;
    a1 = s3;
    t0 = s2;
    a0 = t4;
    a3 = t5;
    ret = Compiler_EmitArithmetic(a0, a1, a2, a3);
    s2 = ret;
loc_203E74:
    ret = s2;
    if (s4 != 0) goto loc_203EA4;
    ret = 1;
    if (s3 != 0) {
        v1 = g_jit_state;
        ret = ~(0 | ret);
        g_jit_state = v1 & ret;
    }
    ret = s2;
loc_203EA4:
loc_203EA8:
    return ret;
}

/* Function at 0x00203EC8 - 0x00203F30 */
u32 R3000_FlushPendingStores(u32 a0)
{
    /* Stack frame: 32 bytes */
    u32 ret, a1, a2, a3, s0, s1;
    s0 = 0x00500000 + 0x3b20;
    s1 = a0;
    if ((unsigned)s1 >= (unsigned)s0) {
        ret = *(u32*)(s0);
        do {
            ret = ret & 0x10;
            s0 = s0 + 0x30;
            if (ret != 0) {
                ret = *(u32*)(s0 + 8);
                a0 = *(u32*)(s0 + 0x10);  /* GTE data: vxy2 */
                a1 = *(u32*)(ret + 0xc);  /* GTE data: vz1 */
                ret = Compiler_Emit_SUBI(a0, a1);
                s0 = s0 + 0x30;
            }
            ret = *(u32*)(s0);
        } while (ret == 0);
    }
    return ret;
}

/* Function at 0x00203F30 - 0x002040F8 */
u32 R3000_BuildBlockDescriptor(u32 a0, u32 a1, u32 a2, u32 a3)
{
    u32 ret, v1, t0, t1, t2, t3, t4, t5, t6, t7;
    t5 = *(u32*)(a3 + 0x30);  /* GTE data: sxy0 */
    t3 = a0;
    ret = t5 & 0x200;
    t7 = 0;
    if (ret != 0) goto loc_204020;
    t6 = 0x00500000;
    v1 = t6 + 0x3b20;
    ret = 0xAAAAAAAB;
    v1 = (signed)v1 >> 2;
    a0 = (s32)((s64)v1 * (s64)ret); HI_LO = (s64)v1 * (s64)ret;
    t4 = a0 + a1;
    a0 = t4 + 8;
    if (t3 == a0) {
        v1 = 0xd;
        ret = (u32)R3000_EmitALUOp;
        *(u32*)(a3 + 0x14) = v1;
        *(u32*)(a3 + 0x2c) = ret;
        ret = 0;
        *(u32*)(a3 + 0x10) = 0;
        *(u32*)(a3 + 0x18) = 0;
        *(u32*)(a3 + 0x1c) = 0;
        *(u32*)(a3 + 0x20) = 0;
        *(u32*)(a3 + 0x24) = 0;
        *(u32*)(a3 + 0x28) = 0;
        return ret;
    }
    a0 = a3 + 0x60;
    if (t1 == 0) goto loc_203FC4;
    v1 = *(u32*)(a3 + 0x60);  /* GTE data: mac0 */
    ret = *(u32*)(t0);
    *(u32*)(a3 + 0x60) = v1 | 0x400;
    if ((unsigned)ret >= (unsigned)a0) goto loc_203FC4;
    *(u32*)(t0) = a0;
loc_203FC4:
    a0 = *(u32*)(a3);
    if ((unsigned)t3 < (unsigned)a1) goto loc_2040B4;
    a0 = *(u32*)(a3);
    if ((unsigned)t3 >= (unsigned)a2) goto loc_2040B4;
    ret = t4 + 4;
    v1 = t3 - a1;
    if (t3 != ret) {
        a1 = t6 + 0x3b20;
        v1 = (unsigned)v1 >> 2;
        a0 = *(u32*)(t0);
        ret = ret << 4;
        a1 = ret + a1;
        a0 = ((unsigned)a0 < (unsigned)a1) ? 1 : 0;
        *(u32*)(t0) = a1;
        if (a0 != 0) goto loc_204010;
        loc_204010:
        ret = ret & 4;
        *(u32*)(a3 + 0x2c) = t2;
        if (ret != 0) {
            loc_204020:
            v1 = *(u32*)(a3);
            ret = (u32)R3000_HandleBranchBlock;
            v1 = v1 | 0x5000;
            *(u32*)(a3 + 0x2c) = ret;
            *(u32*)(a3) = v1;
        } else {
            a2 = a3 + 0x30;
            ret = *(u32*)(a3);
            a0 = t5 | 4;
            v1 = *(u32*)(t0);
            ret = ret | 0x22;
            *(u32*)(a3 + 0x30) = a0;
            v1 = ((unsigned)v1 < (unsigned)a2) ? 1 : 0;
            *(u32*)(a3) = ret;
            if (v1 != 0) {
                *(u32*)(t0) = a2;
            }
            ret = ret | 0x200;
            *(u32*)(a1) = ret;
            if (t1 != 0) goto loc_2040A0;
            ret = *(u32*)(a3);
            v1 = *(u32*)(t0);
            ret = ret | 0x800;
            *(u32*)(a3) = ret;
            v1 = ((unsigned)v1 < (unsigned)a2) ? 1 : 0;
            *(u32*)(a2) = ret | 0x1000;
            if (v1 == 0) goto loc_2040A0;
            *(u32*)(t0) = a2;
            loc_2040A0:
            *(u32*)(a3 + 8) = a1;
            t7 = 1;
            } else {
            a0 = *(u32*)(a3);
            loc_2040B4:
            v1 = t5 | 4;
            *(u32*)(a3 + 0x2c) = t2;
            ret = a0 | 2;
            *(u32*)(a3 + 0x30) = v1;
            *(u32*)(a3) = ret;
            if (t1 != 0) goto loc_2040F0;
            ret = *(u32*)(t0);
            a1 = a3 + 0x30;
            v1 = a0 | 0x802;
            a0 = t5 | 0x1004;
            *(u32*)(a3) = v1;
            *(u32*)(a3 + 0x30) = a0;
            if ((unsigned)ret >= (unsigned)a1) goto loc_2040F0;
            *(u32*)(t0) = a1;
            }
        }
loc_2040F0:
    return t7;
}

/* Function at 0x002040F8 - 0x00204928 */
void R3000_DecodeInstruction(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 80 bytes */
    u32 ret, v1, s0, s1, s2, s3, s4, s5, s6, s7, t0, t1, t2;
    ret = g_psx;
    s0 = a3;
    s2 = a0;
    s3 = t1;
    s4 = a1;
    s5 = a2;
    s6 = t0;
    v1 = v1 << 4;
    a1 = *(u32*)(ret + 0x2e0);  /* counter_misc[0] */
    v1 = a1 + v1;
    ret = *(u32*)(v1 + 8);
    s7 = 0;
    if (ret != 0) {
        a1 = 4;
        ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
        a1 = ret;
    } else {
        ret = *(u32*)(v1 + 4);
        v1 = *(u32*)(v1);
        ret = s2 & ret;
        v1 = v1 + ret;
        a1 = *(u32*)(v1);
    }
    a3 = (unsigned)a1 >> 0x1a;
    ret = (unsigned)a1 >> 0x15;
    v1 = (unsigned)a1 >> 0xb;
    a0 = (unsigned)a1 >> 0x10;
    a2 = ret & 0x1f;
    ret = 1;
    t0 = v1 & 0x1f;
    v1 = ((unsigned)a3 < 0x3b) ? 1 : 0;
    s1 = a0 & 0x1f;
    *(u32*)(s0 + 4) = ret;
    *(u32*)(s0 + 0x10) = a1;
    *(u32*)(s0 + 0x1c) = s1;
    *(u32*)(s0 + 0x18) = a2;
    *(u32*)(s0 + 0x20) = t0;
    *(u32*)(s0 + 0x14) = a3;
    *(u32*)(s0 + 0x24) = 0;
    if (v1 == 0) R3000_DecodeInstruction(a0, a1, a2, a3); return;
    ret = a3 << 2;
    v1 = *(u32*)(v1 + -0x6eb0);
    goto *v1; /* computed jump */
    a1 = a1 & 0x3f;
    ret = a1 + 0x40;
    v1 = ((unsigned)a1 < 0x2c) ? 1 : 0;
    *(u32*)(s0 + 0x14) = ret;
    if (v1 == 0) R3000_DecodeInstruction(a0, a1, a2, a3); return;
    ret = a1 << 2;
    v1 = *(u32*)(v1 + -0x6dc0);
    goto *v1; /* computed jump */
    *(u32*)(s0 + 0x24) = t0;
    *(u32*)(s0 + 0x2c) = R3000_EmitDelaySlot;
    R3000_DecodeInstruction(a0, a1, a2, a3); return;
        v1 = v1 << 8;
        ret = (u32)R3000_EmitJumpRegister;
        *(u32*)(s0 + 0x14) = v1;
        *(u32*)(s0 + 0x2c) = ret;
        a2 = s0 + 0x30;
        v1 = *(u32*)(s0);
        a0 = a0 | 0x1004;  /* PSX_MEM_CTRL: Memory Control registers (0x1F801004) */
        ret = *(u32*)(s6);
        v1 = v1 | 0x802;
        *(u32*)(s0 + 0x30) = a0;
        *(u32*)(s0) = v1;
        if ((unsigned)ret < (unsigned)a2) {
            *(u32*)(s6) = a2;
            }
    ret = a1 ^ 8;
    v1 = 0;
    if (ret != 0) v1 = t0;
    *(u32*)(s0 + 0x24) = v1;
    goto loc_2048F8;
    ret = 0x205;
    if (a2 != 0) goto loc_2043A8;
    ret = 1;
    if (s1 != 0x205) goto loc_2043A8;
    *(u32*)(s0 + 0x14) = 0;
    a1 = s4;
    a2 = s5;
    a0 = *(u32*)(s3);
    a3 = s0;
    t0 = s6;
    t2 = (u32)R3000_EmitJump;
    t1 = 0;
    goto loc_20462C;
loc_2043A8:
    v1 = 0x202;
    if (s1 != 0) v1 = ret;
    *(u32*)(s0 + 0x20) = 0;
    *(u32*)(s0 + 0x14) = v1;
    t2 = 0x00200000;
    *(u32*)(s0 + 0x1c) = 0;
    a1 = s4;
    a2 = s5;
    a3 = s0;
    a0 = *(u32*)(s3);
    t0 = s6;
    goto loc_204624;
        ret = 0x202;
        v1 = 0x1f;
        if (a1 != 0) ret = a0;
        a1 = s4;
        *(u32*)(s0 + 0x20) = v1;
        *(u32*)(s0 + 0x14) = ret;
        a2 = s5;
        *(u32*)(s0 + 0x1c) = 0;
        t0 = s6;
        t2 = (u32)R3000_EmitBranch;
        a3 = s0;
        a0 = *(u32*)(s3);
        t1 = 1;
        s7 = R3000_BuildBlockDescriptor(a0, a1, a2, a3);
    *(u32*)(s0 + 0x24) = 0x1f;
    goto loc_2048F8;
        a3 = s0;
        v1 = 0x206;
        ret = 0x201;
        if (a0 != 0) ret = v1;
        *(u32*)(s0 + 0x20) = 0;
        *(u32*)(s0 + 0x14) = ret;
        t2 = 0x00200000;
        a1 = s4;
        a2 = s5;
        a0 = *(u32*)(s3);
        t0 = s6;
        goto loc_204624;
            a3 = s0;
            if (a0 != 0) 0x203 = 0x204;
            *(u32*)(s0 + 0x20) = 0;
            *(u32*)(s0 + 0x1c) = 0;
            t2 = 0x00200000;
            *(u32*)(s0 + 0x14) = ret;
            a1 = s4;
            a2 = s5;
            t0 = s6;
            a0 = *(u32*)(s3);
            loc_204624:
            t2 = (u32)R3000_EmitBranch;
            t1 = 1;
loc_20462C:
    ret = R3000_BuildBlockDescriptor(a0, a1, a2, a3);
    s7 = ret;
    goto loc_2048F8;
    ret = *(u32*)(v1 + 4);
    v1 = *(u32*)(v1);
    ret = a1 & ret;
    v1 = v1 + ret;
    a0 = *(u32*)(v1);
    if (s2 == s4) goto loc_2046D8;
    ret = 0x800A50C8;
    if (s2 != 0x00200000) goto loc_2046D8;
    v1 = *(u32*)(s0);
    ret = v1 & 4;
    goto loc_2046D8;
loc_2046D8:
    ret = ret + 0x2cf0;
    *(u32*)(s0 + 0x2c) = ret;
    *(u32*)(s0 + 0x24) = s1;
    goto loc_2048F8;
                if (a2 != 0x00200000) {
                    goto loc_204790;
                    }
                    *(u32*)(s0 + 0x24) = s1;
                    *(u32*)(s0 + 0x2c) = R3000_EmitGTEDataRead;
                    } else {
                    ret = 0xc;
                    if (t0 != 0x00200000) goto loc_204770;
                    v1 = *(u32*)(s0);
                    ret = v1 & 4;
                    goto loc_204770;
                    loc_204770:
                    *(u32*)(s0 + 0x2c) = R3000_EmitSyscall;
                } else {
                    *(u32*)(s0 + 0x2c) = ret + 0x3c30;
                    goto loc_2048F8;
                    loc_204790:
                    BREAK(); /* breakpoint */
                    v1 = *(u32*)(s0);
                    *(u32*)(s0 + 0x2c) = R3000_HandleConditionalBranch;
                    v1 = v1 | 0x1000;
                    goto loc_2048F4;
                    loc_2047F8:
                    *(u32*)(s0 + 0x24) = s1;
                    *(u32*)(s0 + 0x2c) = R3000_EmitGTEControlRead;
                    goto loc_2048F8;
                    loc_2048D4:
                    *(u32*)(s0 + 4) = v1;
                    *(u32*)(s0 + 0x2c) = ret;
                    goto loc_2048F8;
                    loc_2048E0:
                    v1 = *(u32*)(s0);
                    loc_2048E4:
                    ret = (u32)R3000_HandleConditionalBranch;
                    v1 = v1 | 0x1000;
                    *(u32*)(s0 + 0x2c) = ret;
                    loc_2048F4:
                    *(u32*)(s0) = v1;
loc_2048F8:
    return;
}

/* Function at 0x00204928 - 0x00204A88 */
u32 R3000_TranslateBlockRange(u32 a0, u32 a1, u32 a2)
{
    /* Stack frame: 64 bytes */
    u32 ret, v1, a3, s0, s1, s2, s3, s4, t0, t1;
    s1 = a2;
    s3 = a0;
    v1 = (unsigned)v1 >> 2;
    a0 = 0x00503B20;
    ret = v1 << 1;
    a2 = 0x00200000;
    ret = ret << 4;
    *(u32*)(__sp) = a0;
    s0 = ret + a0;
    s2 = a1;
    s4 = a2 + 0x29c8;
    ret = *(u32*)(__sp);
    while (1) {
        a0 = ((unsigned)s1 < (unsigned)s2) ? 1 : 0;
        if ((((unsigned)ret < (unsigned)s0) ? 1 : 0) != 0) ret = s0;
        *(u32*)(__sp) = ret;
        if (a0 == 0) {
            a0 = *(u32*)(s0);
            ret = a0 | 0x5001;
            if (ret != 0) {
                ret = a0 & 1;
                if (ret == 0) {
                    ret = *(u32*)(s0 + 0x30);  /* GTE data: sxy0 */
                    a1 = s0 + 0x30;
                    v1 = ((unsigned)v1 < (unsigned)a1) ? 1 : 0;
                    *(u32*)(s0 + 0x5c) = s4;
                    *(u32*)(s0 + 0x30) = ret | 0x5001;
                    if (v1 != 0) {
                        *(u32*)(__sp) = a1;
                        } else {
                        *(u32*)(s0 + 0x2c) = s4;
                        *(u32*)(s0) = ret;
                        goto loc_204A60;
                        }
                        a0 = *(u32*)(s0);
                        }
                    }
                    ret = a0 & 1;
                }
        ret = *(u32*)(__sp);
        if (ret != 0) goto loc_204A64;
        ret = a0 | 1;
        a0 = s1;
        *(u32*)(s0) = ret;
        a1 = s3;
        a2 = s2;
        a3 = s0;
        t0 = __sp;
        t1 = __sp + 4;
        R3000_DecodeInstruction(a0, a1, a2, a3);
        a2 = *(u32*)(__sp + 4);
        if (ret != 0) {
            a0 = s3;
            a1 = s2;
            ret = R3000_TranslateBlockRange(a0, a1, a2);
            v1 = *(u32*)(__sp);
            if ((signed)v1 < (signed)ret) v1 = ret;
            *(u32*)(__sp) = v1;
        }
        if ((*(u32*)(__sp)) != 0) goto loc_204A64;
        s1 = s1 + 4;
        s0 = s0 + 0x30;
    }
loc_204A60:
    ret = *(u32*)(__sp);
loc_204A64:
    return ret;
}

/* Function at 0x00204A88 - 0x00204B78 */
u32 R3000_TranslateFromPC(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1;
    ret = g_psx;
    s0 = a0;
    v1 = v1 << 4;
    a1 = *(u32*)(ret + 0x2e0);  /* counter_misc[0] */
    v1 = a1 + v1;
    ret = *(u32*)(v1 + 8);
    s1 = g_hw_reg_base;
    if (ret != 0) {
        a1 = 4;
        ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
        v1 = ret;
        goto loc_204AE4;
    }
    ret = *(u32*)(v1 + 4);
    v1 = *(u32*)(v1);
    ret = s0 & ret;
    v1 = *(u32*)(v1);
loc_204AE4:
    ret = 0x3C028001;
    a0 = s0;
    if (v1 == ret) {
        ret = g_psx;
        a2 = s0 + 4;
        v1 = (unsigned)a2 >> 0x1c;
        a1 = *(u32*)(ret + 0x2e0);  /* counter_misc[0] */
        v1 = a1 + v1;
        ret = *(u32*)(v1 + 8);
        a0 = a2;
        if (ret != 0) {
            a1 = 4;
            ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
            a0 = ret;
        } else {
            ret = *(u32*)(v1 + 4);
            v1 = *(u32*)(v1);
            ret = a2 & ret;
            v1 = v1 + ret;
            a0 = *(u32*)(v1);
        }
        v1 = 1;
        ret = a0 ^ ret;
        if (ret == 0) s1 = v1;
        a0 = s0;
    }
    a1 = s1 << 2;
    a1 = a0 + a1;
    a2 = a0;
    return R3000_TranslateBlockRange(a0, a1, a2);
}

/* Function at 0x00204B78 - 0x00204C50 */
u32 R3000_TranslateAndCompile(u32 a0)
{
    /* Stack frame: 48 bytes */
    u32 ret, v1, a1, a2, a3, s0, s1, s2, t0, t1;
    s0 = a0;
    R3000_GetCodeCacheEntry();
    a0 = s0;
    if (s2 == 0) {
        a0 = 0x004F9370;
        ret = AssertionFailed(a0, a1, a2, a3);
        goto loc_204C38;
    }
    ret = R3000_TranslateFromPC(a0, a1, a2, a3);
    a0 = s0;
    s1 = ret;
    a3 = __sp;
    a1 = s1;
    t0 = __sp + 4;
    a2 = s2 + 0x1c;
    t1 = s2 + 0xc;
    ret = R3000_ExecuteBlocks(a0, a1, a2, a3);
    a0 = s1;
    ret = *(u16*)(__sp);
    s0 = 0x00503B20;
    *(u16*)(s2 + 0x14) = ret;
    *(u16*)(s2 + 0x16) = *(u16*)(__sp + 4);
    ret = R3000_FlushPendingStores(a0);
    a1 = 0x30;
    a1 = a1 - s0;
    a0 = s0;
    a1 = s1 + a1;
    s1 = s1 - s0;
    ret = Compiler_MemoryClear(a0, a1);
    s1 = (signed)s1 >> 2;
    ret = 0xAAAAAAAB;
    s1 = (s32)((s64)s1 * (s64)ret); HI_LO = (s64)s1 * (s64)ret;
    a0 = s2;
    a1 = s1 + 4;
    ret = R3000_CompileBlock(a0);
loc_204C38:
    return ret;
}

/* Function at 0x00204C50 - 0x00204D18 */
u32 R3000_ExecutionLoop(u32 a0, u32 a1, u32 a2, u32 a3)
{
    /* Stack frame: 32 bytes */
    u32 ret, v1, s0, s1;
    s1 = 1;
    a0 = g_psx;
loc_204C68:
    ret = *(u32*)(a0 + 0x2cc);  /* irq_pending */
    v1 = g_jit_cache;
    if (ret != 0) {
        *(u32*)(a0 + 0x2cc) = 0;  /* irq_pending (store) */
        a0 = 0;
        a1 = 0;
        ret = PSX_HandleException(a0, a1, a2, a3);
        a0 = g_psx;
        v1 = g_jit_cache;
    }
    ret = CALL_INDIRECT(ret)(a0, a1, a2, a3);
    s0 = ret;
    v1 = s0 + -1;
    s1 = 0;
    if ((unsigned)v1 >= 6) goto loc_204CF4;
    ret = v1 << 2;
    v1 = *(u32*)(v1 + -0x6c60);
    goto *v1; /* computed jump */
    ret = g_psx;
    a0 = *(u32*)(ret);
    ret = R3000_TranslateAndCompile(a0);
    goto loc_204CF4;
loc_204CF4:
    a0 = g_psx;
    if (s1 != 0) goto loc_204C68;
    return s0;
}

/* Function at 0x00204D18 - 0x00204D78 */
u32 R3000_ClassifyAddress(u32 a0)
{
    u32 ret, v1, a1, a2;
    ret = 0x1FFFFFFF;
    v1 = 0x007FFFFF;
    a2 = a0 & ret;
    v1 = ((unsigned)v1 < (unsigned)a2) ? 1 : 0;
    ret = 1;
    if (v1 == 0) goto loc_204D6C;
    v1 = ((unsigned)v1 < 0x400) ? 1 : 0;
    ret = 2;
    if (v1 != 0) goto loc_204D6C;
    v1 = 0x0007FFFF;
    a0 = a2 + a0;
    a1 = 4;
    ret = 3;
    if ((((unsigned)v1 < (unsigned)a0) ? 1 : 0) != 0) ret = a1;
loc_204D6C:
    return ret;
}

/* Function at 0x00204D78 - 0x00204E00 */
u32 R3000_UpdateBlockSize(u32 a0)
{
    /* Stack frame: 48 bytes */
    u32 ret, a1, a2, a3, s0, s1;
    s0 = a0;
    a1 = __sp + 4;
    a0 = __sp;
    s1 = s0;
    ret = R3000_GetCachePointers(a0, a1);
    ret = s1 - s0;
    if (ret == 0) goto loc_204DD8;
    ret = s1 - s0;
    if (ret == 0) goto loc_204DD8;
    ret = g_jit_cache;
    a1 = 0;
    a2 = s0;
    a0 = *(u32*)(ret + 0xc);  /* GTE data: vz1 */
    ret = Compiler_Emit_SH(a0, a1, a2);
    s1 = ret;
    ret = s1 - s0;
loc_204DD8:
    return ret;
}

/* Function at 0x00204E00 - 0x00204E30 */
u32 R3000_SetBlockSize(u32 a0, u32 a1)
{
    /* Stack frame: 16 bytes */
    u32 ret, v1, a2, a3;
    if (ret != 0) a1 = a0;
    if (a1 != v1) {
        g_hw_reg_base = a1;
        return R3000_InvalidateAllBlocks();
    }
    return ret;
}

/* Function at 0x00204E30 - 0x00204E38 */
u32 R3000_GetBlockSize(void)
{
    u32 ret;
    return g_hw_reg_base;
}

/* Function at 0x00204E38 - 0x00204E3C */
void R3000_GetCurrentBlock(void)
{
    u32 a0;
    a0 = g_jit_cache;
}

/* Function at 0x00204E3C - 0x00204E70 */
u32 R3000_ResetCompiler(void)
{
    /* Stack frame: 16 bytes */
    u32 ret, a0, a1, a2, a3;
    ret = Compiler_Emit_NoOp();
    a0 = 0x00503B20;
    a1 = 0;
    a2 = 0x3060;
    ret = Libc_Memset(a0, a1, a2);
    return R3000_GetCacheBase();
}
