/* POPS.ELF Decompiled - spu.c */
/* Auto-generated by POPS Decompiler */
/* 19 functions */

#include "pops_types.h"

/* Forward declarations */
int SPU_Init();
int SPU_RegisterIO();
int SPU_ProcessSamples();
int SPU_AllocBuffers();
int SPU_FreeBuffers();
int SPU_Start();
int SPU_Stop();
int SPU_SetVoiceVolume();
int SPU_GetWritePtr();
int SPU_AdvanceReadPtr();
int SPU_GetBufferFree();
int SPU_SetSampleRate();
int SPU_MixSamples();
int SPU_WaitIOPReady();
int SPU_Callback();
int SPU_SetupDMAThread();
int SPU_MountHDD();
int SPU_Nop();
int SPU_DebugDisasm();

/* ======================================== */

/* Function at 0x00213E50 - 0x00213E5C */
int SPU_Init()
{
    int a0, a2, a3;
    a2 = 0x00210000;
    a3 = 0x00210000;
    a0 = 0x1F800000;
}

/* Function at 0x00213E5C - 0x00213F08 */
int SPU_RegisterIO()
{
    /* Stack frame: 16 bytes */
    int ret, v1, a0, a1, a2, a3, t0, t1;
    a3 = a3 + 0x38e0;
    a2 = a2 + 0x3850;
    a0 = a0 | 0x1c00;
    a1 = 0x260;
    ret = R3000_SetupIOHandlers(a0, a1, a2, a3);
    a0 = 4;
    a1 = 0x002136B0;
    ret = Interrupt_SetCallback(a0, a1, a2, a3);
    a2 = 8 << 16;
    a0 = 0x007AB980;
    a1 = 0;
    ret = Libc_Memset(a0, a1, a2, a3);
    v1 = 0x004FA0D8;
    t1 = 0x005B0000 + -0x4e80;
    a3 = v1;
    a2 = v1 + 0x1fe;
    t0 = 0xff;
    do {
        a1 = *(u16*)*(a3 + 0x200);
        t0 = t0 + -1;
        ret = *(u16*)(a3);
        a3 = a3 + 2;
        v1 = *(u16*)*(a2 + 0x200);
        a1 = a1 << 16;
        a0 = *(u16*)(a2);
        a2 = a2 + -2;
        ret = ret | a1;
        v1 = (u64)v1 << 32;
        ret = ret | v1;
        a0 = (u64)a0 << 48;
        ret = ret | a0;
        *(u64*)*(t1 + 0) = ret;
        t1 = t1 + 8;
    } while ((signed)t0 >= 0);
    return 1;
}

/* Function at 0x00213F08 - 0x002140F0 */
int SPU_ProcessSamples()
{
    /* Stack frame: 80 bytes */
    int local_0C;
    int ret, v0, v1, a0, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6;
    v1 = g_spu_state1;
    s6 = 0x00850000;
    a1 = s6 + 0x970;
    a0 = 0xfb;
    s2 = *(u32*)*(a1 + 8);
    ret = ((unsigned)s2 < 0xfc) ? 1 : 0;
    __asm("movz s2, a0, v0");
    if (v1 == 0) {
        a1 = *(u32*)(a1);
        s4 = a0 - s2;
        s3 = 0;
        v1 = a1 + s2;
        a0 = s2;
        if ((unsigned)v1 >= 0x801) {
            s3 = v1 + -0x800;
            a0 = s2 - s3;
        }
        s5 = 0x00850000;
        ret = g_spu_ctrl0;
        s1 = a0 << 2;
        a1 = a1 << 2;
        s0 = s5 + 0x580;
        a1 = ret + a1;
        a0 = s0;
        a2 = s1;
        ret = Compiler_MemoryCopy(a0, a1, a2, a3);
        a1 = g_spu_ctrl0;
        if (s3 != 0) {
            a0 = s1 + s0;
            a2 = s3 << 2;
            ret = Compiler_MemoryCopy(a0, a1, a2, a3);
        }
        a0 = s2 << 2;
        if (s4 != 0) {
            a1 = s4 << 2;
            a0 = a0 + s0;
            ret = Compiler_MemoryClear(a0, a1, a2, a3);
            a0 = g_spu_ctrl1;
            goto loc_213FDC;
            }
            s5 = 0x00850000;
            a1 = 0x3ec;
            a0 = s5 + 0x580;
            ret = Compiler_MemoryClear(a0, a1, a2, a3);
        }
    a0 = g_spu_ctrl1;
loc_213FDC:
    ret = 0x0FFFFFFF;
    v1 = 0x20000000;
    a0 = a0 & ret;
    a1 = s5 + 0x580;
    a0 = a0 | v1;
    a2 = 0x100;
    ret = SPU_MixSamples(a0, a1, a2, a3);
    s0 = g_spu_state1;
    s1 = ret;
    if (s0 == 0) {
        s0 = s6 + 0x970;
        v1 = ((unsigned)s2 < (unsigned)s1) ? 1 : 0;
        ret = *(u32*)(s0);
        __asm("movn s1, s2, v1");
        ret = ret + s1;
        ret = ret & 0x7ff;
        *(u32*)(s0) = ret;
        ret = TLB_SetupEntries(a0, a1, a2, a3);
        v1 = *(u32*)*(s0 + 8);
        v1 = v1 - s1;
        *(u32*)*(s0 + 8) = v1;
        ret = System_EnableInterrupts(a0, a1, a2, a3);
        v1 = ((unsigned)s2 < 0xfb) ? 1 : 0;
        ret = 1;
        if (v1 == 0) goto loc_214068;
        g_spu_state1 = ret;
        goto loc_214068;
    }
    ret = s6 + 0x970;
    v1 = *(u32*)*(ret + 8);
    ret = 0;
    v1 = ((unsigned)v1 < 0x400) ? 1 : 0;
    __asm("movn v0, s0, v1");
    g_spu_state1 = ret;
loc_214068:
    a0 = __gp + -0x7db0;
    v1 = 0x400;
    ret = *(u32*)(a0);
    *(u32*)*(__sp + 8) = v1;
    a1 = ret & 1;
    ret = ret + 1;
    *(u32*)(a0) = ret;
    local_0C = 0;
    if (a1 != 0) {
        ret = g_spu_ctrl3;
        ret = ret + 0x400;
    } else {
        ret = g_spu_ctrl3;
    }
    *(u32*)*(__sp + 4) = ret;
    v1 = g_spu_ctrl1;
    ret = 0x0FFFFFFF;
    a0 = __sp;
    v1 = v1 & ret;
    a1 = 1;
    *(u32*)(sp) = v1;
    ret = UI_Kern_ExecOSD2(a0, a1, a2, a3);
    return 0;
}

/* Function at 0x002140F0 - 0x00214390 */
int SPU_AllocBuffers()
{
    /* Stack frame: 32 bytes */
    int local_0C;
    int ret, v1, a0, a1, a2, a3, s0, t0, t1;
    s0 = a0;
    a0 = 0 | 0xac44;
    ret = SPU_SetSampleRate(a0, a1, a2, a3);
    a0 = 0;
    ret = UI_Kern_GsPutIMR(a0, a1, a2, a3);
    a0 = 0x40;
    a1 = 0x2000;
    ret = EEKernel_SyscallWrapper(a0, a1, a2, a3);
    a2 = 0xc;
    a0 = 0x00850970;
    a1 = 0;
    g_spu_ctrl0 = ret;
    ret = Libc_Memset(a0, a1, a2, a3);
    a0 = 0x40;
    a1 = 0x800;
    ret = EEKernel_SyscallWrapper(a0, a1, a2, a3);
    a1 = 0x800;
    a0 = ret;
    g_spu_ctrl1 = ret;
    ret = Compiler_MemoryClear(a0, a1, a2, a3);
    ret = EEKernel_DMA_Channel1_Wait(a0, a1, a2, a3);
    a0 = s0;
    ret = EEKernel_VIF0_DMA_Transfer(a0, a1, a2, a3);
    a0 = 0;
    a2 = 0;
    a1 = 0x800;
    g_spu_ctrl2 = ret;
    ret = System_SifGetResult(a0, a1, a2, a3);
    a2 = ret;
    g_spu_ctrl3 = a2;
    if (a2 == 0) {
        a0 = 0x004FA640;
        ret = AssertionFailed(a0, a1, a2, a3);
        ret = 1;
        goto loc_21437C;
    }
    v1 = g_spu_ctrl1;
    ret = 0x0FFFFFFF;
    a0 = __sp;
    v1 = v1 & ret;
    ret = 0x800;
    a1 = 1;
    *(u32*)*(__sp + 4) = a2;
    *(u32*)*(__sp + 8) = ret;
    *(u32*)(sp) = v1;
    local_0C = 0;
    ret = UI_Kern_ExecOSD2(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8000;
    a2 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x980;
    a3 = 0x3fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xa80;
    a3 = 0x3fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x981;
    a3 = 0x3fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xa81;
    a3 = 0x3fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x800;
    a3 = 0xcc0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x801;
    a3 = 0xc0c;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a3 = 0x00213F08;
    a0 = 1;
    a1 = 0 | 0x8160;
    a2 = 0;
    t0 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    t0 = g_spu_ctrl3;
    t1 = 0x800;
    a1 = 0 | 0x80e0;
    a2 = 0;
    a3 = 0x10;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xd80;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xe80;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xf80;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x1080;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xd81;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xe81;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xf81;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x1081;
    a3 = 0x7fff;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xb80;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xc80;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xb81;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xc81;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    ret = 0;
loc_21437C:
    return ret;
}

/* Function at 0x00214390 - 0x00214418 */
int SPU_FreeBuffers()
{
    /* Stack frame: 16 bytes */
    int ret, a0, a1, a2, a3;
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0x981;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8010;
    a2 = 0xa81;
    a3 = 0;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x8070;
    a2 = 6;
    a3 = 1;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 1;
    a1 = 0 | 0x80e0;
    a2 = 0;
    a3 = 2;
    ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
    a0 = 0;
    ret = EEKernel_DMA_Quiet(a0, a1, a2, a3);
    a0 = g_spu_ctrl2;
    ret = UI_Kern_DeleteThread(a0, a1, a2, a3);
    a0 = g_spu_ctrl0;
    ret = Libc_Free(a0, a1, a2, a3);
    a0 = g_spu_ctrl1;
    ret = Libc_Free(a0, a1, a2, a3);
    a0 = g_spu_ctrl3;
    return System_SifGetStatus(a0, a1, a2, a3);
}

/* Function at 0x00214418 - 0x00214450 */
int SPU_Start()
{
    /* Stack frame: 16 bytes */
    int ret, v1, a0, a1, a2, a3;
    ret = EEKernel_DMA_Channel0_Wait(a0, a1, a2, a3);
    a0 = 1;
    ret = SPU_AllocBuffers(a0, a1, a2, a3);
    v1 = 1;
    ret = 1;
    g_spu_state0 = v1;
    return ret;
}

/* Function at 0x00214450 - 0x00214480 */
int SPU_Stop()
{
    /* Stack frame: 16 bytes */
    int ret, a0, a1, a2, a3;
    ret = SPU_FreeBuffers(a0, a1, a2, a3);
    g_spu_state0 = 0;
    return ret;
}

/* Function at 0x00214480 - 0x002144E8 */
int SPU_SetVoiceVolume()
{
    /* Stack frame: 32 bytes */
    int ret, v1, a0, a1, a2, a3, s0, s1;
    s0 = 0;
    s1 = a0 & 0x3fff;
    a2 = s0 | 0x980;
    do {
        a0 = 1;
        a1 = 0 | 0x8010;
        a3 = s1;
        ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
        a0 = 1;
        a2 = s0 | 0xa80;
        s0 = s0 + 1;
        a1 = 0 | 0x8010;
        a3 = s1;
        ret = EEKernel_VIF0_Initialize(a0, a1, a2, a3);
        v1 = ((signed)s0 < 2) ? 1 : 0;
        a2 = s0 | 0x980;
    } while (v1 != 0);
    return ret;
}

/* Function at 0x002144E8 - 0x00214500 */
int SPU_GetWritePtr()
{
    int ret, v1, a0;
    v1 = 0x00850000;
    a0 = g_spu_ctrl0;
    ret = *(u32*)*(v1 + 0x974);
    ret = ret << 2;
    ret = a0 + ret;
    return ret;
}

/* Function at 0x00214500 - 0x00214550 */
int SPU_AdvanceReadPtr()
{
    /* Stack frame: 32 bytes */
    int ret, v1, a0, a1, a2, a3, s0, s1;
    s1 = a0;
    s0 = 0x00850970;
    ret = s0->field_04;  /* field_04 */
    ret = ret + s1;
    ret = ret & 0x7ff;
    s0->field_04 = ret;  /* field_04 (store) */
    ret = TLB_SetupEntries(a0, a1, a2, a3);
    v1 = s0->sample_count;  /* sample_count */
    v1 = v1 + s1;
    s0->sample_count = v1;  /* sample_count (store) */
    return System_EnableInterrupts(a0, a1, a2, a3);
}

/* Function at 0x00214550 - 0x00214580 */
int SPU_GetBufferFree()
{
    int ret, v0, v1, a0, a1;
    a0 = 0x800;
    ret = *(u32*)*(0x00850970 + 8);
    a1 = *(u32*)*(v1 + 4);
    ret = a0 - ret;
    v1 = a1 + ret;
    a0 = a0 - a1;
    v1 = ((unsigned)v1 < 0x801) ? 1 : 0;
    __asm("movz v0, a0, v1");
    return ret;
}

/* Function at 0x00214580 - 0x002145B0 */
int SPU_SetSampleRate()
{
    int ret, v0, v1, a0;
    a0 = a0 << 0xc;
    ret = 0 | 0xbb80;
    __asm("divu zero, a0, v0");
    ret = 0;
    v1 = __gp + -0x7740;
    g_spu_ctrl6 = 0;
    *(u32*)(v1) = 0;
    a0 = LO;
    *(u32*)*(v1 + 4) = a0;
    g_spu_ctrl4 = a0;
    return ret;
}

/* Function at 0x002145B0 - 0x002147F0 */
int SPU_MixSamples()
{
    /* Stack frame: 80 bytes */
    int ret, v0, v1, a0, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6, s7, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    ret = __gp + -0x7740;
    s1 = a1;
    s2 = a0;
    s4 = 0;
    s5 = a2;
    s7 = 0;
    __fp = g_spu_ctrl4;
    s0 = *(u32*)*(ret + 4);
    s6 = *(u32*)(v0);
    s3 = g_spu_ctrl6;
    ret = TLB_SetupEntries(a0, a1, a2, a3);
    __asm("mmi3 a3, zero, zero");
    __asm("psllw a3, zero, a3");
    ret = 0x00500000;
    t9 = 0 | 0xffff;
    t8 = ret + -0x5980;
    do {
        ret = 0xff - s3;
        ret = ret << 6;
        ret = ret + t8;
        __asm(".word 0x06380000"); /* 0x00214630 EE unknown */
        __asm("nori.b w0, w0, 0x28");
        __asm("ave_s.h w0, w0, w9");
        __asm("ld.b w0, -0x1d6(zero)");
        t3 = *(u128*)*(s1 + 48);  /* lq */
        __asm("mmi1 t0, t1, t0");
        __asm("nori.b w1, w0, 0x2c");
        __asm("mmi1 t1, t2, t1");
        __asm("pref 0, (v0)");
        __asm("mmi1 t2, t3, t2");
        __asm("mmi1 t3, t4, t3");
        __asm("mmi2 t4, t0, a3");
        __asm("mmi2 t5, t1, a3");
        __asm("mmi2 t6, t2, a3");
        __asm("mmi2 t7, t3, a3");
        __asm("psllw t0, zero, t0");
        __asm("cop2 t4, vi9");
        __asm("psllw t1, zero, t1");
        __asm("cop2 t5, vi10");
        __asm("psllw t2, zero, t2");
        __asm("cop2 t6, vi11");
        __asm("psllw t3, zero, t3");
        __asm("cop2 t7, vi12");
        __asm("vu0_cop2 0x4be9493c");
        __asm("cop2 t0, vi5");
        __asm("vu0_cop2 0x4bea513c");
        __asm("cop2 t1, vi6");
        __asm("vu0_cop2 0x4beb593c");
        __asm("cop2 t2, vi7");
        __asm("vu0_cop2 0x4bec613c");
        __asm("cop2 t3, vi8");
        __asm("vu0_cop2 0x4be5293c");
        __asm("ldc2 1, (v0)");
        __asm("vu0_cop2 0x4be6313c");
        __asm("ldc2 2, 0x10(v0)");
        __asm("vu0_cop2 0x4be7393c");
        __asm("ldc2 3, 0x20(v0)");
        __asm("vu0_cop2 0x4be8413c");
        __asm("ldc2 4, 0x30(v0)");
        __asm("vu0_cop2 0x4be50abe");
        __asm("vu0_cop2 0x4be612bd");
        __asm("vu0_cop2 0x4be71abd");
        __asm("vu0_cop2 0x4be82169");
        __asm("vu0_cop2 0x4be90abe");
        __asm("vu0_cop2 0x4bea12bd");
        __asm("vu0_cop2 0x4beb1abd");
        __asm("vu0_cop2 0x4bec2269");
        __asm("vu0_cop2 0x4b052981");
        __asm("vu0_cop2 0x4b094a81");
        __asm("vu0_cop2 0x4a4529c3");
        __asm("vu0_cop2 0x4a494ac3");
        __asm("vu0_cop2 0x4b073202");
        __asm("vu0_cop2 0x4b0b5302");
        __asm("vu0_cop2 0x4b01417c");
        __asm("vu0_cop2 0x4b02617c");
        __asm("cop2 t0, vi1");
        __asm("cop2 t1, vi2");
        ret = t0 << 0;
        a1 = t1 << 0;
        t0 = 0 | 0x8000;
        __asm("mmi0 v0, v0, t0");
        __asm("mmi0 a1, a1, t0");
        a0 = s6 & 0xf000;
        s6 = s0;
        v1 = s0 & 0xf000;
        a0 = (signed)a0 >> 0xc;
        v1 = (signed)v1 >> 0xc;
        s4 = s4 + 1;
        a2 = v1 - a0;
        t2 = s0 & 0xff0;
        a0 = a2 + 0x10;
        v1 = ((signed)a2 < 0) ? 1 : 0;
        __asm("movn a2, a0, v1");
        v1 = ((signed)s4 < 0x100) ? 1 : 0;
        s0 = s0 + __fp;
        ret = (signed)ret >> 0x10;
        a1 = (signed)a1 >> 0x10;
        *(u16*)(s2) = ret;
        *(u16*)*(s2 + 0x200) = a1;
        s2 = s2 + 2;
        t0 = a2 << 2;
        t1 = ((signed)t9 < (signed)s0) ? 1 : 0;
        a0 = s0 & 0xffff;
        s5 = s5 + -1;
        if (v1 == 0) {
            s4 = 0;
            s2 = s2 + 0x200;
        }
        __asm("movn s0, a0, t1");
        if ((signed)a2 > 0) {
            s1 = s1 + t0;
            s7 = s7 + 1;
        }
        s3 = (signed)t2 >> 4;
    } while (s5 != 0);
    ret = System_EnableInterrupts(a0, a1, a2, a3);
    v1 = __gp + -0x7740;
    *(u32*)*(v1 + 4) = s0;
    ret = s7;
    *(u32*)(v1) = s6;
    g_spu_ctrl6 = s3;
    return ret;
}

/* Function at 0x002147F0 - 0x00214888 */
/* String ref: "pfs:" */
int SPU_WaitIOPReady()
{
    /* Stack frame: 64 bytes */
    int ret, a0, a1, a2, a3, s0, s1, s2, s3, t0, t1;
    s0 = 0x00500000;
    s1 = a0;
    s2 = 0x00500000;
    s3 = 0x00500000;
loc_214818:
    a0 = s1;
    ret = UI_Kern_WaitSema(a0, a1, a2, a3);
    a0 = s3 + -0x1980;
    ret = AssertionFailed(a0, a1, a2, a3);
    a0 = s2 + 0x28d0;
    a1 = 0x5003;
    a2 = 0;
    a3 = 0;
    t0 = 0;
    t1 = 0;
    ret = System_SifLoadModule5(a0, a1, a2, a3);
    a0 = s0 + 0x28d8;
    do {
        a1 = 0x4806;
        a2 = 0;
        a3 = 0;
        t0 = 0;
        t1 = 0;
        ret = System_SifLoadModule5(a0, a1, a2, a3);
        a0 = s0 + 0x28d8;
    } while (likely((signed)ret < 0));
loc_214868:
    a0 = __sp;
    ret = System_BootTimerSetup(a0, a1, a2, a3);
    ret = *(u32*)(sp);
    if (ret == 0) goto loc_214868;
    if (ret != 0) goto loc_214868;
    goto loc_214818;
}

/* Function at 0x00214888 - 0x002148A0 */
int SPU_Callback()
{
    /* Stack frame: 16 bytes */
    int a0, a1, a2, a3;
    return UI_Kern_iSignalSema(a0, a1, a2, a3);
}

/* Function at 0x002148A0 - 0x00214938 */
int SPU_SetupDMAThread()
{
    /* Stack frame: 112 bytes */
    int local_0C;
    int local_10;
    int local_14;
    int local_34;
    int local_38;
    int local_44;
    int ret, v1, a0, a1, a2, a3, s0, s1;
    s0 = 1;
    a0 = __sp + 0x30;
    local_34 = s0;
    local_38 = 0;
    local_44 = 0;
    ret = UI_Kern_CreateSema(a0, a1, a2, a3);
    a2 = 0x00850980;
    a0 = __sp;
    v1 = 0x0050A670;
    s1 = ret;
    a1 = 0x002147F0;
    ret = 0x2000;
    *(u32*)*(__sp + 4) = a1;
    local_14 = s0;
    local_0C = ret;
    local_10 = v1;
    *(u32*)*(__sp + 8) = a2;
    ret = UI_Kern_CreateThread(a0, a1, a2, a3);
    a0 = ret;
    a1 = s1;
    ret = UI_Kern_StartThread(a0, a1, a2, a3);
    a1 = s1;
    a0 = 0x00214888;
    ret = System_DisplaySetResolution(a0, a1, a2, a3);
    return ret;
}

/* Function at 0x00214938 - 0x002149E0 */
/* String ref: "hdd0:__common" */
/* String ref: "pfs0:" */
/* String ref: "pfs1:" */
int SPU_MountHDD()
{
    /* Stack frame: 32 bytes */
    int ret, a0, a1, a2, a3, s0, s1, t0;
    s0 = a0;
    ret = SPU_SetupDMAThread(a0, a1, a2, a3);
    a0 = 0x005028E0;
    a1 = 0x004FE6A0;
    a2 = 0;
    a3 = 0;
    t0 = 0;
    ret = System_SifLoadModule4(a0, a1, a2, a3);
    s1 = ret;
    a1 = s0;
    a0 = 0x005028E8;
    a2 = 0;
    a3 = 0;
    t0 = 0;
    if ((signed)s1 < 0) {
        a1 = s1;
        a0 = 0x004FE6B0;
    } else {
        ret = System_SifLoadModule4(a0, a1, a2, a3);
        s1 = ret;
        ret = 0;
        a1 = s1;
        a0 = 0x004FE6D8;
            ret = AssertionFailed(a0, a1, a2, a3);
            ret = s1;
        }
    return ret;
}

/* Function at 0x002149E0 - 0x002149E8 */
int SPU_Nop()
{
    return 0;
}

/* Function at 0x002149E8 - 0x00215088 */
/* String ref: "  0x%08x: 0x%08x  " */
/* String ref: ".word   0x%08x" */
/* String ref: "%s%x" */
int SPU_DebugDisasm()
{
    /* Stack frame: 208 bytes */
    int local_60;
    int local_64;
    int local_68;
    int local_6C;
    int local_70;
    int local_74;
    int local_78;
    int local_7C;
    int ret, v0, v1, a0, a1, a2, a3, s0, s1, s2, s3, s4, s5, s6, s7, t0, t1;
    s3 = a1;
    s7 = a0;
    a2 = s7;
    a0 = __sp;
    a1 = 0x004FEEB8;
    a3 = s3;
    ret = Libc_GetReentStruct(a0, a1, a2, a3);
    v1 = 0x00250000;
    s0 = __sp + ret;
    a0 = v1 + -0x5310;
loc_214A40:
    a1 = *(u32*)(a0);
    a1 = 0x00500000;
    if (a1 != 0) {
        ret = *(u32*)*(a0 + 4);
        v1 = *(u32*)*(a0 + 8);
        ret = s3 & ret;
        a0 = a0 + 0x10;
        if (likely(ret != v1)) goto loc_214A40;
        ret = *(u32*)*(a0 + 0xc);
        ret = ret & 0x1000;
        a0 = a0 + 0x10;
        if (likely(ret != 0)) goto loc_214A40;
        s2 = a1;
        if (a1 == 0) {
            a1 = 0x00500000;
            }
            a0 = s0;
            a1 = 0x004FEED0;
            a2 = s3;
            ret = Libc_GetReentStruct(a0, a1, a2, a3);
            a0 = 0x00502D68;
            a1 = __sp;
            ret = AssertionFailed(a0, a1, a2, a3);
        } else {
            ret = *(s8*)(s2);  /* lb */
            t1 = *(u8*)(s2);
            if (ret == 0) goto loc_215044;
            v1 = (unsigned)s3 >> 0xb;
            ret = (unsigned)s3 >> 0x1a;
            local_60 = v1;
            v1 = ret & 7;
            local_64 = ret;
            s5 = (unsigned)s3 >> 0x10;
            ret = local_60;
            s6 = (unsigned)s3 >> 6;
            v1 = v1 << 5;
            a2 = s5 & 0x1f;
            a1 = ret & 0x1f;
            a0 = s6 & 0x1f;
            t0 = v1 + a1;
            a3 = a2 << 2;
            a0 = a0 << 2;
            a1 = a1 << 2;
            v1 = v1 + a2;
            ret = 0x0024B420;
            __fp = t0 << 2;
            v1 = v1 << 2;
            a3 = a3 + 0x80;
            a1 = a1 + 0x80;
            a0 = a0 + 0x80;
            a0 = a0 + ret;
            v1 = v1 + ret;
            a3 = a3 + ret;
            a1 = a1 + ret;
            ret = __fp + ret;
            t0 = s7 & t0;
            local_7C = a0;
            local_68 = v1;
            s4 = 0x00500000;
            local_74 = a3;
            local_78 = a1;
            local_70 = t0;
            local_6C = ret;
            loc_214B50:
            ret = t1 << 0x18;
            a0 = (signed)ret >> 0x18;
            v1 = 0x00500000;
            v1 = v1 + a0;
            v1 = *(u8*)*(v1 + 0x1f31);
            ret = v1 & 2;
            a1 = __sp + 0x50;
            if (ret == 0) {
                ret = v1 & 1;
                v1 = a0;
                s2 = s2 + 1;
                if (ret != 0) {
                    ret = v1 + 0x20;
                    ret = ret << 0x18;
                    v1 = (signed)ret >> 0x18;
                }
                *(u8*)(s0) = v1;
                s0 = s0 + 1;
                *(u8*)(s0) = 0;
                goto loc_215038;
            }
            s2 = s2 + 1;
            s1 = a1;
            a1 = __sp + 0x51;
            *(u8*)(s1) = t1;
            *(u8*)(a1) = 0;
            goto loc_214BC8;
            loc_214BB8:
            *(u8*)(a1) = a0;
            a1 = a1 + 1;
            *(u8*)(a1) = 0;
            s2 = s2 + 1;
            loc_214BC8:
            v1 = *(s8*)(s2);  /* lb */
            ret = 0x00500000;
            ret = ret + v1;
            ret = *(u8*)*(ret + 0x1f31);
            ret = ret & 2;
            a0 = *(u8*)(s2);
            if (ret != 0) goto loc_214BB8;
            a1 = s1;
            a0 = 0x00502D70;
            ret = Libc_Strcmp(a0, a1, a2, a3);
            if (ret == 0) {
                ret = (unsigned)s3 >> 0x13;
                v1 = 0x0024B3A0;
                ret = ret & 0x7c;
                ret = ret + v1;
                a0 = s0;
                a2 = *(u32*)(v0);
                a1 = s4 + 0x2d78;
            } else {
                a1 = s1;
                a0 = a0 + 0x2d80;
                ret = Libc_Strcmp(a0, a1, a2, a3);
                if (ret == 0) {
                    ret = s5 & 0x1f;
                    v1 = 0x0024B3A0;
                    ret = ret << 2;
                    ret = ret + v1;
                    a0 = s0;
                    a2 = *(u32*)(v0);
                    a1 = s4 + 0x2d78;
                } else {
                    a1 = s1;
                    a0 = a0 + 0x2d88;
                    ret = Libc_Strcmp(a0, a1, a2, a3);
                    if (ret == 0) {
                        v1 = local_60;
                        a0 = s0;
                        a1 = s4 + 0x2d78;
                        ret = v1 & 0x1f;
                        v1 = 0x0024B3A0;
                        ret = ret << 2;
                        ret = ret + v1;
                        a2 = *(u32*)(v0);
                        goto loc_21502C;
                    }
                    a1 = s1;
                    a0 = a0 + 0x2d90;
                    ret = Libc_Strcmp(a0, a1, a2, a3);
                    if (ret == 0) {
                        ret = local_68;
                        a0 = s0;
                        a1 = s4 + 0x2d78;
                        a2 = *(u32*)(v0);
                    } else {
                        a1 = s1;
                        a0 = a0 + 0x2d98;
                        ret = Libc_Strcmp(a0, a1, a2, a3);
                        if (ret == 0) {
                            v1 = local_6C;
                            a0 = s0;
                            a1 = s4 + 0x2d78;
                            a2 = *(u32*)(v1);
                        } else {
                            a1 = s1;
                            a0 = a0 + 0x2da0;
                            ret = Libc_Strcmp(a0, a1, a2, a3);
                            if (ret == 0) {
                                a2 = 0x00250000;
                                a2 = a2 + __fp;
                                a2 = *(u32*)*(a2 + -0x49e0);
                                a0 = s0;
                                a1 = s4 + 0x2d78;
                                goto loc_21502C;
                            }
                            a1 = s1;
                            a0 = a0 + 0x2da8;
                            ret = Libc_Strcmp(a0, a1, a2, a3);
                            a0 = 0x00500000;
                            if (ret == 0) {
                                ret = s3 & 0x8000;
                                a3 = s3 & 0xffff;
                                if (ret != 0) {
                                    a3 = a3 | 0xFFFF0000;
                                }
                                if ((signed)a3 < 0) {
                                    ret = 0x2d;
                                    __asm("negu a3, a3");
                                    *(u8*)(s0) = ret;
                                    s0 = s0 + 1;
                                    ret = 0x00500000;
                                }
                                v1 = ((unsigned)a3 < 0xa) ? 1 : 0;
                                a1 = ret + 0x2db0;
                                if (v1 != 0) {
                                    a2 = 0x00500000 + 0x2db8;
                                    goto loc_214D80;
                                }
                                a2 = 0x00500000 + 0x2dc0;
                                loc_214D80:
                                a0 = s0;
                                ret = Libc_GetReentStruct(a0, a1, a2, a3);
                                s0 = s0 + ret;
                            } else {
                                a1 = s1;
                                a0 = a0 + 0x2dc8;
                                ret = Libc_Strcmp(a0, a1, a2, a3);
                                if (ret == 0) {
                                    a0 = s0;
                                    a1 = 0x00502DD0;
                                    a2 = s3 & 0xffff;
                                } else {
                                    a1 = s1;
                                    a0 = a0 + 0x2dd8;
                                    ret = Libc_Strcmp(a0, a1, a2, a3);
                                    a0 = 0x00500000;
                                    if (ret == 0) {
                                        a3 = s6 & 0x1f;
                                        ret = 0x00500000;
                                        v1 = ((signed)a3 < 0xa) ? 1 : 0;
                                        a1 = ret + 0x2db0;
                                        if (v1 != 0) {
                                            a2 = 0x00500000 + 0x2db8;
                                            goto loc_214DF8;
                                        }
                                        a2 = 0x00500000 + 0x2dc0;
                                        loc_214DF8:
                                        a0 = s0;
                                        ret = Libc_GetReentStruct(a0, a1, a2, a3);
                                        s0 = s0 + ret;
                                    } else {
                                        a1 = s1;
                                        a0 = a0 + 0x2de0;
                                        ret = Libc_Strcmp(a0, a1, a2, a3);
                                        a0 = 0x00500000;
                                        if (ret == 0) {
                                            v1 = 0x00500000;
                                            ret = s3 & 0x8000;
                                            a1 = v1 + 0x2de8;
                                            v1 = s3 & 0xffff;
                                            a2 = s7 + 4;
                                            if (ret != 0) {
                                                ret = v1 | ret;
                                                ret = ret << 2;
                                                goto loc_214E4C;
                                            }
                                            ret = v1 << 2;
                                            loc_214E4C:
                                            a2 = a2 + ret;
                                            a0 = s0;
                                        } else {
                                            a1 = s1;
                                            a0 = a0 + 0x2df0;
                                            ret = Libc_Strcmp(a0, a1, a2, a3);
                                            if (ret == 0) {
                                                v1 = local_70;
                                                a2 = 0x03FFFFFF;
                                                ret = 0x00500000;
                                                a2 = s3 & a2;
                                                a0 = s0;
                                                a2 = a2 << 2;
                                                a1 = ret + 0x2de8;
                                                a2 = v1 | a2;
                                                goto loc_21502C;
                                            }
                                            a1 = s1;
                                            a0 = a0 + 0x2df8;
                                            ret = Libc_Strcmp(a0, a1, a2, a3);
                                            if (ret == 0) {
                                                ret = 0x00500000;
                                                a2 = 0x000FFFFF;
                                                a0 = s0;
                                                a1 = ret + 0x2e00;
                                                a2 = s6 & a2;
                                            } else {
                                                a1 = s1;
                                                a0 = a0 + 0x2e08;
                                                ret = Libc_Strcmp(a0, a1, a2, a3);
                                                if (ret == 0) {
                                                    v1 = 0x00500000;
                                                    a2 = 0x01FFFFFF;
                                                    a0 = s0;
                                                    a1 = v1 + 0x2e00;
                                                    a2 = s3 & a2;
                                                } else {
                                                    a1 = s1;
                                                    a0 = a0 + 0x2e10;
                                                    ret = Libc_Strcmp(a0, a1, a2, a3);
                                                    if (ret == 0) {
                                                        v1 = local_64;
                                                        ret = 0x00500000;
                                                        a0 = s0;
                                                        a1 = ret + 0x2e18;
                                                        a2 = v1 & 7;
                                                        goto loc_21502C;
                                                    }
                                                    a1 = s1;
                                                    a0 = a0 + 0x2e20;
                                                    ret = Libc_Strcmp(a0, a1, a2, a3);
                                                    if (ret == 0) {
                                                        ret = 0x00500000;
                                                        a0 = s0;
                                                        a1 = ret + 0x2e18;
                                                        a2 = s5 & 0x1f;
                                                    } else {
                                                        a1 = s1;
                                                        a0 = a0 + 0x2e28;
                                                        ret = Libc_Strcmp(a0, a1, a2, a3);
                                                        if (ret == 0) {
                                                            v1 = 0x00500000;
                                                            a2 = (unsigned)s3 >> 1;
                                                            a0 = s0;
                                                            a2 = a2 & 0x1f;
                                                            a1 = v1 + 0x2e18;
                                                            goto loc_21502C;
                                                        }
                                                        a1 = s1;
                                                        a0 = a0 + 0x2e30;
                                                        ret = Libc_Strcmp(a0, a1, a2, a3);
                                                        if (ret == 0) {
                                                            ret = 0x00500000;
                                                            a0 = s0;
                                                            a1 = ret + 0x2e00;
                                                            a2 = s5 & 0x1f;
                                                        } else {
                                                            a1 = s1;
                                                            a0 = a0 + 0x2e38;
                                                            ret = Libc_Strcmp(a0, a1, a2, a3);
                                                            if (ret == 0) {
                                                                v1 = local_74;
                                                                a0 = s0;
                                                                a1 = s4 + 0x2d78;
                                                                a2 = *(u32*)(v1);
                                                            } else {
                                                                a1 = s1;
                                                                a0 = a0 + 0x2e40;
                                                                ret = Libc_Strcmp(a0, a1, a2, a3);
                                                                if (ret == 0) {
                                                                    ret = local_78;
                                                                    a0 = s0;
                                                                    a1 = s4 + 0x2d78;
                                                                    a2 = *(u32*)(v0);
                                                                } else {
                                                                    a1 = s1;
                                                                    a0 = a0 + 0x2e48;
                                                                    ret = Libc_Strcmp(a0, a1, a2, a3);
                                                                    if (ret == 0) {
                                                                        v1 = local_7C;
                                                                        a0 = s0;
                                                                        a1 = s4 + 0x2d78;
                                                                        a2 = *(u32*)(v1);
                                                                    } else {
                                                                        a0 = s0;
                                                                        a2 = s1;
                                                                        a1 = a1 + 0x2e50;
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                        }
                                                                    }
                                        loc_21502C:
                                        ret = Libc_GetReentStruct(a0, a1, a2, a3);
                                        s0 = s0 + ret;
                                        }
                                    }
            loc_215038:
            ret = *(s8*)(s2);  /* lb */
            t1 = *(u8*)(s2);
            if (ret != 0) goto loc_214B50;
            loc_215044:
            a1 = __sp;
            a0 = 0x00502D68;
            *(u8*)(s0) = 0;
            ret = AssertionFailed(a0, a1, a2, a3);
        }
    return ret;
}
